### ISSUE TITLE
Alternative code icon

### ISSUE THREAD

**Issue by sh7dm** [Remix-Design/RemixIcon#10]
## Icon Request
I'd like to see alternative code icon with slash, like this: `</>`

* Icon name: code-2
* Tags of this icon: code, programming, hacking, development
* Use case: show if there is any code
* Screenshots of similar icons: `code` icon

**Comment by xiaochunjimmy** [comment]
Got it~
You'll see it in the next icon version~

**Comment by xiaochunjimmy** [comment]
Hey man, you can find it [here](https://remixicon.com/#development) now!
Do you like it？😀不用客气！
