### ISSUE TITLE
Tools/service icon

### ISSUE THREAD

**Issue by IrkaPo** [Remix-Design/RemixIcon#100]
## Icon Request

* Icon name: service/tools
* Tags of this icon: 
* Use case: for auto diler's sites
* Screenshots of similar icons: https://gyazo.com/95b7d91da36fa4c0136f90392b62c324

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Design/tools-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Design/tools-line.svg
