### ISSUE TITLE
steering icon

### ISSUE THREAD

**Issue by IrkaPo** [Remix-Design/RemixIcon#101]
## Icon Request

* Icon name: steering
* Tags of this icon: 
* Use case: for test-drive btns
* Screenshots of similar icons: https://gyazo.com/b196220a11115a5fd69f98b90bc76234

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Map/steering-2-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Map/steering-2-line.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Map/steering-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Map/steering-line.svg
