### ISSUE TITLE
open folder

### ISSUE THREAD

**Issue by froeb** [Remix-Design/RemixIcon#102]
Greetings and thank you for the huge amount of icons. It offers the possibility, to have all icons on a website in the same style, what is very useful.

I was a little surprised though, that in the files/folder section, an icon for an open folder is missing.

I need/use this to illustrate a directory hiearchy, where the current folder (and parent folder) is open with an open folder icon, while the other ones are closed.

Also, as others have already said, an icon for selecting languages, like the one at wikipedia, would be useful too. 

Thank you
Kai
http://kai.froeb.net

**Comment by xiaochunjimmy** [comment]
We've added the open folder icons, thank you for your advice.
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-open-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-open-line.svg
You can also find the from our website https://remixicon.com/#document
