### ISSUE TITLE
中文着重号图标

### ISSUE THREAD

**Issue by Alecyrus** [Remix-Design/RemixIcon#103]
非常感谢你们带来如此优秀的图标。

## Icon Request

* Icon name:  着重号
* Tags of this icon: emphasis
* Use case:  编辑器中，中文着重号
* Screenshots of similar icons: 目前没找着其他有关于中文着重号的 Icon
着重号如下图，测量学下面的点，就是着重号，这是中文里面特有的符号，现在暂时使用 文本颜色 （左边这个红框）这个 Icon 来代替的：
![2051571800713_ pic_hd](https://user-images.githubusercontent.com/13865581/67354487-d0900400-f587-11e9-9dc4-2d4df3537b55.jpg)

**Comment by xiaochunjimmy** [comment]
在图标中居中一个点就可以是吧？点的大小多大比较合适？

**Comment by Alecyrus** [comment]
大概 这么大？ 可以是一个 E 下面 三个点吧，就和下划线那个差不多。

**Comment by xiaochunjimmy** [comment]
我明白了，之前理解有误，点大小我们来把控就OK

**Comment by xiaochunjimmy** [comment]
已更新：
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Editor/emphasis.svg

**Comment by Alecyrus** [comment]
@xiaochunjimmy  我觉得这样设计会有不妥当，非常抱歉之前给了不好的建议。着重号作为中文行文中特有的标点符号，我觉得 图标的上部分不应该是 E(emphasis)，而是 “文” （比如 translate-2 图标中的 ‘文’ 图案），这样更能体现图标的原本意义。
