### ISSUE TITLE
Icon request: offline mode/connection fail

### ISSUE THREAD

**Issue by Lisavdmerwe** [Remix-Design/RemixIcon#106]
Hi! I'm currently using the icons for our app & love them.

I was wondering whether you could include an 'offline mode/connection fail' icon, like here: https://material.io/design/communication/offline-states.html#offline-functionality

I did a quick one myself based on your cloud icon and added a stripe through it, but would be great if the devs can pull it straight from your library :)

**Comment by xiaochunjimmy** [comment]
Hi, Lisa, Long-time no see! Thank you for your love and suggestion!
How about a wifi icon with a stripe through it?

**Comment by xiaochunjimmy** [comment]
I would design both wifi and cloud icon. You may find them in the next version after a few days.

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Business/cloud-off-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Business/cloud-off-line.svg

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/wifi-off-line.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/wifi-off-fill.svg

**Comment by Lisavdmerwe** [comment]
Hi! Definitely :) How have you been?
I'm really loving your icon library, keep up the great work!

I am looking for an icon that can be used for both the internet connection
(whether it's wifi or 4G), but also when some data fails to load from the
API (in that case, the cloud icon is more suitable).
So I think the cloud icon would be better, and we might use it for both
cases.

Lisa van de Merwe
Experience Designer
Email lisa.merwe@thoughtworks.com
WeChat lisavandemerwe
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=lisa-van%20de%20merwe-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by Lisavdmerwe** [comment]
I see the icons now, they are great! You are so fast to reply haha. Thanks
a lot!

Lisa van de Merwe
Experience Designer
Email lisa.merwe@thoughtworks.com
WeChat lisavandemerwe
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=lisa-van%20de%20merwe-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by xiaochunjimmy** [comment]
Waiting for your next visit to Xi'an, haha

**Comment by Lisavdmerwe** [comment]
Haha, I'm not that far away actually. On a project in Chengdu now.

Lisa van de Merwe
Experience Designer
Email lisa.merwe@thoughtworks.com
WeChat lisavandemerwe
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=lisa-van%20de%20merwe-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by xiaochunjimmy** [comment]
So you are cooperating with Tutu now?

**Comment by Lisavdmerwe** [comment]
No, I haven't seen her in the office actually. Last time I saw her, she was
in the Shanghai office!

Lisa van de Merwe
Experience Designer
Email lisa.merwe@thoughtworks.com
WeChat lisavandemerwe
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=lisa-van%20de%20merwe-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>
