### ISSUE TITLE
Downloaded SVG zip cannot be opened

### ISSUE THREAD

**Issue by guoyunhe** [Remix-Design/RemixIcon#107]
**Describe the bug**
In official website, I downloaded several icons in SVG format. But the downloaded zip file cannot be extracted. 

**To Reproduce**
1. Go to website.
2. Select several icons.
3. Download by clicking "SVG" button.
4. Open the downloaded *.zip file.
**Expected behavior**
The *.zip file should be able to extract and get SVG files.

**Device (please complete the following information):**
 - OS: openSUSE Tumbleweed Linux
 - Browser &amp; Version Firefox 69.0.3
 - Website Version 2.0.0

**Additional context**

**Comment by wendygaoyuan** [comment]
Hello~
我在Ubuntu 18.04 Firefox 69.0.3上按照步骤并没有出现无法解压的情况。
可能需要在openSUSE再测试一下，能提供一下你使用的版本吗？我还没有用过openSUSE呢🙊

**Comment by guoyunhe** [comment]
openSUSE Tumbleweed + KDE. 用的解压软件是 Ark。
