### ISSUE TITLE
Icon request: <Gatsby>

### ISSUE THREAD

**Issue by DemoRoy** [Remix-Design/RemixIcon#118]
## Icon Request

* Icon name: Gatsby
* Tags of this icon: ri-gatsby
* Use case: The brand of the Gatsby

* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/24954686/68198486-1b356580-fff7-11e9-8b59-1b38683b59ce.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-gatsby-line
https://remixicon.com/#icon-gatsby-fill
