### ISSUE TITLE
Icon Request: Pixelfed

### ISSUE THREAD

**Issue by moqmar** [Remix-Design/RemixIcon#119]
## Icon Request

* Icon name: pixelfed
* Tags of this icon: logos, photography, social media
* Use case: Just like the Instagram icon, this icon could be used to refer to the federated equivalent Pixelfed when linking to social media accounts.
* Screenshots of similar icons: the logo can be seen at https://pixelfed.org

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/#icon-pixelfed-line
https://www.remixicon.com/#icon-pixelfed-fill
