### ISSUE TITLE
User Shield

### ISSUE THREAD

**Issue by davilla20** [Remix-Design/RemixIcon#12]
## Icon Request

* Icon name: user shield
* Tags of this icon: user protected, guarantor
* Use case: 
* Screenshots of similar icons:https://www.google.com/search?q=user+shield+icon&rlz=1C1CHBF_enTZ843TZ843&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjqyorLrLjhAhVTuHEKHQ71CeYQ_AUIDigB&biw=1280&bih=648#imgrc=tYilrrCqm746MM:

**Comment by xiaochunjimmy** [comment]
Got it~
We'll add this icon in the next icon version

**Comment by xiaochunjimmy** [comment]
Here's the `shield user` icon for you.
[shield-user-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/shield-user-line.svg)
[shield-user-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/shield-user-fill.svg)
