### ISSUE TITLE
Icon Update: Edge

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#120]
Microsoft Edge recently changed their icon to this:

![image](https://user-images.githubusercontent.com/33750251/69447577-b4ca7a00-0d4e-11ea-8bb4-4a2f98c3dfed.png)

https://46c4ts1tskv22sdav81j9c69-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/2/2019/11/8c9568e0875e71b5c0397f39c50a87f8.gif

**Comment by xiaochunjimmy** [comment]
(⊙o⊙)…

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/edge-new-line
https://www.remixicon.com/icon/edge-new-fill
