### ISSUE TITLE
Icon Request: icon for HWP file

### ISSUE THREAD

**Issue by hletrd** [Remix-Design/RemixIcon#121]
## Icon Request

* Icon name: HWP file
* Tags of this icon: hwp
* Use case: hwp
* Screenshots of similar icons: 

  - Sample icon
![Sample icon](https://gist.githubusercontent.com/hletrd/95e5eab3d84342db19bb5ee27eeaeb19/raw/1c086b912a3eec1bac8cb15aeb3fbb1c7b20cd77/file_hwp.svg?sanitize=true)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
<path fill="none" d="M0 0h24v24H0z"/>
<!--border-->
<path d="M21 8v12.993A1 1 0 0 1 20.007 22H3.993A.993.993 0 0 1 3 21.008V2.992C3 2.455 3.449 2 4.002 2h10.995L21 8zm-2 1h-5V4H5v16h14V9z"/>
<!--The icon-->
<path d="M8.8 8.5m0.225 1.215l2.16 0l0 -1.125l1.08 0l0 1.125l2.16 0l0 1.08l-5.4 0l0 -1.08zm2.7 1.35a1.845 1.71 0 0 1 0 3.42a1.845 1.71 0 0 1 0 -3.42zm0 0.99a0.495 0.45 0 1 0 0 1.44a0.495 0.45 0 1 0 0 -1.44zm0 2.88a0.63 0.585 0 0 1 0 1.17a0.63 0.585 0 0 1 0 -1.17m-2.88 0.315l1.08 0l0 1.44l4.59 0l0 0.99l-5.67 0l0 -2.43z"/>
</svg>
```

I made an icon for hwp file, which is a document format created by [Hangul Word Processor](https://en.wikipedia.org/wiki/Hangul_(word_processor)).
Inspired from the official logo of hancom office hwp. (Refer to [https://play.google.com/store/apps/details?id=com.hancom.office.hwp.editor.hwp_apk.gplaystore&hl=en](https://play.google.com/store/apps/details?id=com.hancom.office.hwp.editor.hwp_apk.gplaystore&hl=en))

**Comment by xiaochunjimmy** [comment]
Thank you for your design. I've redesigned the icon to make it looks more clear.
https://remixicon.com/#icon-file-hwp-line
https://remixicon.com/#icon-file-hwp-fill
