### ISSUE TITLE
Icon Request: Flutter icon

### ISSUE THREAD

**Issue by phanirithvij** [Remix-Design/RemixIcon#122]
## Icon Request

* Icon name: flutter
* Tags of this icon: logo
* Use case: Flutter framework's logo
* Screenshots of similar icons: 
This contains an svg of their official color logo found on the top navbar on https://flutter.dev
[flutter.zip](https://github.com/Remix-Design/RemixIcon/files/3908623/flutter.zip)

![](https://res.cloudinary.com/rootworld/image/upload/v1575228109/flutter.png)

**Comment by phanirithvij** [comment]
![](https://res.cloudinary.com/rootworld/image/upload/v1575228109/flutter.png)

**Comment by phanirithvij** [comment]
It's also on https://simpleicons.org/icons/flutter.svg

**Comment by xiaochunjimmy** [comment]
The SVG file in the zip pack is a fake SVG witch is not a vector file. [facepulm]

**Comment by phanirithvij** [comment]
Oh I'm sorry about that. I saved it from flutter.dev. This is the link for the [svg](https://flutter.dev/assets/flutter-lockup-4cb0ee072ab312e59784d9fbf4fb7ad42688a7fdaea1270ccf6bbf4f34b7e03f.svg).
If the link expires. You can find it in their official website https://flutter.dev

**Comment by xiaochunjimmy** [comment]
That's OK, I've finished the logo icons, you will meet them in a few days.
The SVG file on the official website is not really a vector file. It is a PNG format image and been converted to base64 encoding, then embedded in the SVG format, but still a bitmap.

**Comment by xiaochunjimmy** [comment]
We've done the job!
Search `flutter` on https://remixicon.com and you'll find them.
