### ISSUE TITLE
Icon Request: SoundCloud

### ISSUE THREAD

**Issue by schwei23** [Remix-Design/RemixIcon#123]
## Icon Request

* Icon name: SoundCloud
* Tags of this icon: logos
* Use case: an unified icon with other Remix Icons
* Screenshots of similar icons: can be seen on https://soundcloud.com/

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-soundcloud-line
https://remixicon.com/#icon-soundcloud-fill
