### ISSUE TITLE
Icon Request : Movie Genre

### ISSUE THREAD

**Issue by chacawaca** [Remix-Design/RemixIcon#124]
​Action Genre
Animation Genre
Comedy Genre
Crime Genre
Drama Genre
Experimental Genre
Fantasy Genre
Historical Genre
Horror Genre
Romance Genre
Science Fiction Genre
Thriller Genres
Western Genres
Other Genres

**Comment by xiaochunjimmy** [comment]
Is there any picture of your icon request?

**Comment by chacawaca** [comment]
something like this 
https://st2.depositphotos.com/1502311/12019/v/950/depositphotos_120192184-stock-illustration-movie-genres-icon-set-vector.jpg

**Comment by xiaochunjimmy** [comment]
I see, I will add some of them in the next version, but may not be categorized according to the genre of the movies. They may be distributed to the existing categories.

**Comment by xiaochunjimmy** [comment]
You can use those icons:

Action Genre → https://remixicon.com/#icon-criminal-fill
Animation Genre → https://remixicon.com/#icon-star-smile-line
Comedy Genre → https://remixicon.com/#icon-emotion-laugh-line
Crime Genre → https://remixicon.com/#icon-knife-blood-line
Drama Genre → https://remixicon.com/#icon-emotion-sad-line
Experimental Genre → https://remixicon.com/#icon-flask-line
Fantasy Genre → https://remixicon.com/#icon-magic-line
Historical Genre → https://remixicon.com/#icon-sword-line
Horror Genre → https://remixicon.com/#icon-ghost-line
Romance Genre → https://remixicon.com/#icon-hearts-line
Science Fiction Genre → https://remixicon.com/#icon-aliens-line
Thriller Genres → https://remixicon.com/#icon-treasure-map-line
Western Genres → https://remixicon.com/#icon-shield-star-line
Other Genres → https://remixicon.com/#icon-clapperboard-line
