### ISSUE TITLE
Icon Request: Test/Flask icon

### ISSUE THREAD

**Issue by baryla** [Remix-Design/RemixIcon#125]
## Icon Request

* Icon name: Test / Testing / Flask
* Tags of this icon: test, testing, flask
* Use case: 
* Screenshots of similar icons:

![iconmonstr-flask-1](https://user-images.githubusercontent.com/10336085/70793584-85c68780-1d93-11ea-8df3-b46f1b764954.png)

**Comment by xiaochunjimmy** [comment]
Here are your icons:
https://remixicon.com/#icon-flask-line
https://remixicon.com/#icon-flask-fill
