### ISSUE TITLE
Copy CSS on site

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#126]
I love the new "Copy SVG" feature on the site.

I often use that feature, but to have it as a background CSS I also need to use this tool:

https://yoksel.github.io/url-encoder/

Not sure how hard it is, but having a "Copy CSS" directly on your site would be a great addition.

Thanks!

**Comment by xiaochunjimmy** [comment]
Than you for this feature suggestion.

**Comment by xiaochunjimmy** [comment]
I noticed that there's a feature of this tool:
External quotes: single / double

Is this feature useful for you? how about only support double quotes?

**Comment by jenstornell** [comment]
@xiaochunjimmy I don't care about the quote type because it's just a copy paste from my part.

Double quotes looks better and are most common I think.

**Comment by xiaochunjimmy** [comment]
Have a try on our new feature.
<img width="771" alt="new feature@2x" src="https://user-images.githubusercontent.com/6701827/72221429-b1f14600-3595-11ea-8393-29c8be4539fd.png">

**Comment by jenstornell** [comment]
@xiaochunjimmy I have tested it now exactly one time and it worked flawless! 👍 

I'll let you know if it breaks. I'm building a site with your icons involved so I'll test it many times during the next week.

Closing this for now.

Big thanks!
