### ISSUE TITLE
Icon Request: A/B Testing

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#128]
## Icon Request

* Icon name: a/b testing
* Tags of this icon: testing, ab test
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/49694573/72215583-84c37a00-353a-11ea-886f-fe6f12aaaa39.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-a-b

You can find it in the `Editor` category.
