### ISSUE TITLE
OpenSans not loaded and fallback does not work

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#129]
I don't have OpenSans installed on this computer and on the site, most of the time it works because it has a fallback like this:

```
font-family: OpenSans,PingFang SC,Arial,Helvetica Neue,Microsoft YaHei,sans-serif;
```

On some elements like `.icon-edit-bar .icon-svg-msg .svg-content .info[data-v-eefac682]` it does not have any fallback and fails where OpenSans is not installed.

```
font-family: OpenSans;
```

## Solution

```
.icon-edit-bar .icon-svg-msg .svg-content .info[data-v-eefac682] {
    font-family: OpenSans;
    padding: 16px 40px 40px;
    height: 160px;
    overflow-y: scroll;

    /* Add this line */
    font-family: OpenSans,PingFang SC,Arial,Helvetica Neue,Microsoft YaHei,sans-serif;
}
```

***The missing font is missing on more elements. You can probably search in the code to find them***

**Comment by xiaochunjimmy** [comment]
Thanks, we'll fix it next version.
