### ISSUE TITLE
Icon Request: Recycle

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#130]
## Icon Request

* Icon name: recycle
* Tags of this icon: recycle
* Use case: Identify an entity as recyclable
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/72226187-2de39200-3586-11ea-9652-0050e17f9416.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-recycle-line
https://remixicon.com/#icon-recycle-fill
