### ISSUE TITLE
Icon(s) Request: Tick and Double Tick

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#131]
## Icon Request

* Icon name: tick, double-tick
* Tags of this icon: tick, double-tick
* Use case: Whatsapp like ticks, to notify communication has ben sent and read
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/72226479-8a947c00-3589-11ea-943c-0e6c830af891.png)

**Comment by xiaochunjimmy** [comment]
Is this what you want?

https://remixicon.com/#icon-check-double-line

I'll add the tags to this icon later.

**Comment by itsezc** [comment]
> Is this what you want?
> 
> https://remixicon.com/#icon-check-double-line
> 
> I'll add the tags to this icon later.

Thanks, its what I needed!
