### ISSUE TITLE
Icon Request: Incognition / Secret

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#132]
## Icon Request

* Icon name: secret
* Tags of this icon: secret
* Use case: Many, i.e. Browsers
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/72226573-700ed280-358a-11ea-948d-5957da313a87.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-spy-line
https://remixicon.com/#icon-spy-fill

You can find them in the `user&faces` category.
Thank you for your advice.
