### ISSUE TITLE
Icon Request: Passport

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#133]
## Icon Request

* Icon name: passport
* Tags of this icon: passport
* Use case: Passports
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/72226598-d09e0f80-358a-11ea-88f7-52882041f19f.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-passport-line
https://remixicon.com/#icon-passport-fill
