### ISSUE TITLE
Icon(s) Request: Travel

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#134]
## Icon Request

* Icon name: caravan, campsite, cactus
* Tags of this icon: caravan, campsite, cactus
* Use case: Travel
* Screenshots of similar icons:

Caravan:
![image](https://user-images.githubusercontent.com/33750251/72226677-a731b380-358b-11ea-89b8-e89126fb9f06.png)

Monument:

![image](https://user-images.githubusercontent.com/33750251/72226685-c2042800-358b-11ea-8512-c32b91316075.png)

Suitcase:

![image](https://user-images.githubusercontent.com/33750251/72226698-d2b49e00-358b-11ea-9574-a3adb9193d67.png)

![image](https://user-images.githubusercontent.com/33750251/72226716-02fc3c80-358c-11ea-9f61-2ca514cbea2a.png)

Swim:

![image](https://user-images.githubusercontent.com/33750251/72226723-13141c00-358c-11ea-88d2-733118e88dd2.png)

Cactus:

![image](https://user-images.githubusercontent.com/33750251/72226728-1dceb100-358c-11ea-8ea1-268a52000db3.png)

Luggage Cart:

![image](https://user-images.githubusercontent.com/33750251/72226734-2f17bd80-358c-11ea-91d7-c80de6aabc7d.png)

Swimming Pool:

![image](https://user-images.githubusercontent.com/33750251/72226736-38a12580-358c-11ea-9ca9-cc41bbb3cabb.png)

Traffic:

![image](https://user-images.githubusercontent.com/33750251/72226741-49519b80-358c-11ea-92ce-99481fc42baa.png)

Some of these icons are applicable for the Map category but a new Travel category would be good

**Comment by xiaochunjimmy** [comment]
Yes, the `Map` category can be divided into `Map`, `Travel` and `Restaurant` in the future.
