### ISSUE TITLE
Icon Request: Install and Uninstall icons

### ISSUE THREAD

**Issue by bicobus** [Remix-Design/RemixIcon#135]
## Icon Request

* Icon name: install-software, uninstall-software
* Tags of this icon: install, uninstall
* Use case: provide iconography of software being installed or uninstalled
* Screenshots of similar icons: Difficult to provide, as the means of install can vary based on the support (.exe install being different than cloud based install).

**Comment by xiaochunjimmy** [comment]
I've added `install` and `uninstall` icons based on the `hard-drive-2` icons.
You can find them in the `device` category.

https://remixicon.com/#icon-install-line
https://remixicon.com/#icon-install-fill
https://remixicon.com/#icon-uninstall-line
https://remixicon.com/#icon-uninstall-line

But, I'd prefer `delete-bin` icons as `uninstall`.
