### ISSUE TITLE
Icon Request: unzip, unarchive, unpack

### ISSUE THREAD

**Issue by bicobus** [Remix-Design/RemixIcon#136]
## Icon Request

* Icon name: unzip
* Tags of this icon: unzip, unpack, extract
* Use case: archival of data
* Screenshots of similar icons:
![extract-multiple-zip-files](https://user-images.githubusercontent.com/26164751/72668898-e77daf80-3a2b-11ea-89e5-2cc3555e81e0.png)

![extract-file-icons-45001](https://user-images.githubusercontent.com/26164751/72668897-e0ef3800-3a2b-11ea-8ba7-802a545c3ddd.png)

**Comment by bicobus** [comment]
Could be based on the [upload icon](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/upload-2-fill.svg), with the arrow pointing towards the side.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-inbox-unarchive-line
https://remixicon.com/#icon-inbox-unarchive-fill

You can also use `external-link`, `picture-in-picture-exit`, or `aspect-ratio` as your unarchive icon.
https://remixicon.com/#icon-external-link-line
https://remixicon.com/#icon-picture-in-picture-exit-line
https://remixicon.com/#icon-aspect-ratio-line
