### ISSUE TITLE
Icon Request(s): Menu (Alternative styles)

### ISSUE THREAD

**Issue by elitenoire** [Remix-Design/RemixIcon#137]
## Icon Request
Thank you for the beautiful icons.
* Icon name: Menu
* Tags of this icon: menu, hamburger, bars
* Use case: To open or close mobile menu, side drawers etc. 
* Screenshots of similar icons:
![menu-3](https://user-images.githubusercontent.com/25673419/72865836-8d097b00-3cd9-11ea-88c2-d05ec9ca8d6a.jpg)

![menu-4](https://user-images.githubusercontent.com/25673419/72865944-ee314e80-3cd9-11ea-8dff-fe2cb1e7a733.jpg)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#system

You'll see them in the first row of the `system` category.
Thank you for your advice and samples.
