### ISSUE TITLE
Icon Request: Balancing scales

### ISSUE THREAD

**Issue by umberbeard** [Remix-Design/RemixIcon#138]
## Icon Request

* Icon name: Scales
* Tags of this icon: Balance, Scales
* Use case: When representing something that requires a balance, either in the literal or figurative sense. For example, video games have the concept of 'balancing' characters, and one might want to use the scales icon to represent a rebalance
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/4073554/72959104-28dcca80-3d5e-11ea-8316-06de217800e7.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-scales-line
https://remixicon.com/#icon-scales-fill
