### ISSUE TITLE
Remix icon logo

### ISSUE THREAD

**Issue by sh7dm** [Remix-Design/RemixIcon#14]
## Icon Request

* Icon name: Remix icon
* Tags of this icon: remix-icon
* Use case: mention Remix icon
* Screenshots of similar icons: -

**Comment by xiaochunjimmy** [comment]
Hi~ We've add `Remixicon`icons;
[`remixicon-line`](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/remixicon-line.svg) 
[`remixicon-fill`](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/remixicon-fill.svg)
