### ISSUE TITLE
Icon Request(s): Exchange/Swap without boxes

### ISSUE THREAD

**Issue by binary-koan** [Remix-Design/RemixIcon#140]
## Icon Request

* Icon name: exchange/swap (-bare? -arrows?)
* Tags of this icon: 
* Use case: Switching between equivalent forms (e.g. date picker vs dropdown menu). Would be useful when the icons are small and the box/circle around the existing icons doesn't show up well
* Screenshots of similar icons:
![Screen Shot 2020-01-28 at 11 13 47 AM](https://user-images.githubusercontent.com/1077405/73230159-a326a800-41bf-11ea-99f4-63482f09f6a6.png)
![Screen Shot 2020-01-28 at 11 16 43 AM](https://user-images.githubusercontent.com/1077405/73230171-ae79d380-41bf-11ea-8bb3-1dc4f55534e6.png)
![Screen Shot 2020-01-28 at 11 14 12 AM](https://user-images.githubusercontent.com/1077405/73230160-a3bf3e80-41bf-11ea-8a81-c974cb1809d1.png)

**Comment by xiaochunjimmy** [comment]
You can find them in the `System` category. 

https://remixicon.com/#icon-arrow-left-fill
https://remixicon.com/#icon-arrow-left-line
https://remixicon.com/#arrow-up-down-fill
https://remixicon.com/#arrow-up-down-line
