### ISSUE TITLE
Icon Request: Layout 3/1

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#141]
## Icon Request

* Icon name: layout-3
* Tags of this icon: layout
* Use case: When building applications with this type of layout. It can be even more layouts when rotated which is nice.
* Screenshots of similar icons:

https://thenounproject.com/term/layout/18048/

## Update

Many other great layout icons (looks like RemixIcon to me): https://dribbble.com/shots/6287682-Layout-Icons

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#design

I've added some new layout icons. 
Thank you for your advice and samples.
