### ISSUE TITLE
Icon Request: Sort asc / desc

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#143]
## Icon Request

* Icon name: sort-asc / sort-desc
* Tags of this icon: sort,order,ascending,descending
* Use case: For sorting values in forms and lists
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/927011/73723748-15e8d380-472a-11ea-8a56-e33c73c158d2.png)

https://www.iconbolt.com/iconsets/font-awesome-solid/sort-amount-down

## Note

In order for it to work, two icons are needed, one for asc and one for desc. The difference will be the arrow direction.

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/#icon-sort-desc
https://www.remixicon.com/#icon-sort-asc
