### ISSUE TITLE
What is the invisible 24x24 path used for?

### ISSUE THREAD

**Issue by vdh** [Remix-Design/RemixIcon#144]
I've noticed there's always a `<path fill="none" d="M0 0h24v24H0z"/>` path inside every icon, but I couldn't find any documentation mentioning why it's there or what it's used for.

It seems redundant since the `viewBox="0 0 24 24"` already sets the size, but I was wondering if it serves some other sort of functionality I'm not aware of?

**Comment by xiaochunjimmy** [comment]
Thank you for your question.

The path `<path fill="none" d="M0 0h24v24H0z"/>` is a 24*24 rectangle.
This is made for designers. Designers can get a 24*24 icon with paddings when they insert our icons.
With uniform-size icons, designers can easily manage and align their icons and elements.

With the path, all icons are visually aligned.

![Artboard](https://user-images.githubusercontent.com/6701827/73913845-fd77e500-48f2-11ea-9b72-b8194264a0f6.png)

If the path puzzled you in your projects, we could talk about it.

**Comment by vdh** [comment]
@xiaochunjimmy Ahh okay, so they exist for development use and don't have a use in production? Would it be safe to trim out the path with optimisation tools such as `svgo` when deploying assets to production?

**Comment by xiaochunjimmy** [comment]
Our icons are compressed by svgo, svgo will not trim the paths we intentionally draw.
You mean remove the path when convert icons into fonts?

**Comment by vdh** [comment]
Sorry I meant in a custom svgo in our own distributions, not RemixIcon's own svgo setup.
