### ISSUE TITLE
Icon request: npm

### ISSUE THREAD

**Issue by timqian** [Remix-Design/RemixIcon#145]
## Icon Request

* Icon name: npm
* Tags of this icon: logos
* Use case: https://www.npmjs.com/ is wildly used
* Screenshots of similar icons:

<img width="22" alt="Screen Shot 2020-02-08 at 1 38 20 AM" src="https://user-images.githubusercontent.com/5512552/74051849-b9303600-4a13-11ea-9600-aea0bebbe4b7.png">

**Comment by xiaochunjimmy** [comment]
Thank you for your advice, brother Qian.

**Comment by xiaochunjimmy** [comment]
Here are the npm icons.
https://remixicon.com/#icon-npmjs-line
https://remixicon.com/#icon-npmjs-fill

**Comment by timqian** [comment]
👍
