### ISSUE TITLE
Icon Request: Open Source

### ISSUE THREAD

**Issue by guoyunhe** [Remix-Design/RemixIcon#149]
## Icon Request

* Icon name: opensource or open-source
* Tags of this icon: logos
* Use case: any open source projects' websites
* Screenshots of similar icons: https://opensource.org/
![image](https://user-images.githubusercontent.com/5836790/75090657-b2ee9d80-556d-11ea-8b0c-14a1e33a06e4.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-open-source-line
https://remixicon.com/#icon-open-source-fill

**Comment by czlucius** [comment]
@xiaochunjimmy 
May I ask if this icon is compliant to the Open Source Initiative trademark and logo guidelines? I am looking to use this in my app.
https://opensource.org/logo-usage-guidelines
https://opensource.org/trademark-guidelines
From clause 1.1.3 of the logo usage guidelines, it seems that the OSI keyhole logo without the wordmark bears a registered trademark symbol (®)

Thank you.

**Comment by xiaochunjimmy** [comment]
@czlucius 
The logos in RemixIcon are all iconized and adjusted according to the icon style of RemixIcon, not the original logo file. 
So if the scenarios of your usage get very strict specifications on the use of logos, such as printing, partners, etc., it is recommended to obtain the original logo symbols from the official website.

**Comment by czlucius** [comment]
Ok, thank you!

好，谢谢!
