### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by sh7dm** [Remix-Design/RemixIcon#15]
## Icon Request

* Icon name: patreon
* Tags of this icon: patreon, donate, money, app
* Use case: patreon donation button
* Screenshots of similar icons: -

**Comment by xiaochunjimmy** [comment]
Hi~ We've add `Patreon`icons;
[`patreon-line`](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/patreon-line.svg) 
[`patreon-fill`](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/patreon-fill.svg) 

If those are what you want, please close this issue.
