### ISSUE TITLE
Icon request: Disqus

### ISSUE THREAD

**Issue by tterb** [Remix-Design/RemixIcon#153]
## Icon Request

* Icon name: Disqus
* Tags of this icon: logos
* Use case: Social link for Disqus users
* Screenshots of similar icons:  

![Disqus icon](https://user-images.githubusercontent.com/16360374/76136236-384d6580-5fe4-11ea-8b7c-2a42f1ae553b.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-Disqus-line
https://remixicon.com/#icon-Disqus-fill
