### ISSUE TITLE
Icon Update: Stackshare in wrong category

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#154]
The stackshare icon is located in the wrong category (currently in Development), it belongs in the Logos category

Also, the logo always has a background rectangle that has a border radius 
![image](https://user-images.githubusercontent.com/33750251/76148139-52964a80-609b-11ea-9d48-fdc60ab9fa7f.png)

This is missing from the icon set

**Comment by xiaochunjimmy** [comment]
Oh, stack-share is a logo!!!??
I thought it is a kind of action in development.
I'll fix it later

**Comment by xiaochunjimmy** [comment]
I've moved the stackshare icon from `development` to `logos` and redesigned the  `-fill` icon.
Have a look at it here(https://remixicon.com/#icon-stackshare-fill) .
