### ISSUE TITLE
Icon request: leaf

### ISSUE THREAD

**Issue by elumbroso** [Remix-Design/RemixIcon#156]
## Icon Request

* Icon name: leaf
* Tags of this icon: leaf, ecology
* Use case: energy-saving mode, website about ecology...
* Screenshots of similar icons: 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/1764889/76338920-b453f000-62f9-11ea-9366-ba6e56111d77.png">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-leaf-line
https://remixicon.com/#icon-leaf-fill
