### ISSUE TITLE
Icon(s) Request: Video Upload and Download

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#157]
## Icon Request

* Icon name: Video Upload/Download
* Tags of this icon: video-upload, video-download
* Use case: Useful for video sites, when they need to upload or downlod
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/76376715-de7cd080-6340-11ea-88ad-365494240ef6.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-video-add-line
https://remixicon.com/#icon-video-add-fill

https://remixicon.com/#icon-video-upload-line
https://remixicon.com/#icon-video-upload-fill

https://remixicon.com/#icon-video-download-line
https://remixicon.com/#icon-video-download-fill
