### ISSUE TITLE
Icon request: GIF 

### ISSUE THREAD

**Issue by harshapulikollu** [Remix-Design/RemixIcon#158]
## Icon Request

* Icon name: GIF icon
* Tags of this icon: GIF
* Use case: To indicate user that's a GIF.
* Screenshots of similar icons: https://www.flaticon.com/free-icon/gif_1373418?term=gif&page=1&position=56

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-file-gif-line
https://remixicon.com/#icon-file-gif-fill
