### ISSUE TITLE
Zip file has extra Mac OS dot-files

### ISSUE THREAD

**Issue by quasipickle** [Remix-Design/RemixIcon#159]
The zip file (for downloading the entire library) contains a `_MACOSX` folder with copies of all icons.  It greatly increases the size of the zip file and the time it takes to unzip.

**Comment by xiaochunjimmy** [comment]
Thank you for your reminding.
This appears to be hidden files automatically generated by the Mac OS.
We'll try to delete this folder before the compression next time.

**Comment by xiaochunjimmy** [comment]
http://cdn.remixicon.com/releases/RemixIcon_SVG_v2.4.0.zip
Please check whether the new zip file contains OSX file, thank you!

**Comment by quasipickle** [comment]
No, it looks like it doesn't.  The ZIP file is half the size too.  Thanks!

**Comment by xiaochunjimmy** [comment]
Thank you again, we did not notice that in the past versions, your issue helps a lot.
