### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by AndiLeni** [Remix-Design/RemixIcon#160]
Hello,

I noticed, that the website is not accessible by me. 
If this problem is already under investigation feel free to close this issue.

Regards
Andi

**Comment by xiaochunjimmy** [comment]
Is it possible to visit our website now? 
I've tested and it is accessible from my device.
https://remixicon.com

**Comment by AndiLeni** [comment]
Apparently it's because of my ISP, the German Telekom. I have already sent an email to their technical department and am now waiting for an answer. But until then, the website seems to be unreachable via this provider.

**Comment by xiaochunjimmy** [comment]
If it ’s a problem with an overseas Internet service provider, we really can’t help.
Thank you for trying to solve the problem.
Waiting for your further information.

**Comment by mixn** [comment]
I can confirm this issue — same ISP, German Telekom.

**Comment by xiaochunjimmy** [comment]
@AndiLeni @mixn 
Many other users told us they have the same problem: could not access our website.
We've reported this problem to our server provider, but they need more information to locate the problem: 
such as `Ping remixicon.com` `traceroute remixicon.com` and `dig remixicon.com` info.
We could not repetition this problem from our side, so could you help us use these commands in your terminal and send screenshots of the results here?

**Comment by AndiLeni** [comment]
Here is the output. Unfortunately the output is not very helpfull, at least from my windows machine. 

```
ping remixicon.com
Ping request could not find host "remixicon.com". Check the name and try again.
```

```
TRACERT remixicon.com
The target name remixicon.com could not be resolved.
```

**Comment by xiaochunjimmy** [comment]
@AndiLeni Thank you soooo much, could you send us the output of `traceroute remixicon.com` and `dig remixicon.com`?

**Comment by AndiLeni** [comment]
```
; <<>> DiG 9.16.2 <<>> remixicon.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9711
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;remixicon.com.                 IN      A

;; ANSWER SECTION:
remixicon.com.          581     IN      CNAME   remix-icon.b0.aicdn.com.
remix-icon.b0.aicdn.com. 300    IN      CNAME   vo.aicdn.com.

;; Query time: 1213 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Thu May 07 13:22:17 Mitteleuropõische Sommerzeit 2020
;; MSG SIZE  rcvd: 93
```
The traceroute equivalent is the TRACERT command as shown in my last post. It only says what I have already posted.

**Comment by xiaochunjimmy** [comment]
@AndiLeni  O_O...I see. Thank you so much.

**Comment by wendygaoyuan** [comment]
@AndiLeni  Thank you the info you provided. It seems that the node IP is not resolved, you can change the public DNS, such as 8.8.8.8, and try again

**Comment by xiaochunjimmy** [comment]
@mixn @AndiLeni @jenstornell 

Hi there,
Could you get access to https://remixicon.com and https://www.remixicon.com now?
How long does it take to finish loading？
We need your help to know whether our new service provider is viable for oversea users.

**Comment by AndiLeni** [comment]
@xiaochunjimmy Both of them work fine now.
The www version takes about 4-5 seconds to load for the first time while the url without the www in fronf of it seems to be a bit slower (about 2 seconds).

**Comment by jenstornell** [comment]
@xiaochunjimmy It works but a bit slow. "Page Total - 4.91 secs" with Page Size Inspector Chrome extension. I'm on a really fast connection.
