### ISSUE TITLE
Icon Request: Steam

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#162]
## Icon Request

* Icon name: Steam
* Tags of this icon: game, store
* Use case: logo for [steam](https://store.steampowered.com/) （As a way to socialize）
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/25154432/77381914-fa10be00-6db9-11ea-95eb-0b78f4b0a2e6.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-steam-line
https://remixicon.com/#icon-steam-fill
