### ISSUE TITLE
Line chart icon

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#164]
## Icon Request

* Icon name: line-chart
* Tags of this icon: chart, stats, line
* Use case: Charts
* Screenshots of similar icons:

https://boxicons.com/

![line-chart-regular-24](https://user-images.githubusercontent.com/927011/77918066-aad7fb00-729b-11ea-9142-aae15002a082.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-line-chart-line
https://remixicon.com/#icon-line-chart-fill

`bubble chart` and `donut chart` are also available, too.
