### ISSUE TITLE
Recent Icon

### ISSUE THREAD

**Issue by Alecyrus** [Remix-Design/RemixIcon#167]
## Icon Request

* Icon name:  Recent / time-machine
* Tags of this icon:  recent / time-machine
* Use case: 最近文件，最近打开，最近文档
* Screenshots of similar icons:
<img width="98" alt="截屏2020-04-13 08 11 55" src="https://user-images.githubusercontent.com/13865581/79083090-7285f180-7d5e-11ea-8f82-c8df4f79eb10.png">

**Comment by xiaochunjimmy** [comment]
We'll add it to the next version in a few days.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/#icon-history-line
