### ISSUE TITLE
Subscript and Superscript Icons

### ISSUE THREAD

**Issue by hennson** [Remix-Design/RemixIcon#17]
## Icon Request

* Icon name:  Subscript
* Tags of this icon: #subscript
* Use case: in Editor to trigger subscript of characters
* Screenshots of similar icons: used one of yours to remix ;-)
![subscript](https://user-images.githubusercontent.com/1113639/56264121-c2978d00-60e5-11e9-86b6-c4dd88c1bb10.png)
---
* Icon name:  Superscript
* Tags of this icon: #superscript
* Use case: in Editor to trigger superscript of characters
* Screenshots of similar icons: used one of yours to remix ;-)
![superscript](https://user-images.githubusercontent.com/1113639/56264134-caefc800-60e5-11e9-9da5-36917880c5a0.png)

**Comment by xiaochunjimmy** [comment]
I'm sorry, but I'm afraid I didn't understand what you mean.  
The screenshots are so small to identify.  

Do you mean you need an icon used in editor, witch can trigger the feature that input subscript or superscript? Just like this?
![demo](https://i.loli.net/2019/04/17/5cb72b1f482a3.png)

**Comment by hennson** [comment]
Yes, this is actually what I meant...

![subscript](https://user-images.githubusercontent.com/1113639/56307004-34062880-6144-11e9-9b26-ca4a70b9eec6.png)
![superscript](https://user-images.githubusercontent.com/1113639/56307005-34062880-6144-11e9-9328-02274f2b6fe8.png)

**Comment by xiaochunjimmy** [comment]
I'm glad to tell you...
[Here](https://remixicon.com/#editor) are the icons that you requested.

**Comment by hennson** [comment]
Pretty good! Thank you!
