### ISSUE TITLE
H1 - H6 icons for text editor

### ISSUE THREAD

**Issue by lanyusan** [Remix-Design/RemixIcon#171]
## Icon Request

* Icon name: 

heading1, heading2,...,heading6

* Tags of this icon: 

Heading, level

* Use case: 

For text editors to set heading level.

* Screenshots of similar icons:

**Comment by Alecyrus** [comment]
这个是真的需要，拜托了 @xiaochunjimmy

**Comment by xiaochunjimmy** [comment]
下一个版本的图标已经封版了，只能下下次上线时添加了。 @Alecyrus
