### ISSUE TITLE
Change the heart symbol and add the Mac and Windows symbols :)

### ISSUE THREAD

**Issue by paladio** [Remix-Design/RemixIcon#174]
Hello dear friend, this icon collection is very beautiful and practical, and I congratulate you for designing it. It will only be great if you change or add a few items in it.
First of all, change the **symbol of the heart** and try to give it a more **curved, more arched and more attractive state**. The heart symbol can be more attractive and curved because it is also very practical. An attractive heart symbol can attract more audience attention. Here are some examples of good and great designs to add something like these to this icon pack:

**Try to add a variety of widely used icon and symbols So that the user has more choice.**

**Add the link symbol horizontally**  ( There is a diagonal sample right now in pack )

Add new " question "symbols, the question mark symbol, in small dimensions and dark background, loses its clarity completely.In general, the question symbol should be larger.

[question ](https://fontawesome.com/icons/question?style=solid)

[heart symbol example 1](https://linearicons.com/free/icon/heart)

[heart symbol example 2](https://www.flaticon.com/free-icon/heart_1216575)

[heart symbol example 3](https://www.flaticon.com/free-icon/passion_446072?term=heart&page=1&position=33)

[heart symbol example 4](https://www.flaticon.com/premium-icon/heart_441193?term=heart&page=2&position=33)

[heart symbol example 5](https://www.flaticon.com/free-icon/heart_1077035)

Try adding the **Macintosh** , **Windows** ( new version ) and Linux symbols to this collection, and the **dashboard** symbol will be great for **admin panels** if added. Change the **Android** icon to make it more compatible with other icons. I think it is very important to **change** the symbol of the heart . 

thank you for this valuable collection :)

[Windows Example](https://fontawesome.com/icons/windows?style=brands)

[Mac Example](https://icons8.com/icon/122980/mac-logo) With a circular frame.

[Mac Example](https://p1.hiclipart.com/preview/867/1007/719/button-ui-system-icons-finder1-mac-os-logo-png-clipart.jpg)

[Mac Example](https://lh5.googleusercontent.com/proxy/h1cuUCuw2Z8L9FMeW1YhjpTbiso7NTyCXtzsSDfUCn7XRjev0QO07InlzI19CoBzKRpIMLQJeTSmefA0eQYE_b1uucxjQrF3TwzZ)

[Dashboard Example](https://fontawesome.com/icons?d=gallery&q=dashboard)

[Door](https://fontawesome.com/icons?d=gallery&q=door)

[Door](https://fontawesome.com/icons/door-open?style=solid)

[USB](https://www.flaticon.com/premium-icon/usb_2723565?term=usb&page=1&position=90)

[USB](https://www.flaticon.com/premium-icon/usb_2723562)

[USB](https://www.flaticon.com/free-icon/usb_254642?term=usb&page=1&position=80)

[USB](https://fontawesome.com/icons/usb?style=brands)

**The "  user symbol  "  is great now, and try adding a few more modes :) Don't change the current sample and just add new ones**

for new symble of heart , windows and user look at :  [ heart , windows and user symble ](https://ionicons.com/)

for new symble of Arrow with curved or rounded edge , message and download look at :  [ curved or rounded edge , message and download ](https://akveo.github.io/eva-icons/#/)

**Comment by xiaochunjimmy** [comment]
Thank you there, I will add the icons you suggested days(maybe longer) later in the next version.
If you have any other icon suggestions or feedback, feel free to open new issues.
And we'll be very grateful if you could recommend our icons to your friends.

**Comment by Qualima** [comment]
I updated the first comment in this post and added new suggestions to it, see the first comment, thank you.

**Comment by Qualima** [comment]
@xiaochunjimmy 
I updated the first comment in this post and added new suggestions to it, see the first comment, thank you.

**Comment by xiaochunjimmy** [comment]
I'd prefer you to open new issues for new icons' suggestion next time. [facepalm]

**Comment by xiaochunjimmy** [comment]
This is the life-ring icon.
https://www.remixicon.com/#icon-lifebuoy-fill
