### ISSUE TITLE
Icon Request: 思维导图

### ISSUE THREAD

**Issue by Alecyrus** [Remix-Design/RemixIcon#175]
## Icon Request

* Icon name:  mindmap
* Tags of this icon: mindmap
* Use case: 思维导图
* Screenshots of similar icons:
<img width="279" alt="截屏2020-04-23 10 25 40" src="https://user-images.githubusercontent.com/13865581/80052239-cbb70780-854c-11ea-9314-90087f1f3d30.png">

**Comment by xiaochunjimmy** [comment]
思维导图图标已添加，我先暂时关闭这个 issue 了
