### ISSUE TITLE
Remixicon web site off line

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [Remix-Design/RemixIcon#179]
**Describe the bug**
Unable to connect to the remix icon.com web site

**To Reproduce**
1. Go to 'https://remixicon.com'

**Comment by xiaochunjimmy** [comment]
What is your geographical position?
I can access our website from our side.

**Comment by marcelSchmidtC02** [comment]
I'm having the same issue... Geographical position is Austria

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 We are trying to solve this problem, but still have no idea what the problem is.
Can you get a screen capture of browser console to help us locate the error report?

**Comment by marcelSchmidtC02** [comment]
@xiaochunjimmy 
No message in the console, because there's no page to be found
![siteNotFound](https://user-images.githubusercontent.com/60009233/80916775-24f81580-8d5b-11ea-8d8f-1f39e5af7497.PNG)

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 Thank you for your information.
Can you ping remixicon.com in the terminal and see if any packets transmitted and received?

**Comment by marcelSchmidtC02** [comment]
@xiaochunjimmy 
Host not found
![siteNotFound3](https://user-images.githubusercontent.com/60009233/80917321-53c3bb00-8d5e-11ea-9b74-0789ce77bd6b.PNG)

**Comment by wendygaoyuan** [comment]
@marcelSchmidtC02 
Can you provide screenshots of traceroute remixicon.com and dig remixicon.com?

**Comment by xiaochunjimmy** [comment]
This problem may be caused by our server or your internet service provider.
We've submitted a repair order to our service provider for more information.

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/issues/160

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 We've reported this problem to our server provider, but they need more information to locate the problem: like the traceroute and dig info.
We could not repetition this problem from our side, so could you help us get more information?

**Comment by Qualima** [comment]
Hi, I also have this problem from **Iran**, even with **vpn** the problem is not solved, this issue can bother many users, and try to solve this issue as soon as possible, you can change the web server.
Thankful

**Comment by xiaochunjimmy** [comment]
@Qualima Thank you for your information

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 @Qualima We are trying to use another hosting service provider for foreign users, could you get access to https://remixicon.com now?
As we could not test this problem from our side, so I need your info, Thank you.

**Comment by marcelSchmidtC02** [comment]
Still not working
![grafik](https://user-images.githubusercontent.com/60009233/81571130-d58c9780-93a1-11ea-9483-04575aba5fa9.png)

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 How about this link?
https://remixicon.web.app/

**Comment by marcelSchmidtC02** [comment]
This link works fine

**Comment by xiaochunjimmy** [comment]
@marcelSchmidtC02 How about https://remixicon.com now?

**Comment by medatech** [comment]
Just jumping in here in case this helps. In the UK, I'm getting an SSL cert error, and when you bypass it says "Site not found" in Firebase.

![image](https://user-images.githubusercontent.com/1839214/81576514-403cd380-93a0-11ea-9cc6-eb9c7e818e8e.png)

If I ping it, it's doing the following
```
ping remixicon.com
PING remixicon.web.app (151.101.1.195): 56 data bytes
64 bytes from 151.101.1.195: icmp_seq=0 ttl=57 time=28.248 ms
64 bytes from 151.101.1.195: icmp_seq=1 ttl=57 time=10.674 ms
64 bytes from 151.101.1.195: icmp_seq=2 ttl=57 time=13.830 ms
```

So looks like the cname to `remixicon.web.app` is there, but maybe firebase hasn't been configured to accept the remixicon.com host domain.

**Comment by xiaochunjimmy** [comment]
@medatech Thank you for your explanation.
This is the first time I using firebase and I just have finished the configuration. It needs some time (in 24h) to take effect. I hope you can access to our website later.
Please try both https://remixicon.com and https://www.remixicon.com later to see if the DNSPod was configured successfully.

**Comment by medatech** [comment]
Thank you @xiaochunjimmy, I appreciate your hard work on this. It looks like https://remixicon.com is working now so I suspect the www is still propagating. All the best!

**Comment by kbakba** [comment]
now problem with certificate.
```
openssl s_client -connect remixicon.com:443 | grep CN

depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = GTS CA 1O1
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = firebaseapp.com
verify return:1
 0 s:/C=US/ST=California/L=Mountain View/O=Google LLC/CN=firebaseapp.com
   i:/C=US/O=Google Trust Services/CN=GTS CA 1O1
 1 s:/C=US/O=Google Trust Services/CN=GTS CA 1O1
   i:/OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
subject=/C=US/ST=California/L=Mountain View/O=Google LLC/CN=firebaseapp.com
issuer=/C=US/O=Google Trust Services/CN=GTS CA 1O1
```
Certificate issued for firebaseapp.com and browser show error **Your connection is not private**

You can check certificate at https://www.digicert.com/help/

**Comment by xiaochunjimmy** [comment]
@kbakba @medatech @ianbradbury-bizzibody @marcelSchmidtC02 @Qualima 

Hi there,
Could you get access to https://remixicon.com and https://www.remixicon.com now?
How long does it take to finish loading？
We need your help to know whether our new service provider is viable for oversea users.

**Comment by kbakba** [comment]
Page loaded fine. But first attempt loading time is so big.
![image](https://user-images.githubusercontent.com/36834/82049854-c5392d00-96bf-11ea-857a-9f33589983db.png)
`/static/js/vendor.*.js` - 28 seconds for first load (2.8Mb), after loadi it cached, and load time for second load is fine.

**Comment by xiaochunjimmy** [comment]
@kbakba Thank you for your info. It seems just fine. What is your location?

**Comment by kbakba** [comment]
> What is your location?

St. Petersburg Russia
