### ISSUE TITLE
Document protected

### ISSUE THREAD

**Issue by davilla20** [Remix-Design/RemixIcon#18]
## Icon Request

* Icon name: Document protected
* Tags of this icon: file-protected, document-protected, document-secured
* Use case: 
* Screenshots of similar icons:
![Icon_24-512](https://user-images.githubusercontent.com/6358916/56340378-6d797b00-61ba-11e9-92aa-a4184840a0ee.png)

**Comment by xiaochunjimmy** [comment]
We've updated our icons. Looking for `document protected` icons with the name of `file-shield` on our website  [`Document`](https://remixicon.com/#document) category.
