### ISSUE TITLE
是否有计划提供物联网和健康方面的icon

### ISSUE THREAD

**Issue by WuJiY** [Remix-Design/RemixIcon#180]
## Icon Request

* Icon name: health and IOT icons
* Tags of this icon:  health\IOT

**Comment by xiaochunjimmy** [comment]
可以的话，能提供一些物联网的图标示例吗，物联网这个范围太大了，我们需要一些具体的需求信息来优先设计

**Comment by WuJiY** [comment]
阿里云提供是这样的 https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=12507
