### ISSUE TITLE
Icon Request：若干图标

### ISSUE THREAD

**Issue by Alecyrus** [Remix-Design/RemixIcon#181]
## Icon Request：若干图标
<img width="297" alt="截屏2020-05-03 13 48 26" src="https://user-images.githubusercontent.com/13865581/80903190-e5263380-8d44-11ea-9d85-b6239d6f4504.png">

### Heading
一二三级标题，3个图标

### 表格相关
上/下/左/右 插入一 行/列，4个图标
删除本行/列，2个图标
合并/拆分单元格，2个图标

### 图片相关
圆角/阴影/缩放尺寸/图片编辑， 4个图标

我们开发的应用是 https://www.v2ex.com/t/668166
全部图标来自你们的图标库，真的太赞了，感谢。

我们会在应用中注明使用了你们的图标库。以后有能力会捐助支持的。

**Comment by xiaochunjimmy** [comment]
1. 编辑器看起来非常漂亮，很有使用的欲望；
2. 捐助其实不太必要；
3. 我会尽量添加一些图标，但一般版本更新时间都比较长，或者也可以某种方式定向合作（非利益），优先支持而不等整体图标版本升级

**Comment by Alecyrus** [comment]
非常感谢🙏，如果对于编辑器有什么需求，可以提给我哦～～小刺上线后，会给 Remix Design 的小伙伴赠送高级订阅会员（RemixIcon 图标库真的对我们帮助很大）。 通过，也希望通过小刺，可以完善和丰富 RemixIcon 图标库。

关于定向合作，如果方便的话，我们同样也希望可以在小刺的 UX 方面得到小伙伴的一些专业意见🍺🍺🍺。

**Comment by xiaochunjimmy** [comment]
哈哈好的感谢，您是小刺的设计师吧？
其实对于小刺目前也还不是非常了解，后面使用的时候如果有想法可以给到您。

**Comment by xiaochunjimmy** [comment]
最近较忙，目前完成了以下图标：
delete-column.svg
delete-row.svg
h-1.svg
h-2.svg
h-3.svg
h-4.svg
h-5.svg
h-6.svg
insert-column-left.svg
insert-column-right.svg
insert-row-bottom.svg
insert-row-top.svg
merge-cells-horizontal.svg
merge-cells-vertical.svg
split-cells-horizontal.svg
split-cells-vertical.svg

下载地址：
[icons.zip](https://github.com/Remix-Design/RemixIcon/files/4606118/icons.zip)
