### ISSUE TITLE
linux penguin

### ISSUE THREAD

**Issue by ElliottStokes** [Remix-Design/RemixIcon#183]
## Icon Request

* Icon name: Linux
* Tags of this icon: Linux
* Use case: Used to display nodes in a graph database which are Linux servers
* Screenshots of similar icons: ![linuxPenguin](https://user-images.githubusercontent.com/35205384/80986636-bed9c400-8e28-11ea-8b63-8c1ba4f89c85.PNG)

**Comment by xiaochunjimmy** [comment]
This icon contains too many details. I'm not sure if it can be redesigned in the RemixIcon style.
If you just need a Linux vector icon, [Simple Icons](https://simpleicons.org/) is a better choice.

**Comment by ElliottStokes** [comment]
Thanks Jimmy!
