### ISSUE TITLE
remixicon.com's HTTPS certificate is not valid anymore

### ISSUE THREAD

**Issue by vivgui** [Remix-Design/RemixIcon#186]
**Describe the bug**
The HTTPS certificate of remixicon.com is not valid anymore (probably expired).

On Firefox:
![image](https://user-images.githubusercontent.com/7389358/81831609-8d898400-950b-11ea-98e0-e5b5e3eede18.png)

On Chrome:
![image](https://user-images.githubusercontent.com/7389358/81831721-b1e56080-950b-11ea-867d-0d20c87a9bb3.png)

**To Reproduce**
1. Open https://remixicon.com on Firefox or Chrome

**Device (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser Version:
Chrome 81.0.4044.138 (64-bit)
Firefox 76.0.1 (64-bit)
 - Website Version: 2.4.1

**Comment by xiaochunjimmy** [comment]
Thank you, how about https://www.remixicon.com ?

**Comment by vivgui** [comment]
It looks like it redirects to https://remixicon.com, so no HTTPS still.

**Comment by xiaochunjimmy** [comment]
I see.
Firebase Hosting has provisioned an SSL certificate to www.remixicon.com, while remixicon.com not.
I changed the redirect rule. Now remixicon.com will be redirected to www.remixicon.com for now.
Please try again and see if it works.
We'll solve this problem asap.

**Comment by xiaochunjimmy** [comment]
I see.
Firebase Hosting has provisioned an SSL certificate to www.remixicon.com, while remixicon.com not (show in the console).
I've changed the redirect rule. 
www.remixicon.com will not be redirected to remixicon.com for now.
Please try again and see if it works.
Maybe we can only wait before Firebase provisions SSL to remixicon.com.

**Comment by vivgui** [comment]
Checked on my desktop and phone on multiple browsers, `www` still redirects to remixicon.com, and remixicon.com still doesn't have a valid certificate.

Let's give it time to propagate and I'll check again tomorrow.

**Comment by imfunniee** [comment]
it's up now

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/81939159-8b691780-9628-11ea-8d7a-820daafd9b1d.png)

**Comment by xiaochunjimmy** [comment]
We are still trying to use a new global hosting service to solve this problem, so you may come across accessing problems for hours.
We hope it will be solved asap.

**Comment by YunYouJun** [comment]
The contents of the website in my impression are all static content.
Just a suggestion, why not consider using GitHub Pages as an alternate hosting site?

**Comment by xiaochunjimmy** [comment]
Information update:
We were using Upyun as our CDN service all the time, and it works fine in the past days until about weeks ago: many oversea uses reported that they could not access our website.
This problem happened in certain countries. We tried to connect Upyun but no useful info and solution returned.
Then we introduced Firebase as our hosting provider for foreign users, but we faced SSL problems when using Upyun and Firebase at the same time for both Chinese users and oversea users. Besides we have to maintain 2 hosting sever and deployments.
So we tried to use Vercel, which could provide hosting&CDN service for both Chinese and other users. But it may need hours(less than 72 hours) to tack effect.

**Comment by xiaochunjimmy** [comment]
Chinese users can visit our website with https://remixicon.cn/
and
Other users can visit our website with https://remixicon.web.app/
temporary.

**Comment by xiaochunjimmy** [comment]
@YunYouJun People say Github page has problems with Baidu SEO, is that true?

**Comment by YunYouJun** [comment]
@xiaochunjimmy Yeah, that's right. Instead, domestic CDN（Tencent Cloud Or Upyun Or Aliyun）can solve this problem.

**Comment by vivgui** [comment]
@xiaochunjimmy its true, I can't access remixicon.com now:

![image](https://user-images.githubusercontent.com/7389358/81949534-f686ff80-95d0-11ea-8c27-762b29200bda.png)

And can confirm, https://remixicon.web.app works ok.

**Comment by xiaochunjimmy** [comment]
@vivgui @YunYouJun @imfunniee 

Hi, could you help us to test the speed when loading our website? 
How long does it take to finish loading？

**Comment by YunYouJun** [comment]
China:
![image](https://user-images.githubusercontent.com/25154432/82028440-3846a180-96c8-11ea-9ea2-56a55e9bb702.png)
VPN(Foreign):
![image](https://user-images.githubusercontent.com/25154432/82028503-4e546200-96c8-11ea-94d8-55586aafddcd.png)

**Comment by vivgui** [comment]
I see the SSL is valid again. 

Here's the speed:

![image](https://user-images.githubusercontent.com/7389358/82063015-f3efdd00-9698-11ea-9018-20d8f7b46913.png)

It's very very slow. I'm on a 200mb internet, in the Dominican Republic.

**Comment by xiaochunjimmy** [comment]
@vivgui what is your location?

**Comment by vivgui** [comment]
Santo Domingo, Dominican Republic.

**Comment by xiaochunjimmy** [comment]
@vivgui It seems that our service provider did not deploy a CDN node around.
However, it should be faster than the first time you loaded our website. 
Besides, you can still use https://remixicon.web.app/

**Comment by vivgui** [comment]
ok sounds good 👍

**Comment by YunYouJun** [comment]
@xiaochunjimmy 
Maybe you can set [remixicon.cn](https://remixicon.cn) for China, and [remixicon.com](https://remixicon.com) for other countries.

> remixicon.com can be deployed on GitHub Pages/Netlify/Firebase, remixicon.cn can be deployed on some domestic cloud service provider for SEO.
> Script can solve the problem of simultaneous deployment.

Example: [elemefe](https://github.com/elemefe) use <https://element.eleme.cn> for China and <https://element.eleme.io/> for other countries.

**Comment by xiaochunjimmy** [comment]
@YunYouJun 坦白说，我们对于分发部署、负载均衡以及判定规则跳转等其实不是非常熟悉，从访问体验上来说，针对不同的国度使用更合理的内容分发部署确实更合适，现阶段从整体上来说，还是希望可以尽可能维护一份部署内容，这样在管理和维护上后期遇到的问题可能会少一点点，不过我们也在积极尝试更好的解决方案。
> 目标是更快、更便宜，考虑到目前几乎没有收入还得额外付出硬件和带宽成本，而且时间精力确实有限，我和小伙伴都是业余时间在维护，随着用户量的上涨，费用已经越来越高了。

后面我们再继续调研一下这方面的东西，如果您这边有更好的提供商解决方案，也欢迎推荐给我们。
好在现在访问问题解决了，而且单页应用加载一次之后不需要再加载就可以正常使用。

> 我怀疑之前的问题可能和美国大选之类的有关，许多VPN貌似这段时间也突然不好使了，咱们每次国庆节的时候也会出现各种问题。

**Comment by YunYouJun** [comment]
关于成本问题，现在 GitHub 除了 GitHub Pages 服务，也提供了 GitHub Actions。完全可以在 GitHub 上完成官网的持续集成部署。GitHub Pages 本身对于国外用户，就有良好的 CDN 和访问速度。足以应对大部分情况。此外为了以防万一，可以再套一层 Cloudflare，既能防止攻击，也可以直接免费使用 Cloudflare 的 CDN。

> 我的想法是可以考虑将 remixicon.com 的域名放置于 Cloudflare，remixicon.com 面向全球其他用户即可。（整个过程无需硬件、带宽成本。）
> 目前许多知名开源项目的文档或官网都是直接采用 GitHub Pages 托管，譬如 three.js, webpack, Rollup.js 等。

其次为了 remixicon 在国内（比如百度）的 SEO 和访问速度，可以将 remixicon.cn 专门面向国内用户。（毕竟 cn 本来就是国别域名）部署在腾讯云、阿里云、又拍云之类的云服务商。
腾讯云一般每个月有 10G 的免费额度，对于现在的 remixicon 可能不一定够用。
但也因此，以 remixicon 现在的使用量和影响力，完全可以考虑联系一些云服务商（又拍云可能比较容易），获取 CDN 赞助支持，相对只需要在官网挂上赞助商 LOGO 即可。

> 成本问题基本都可以解决。

---

如果不介意将官网置于 GitHub 上维护的话，我很乐意参与这一维护，如编写 GitHub Actions 的自动部署脚本等工作。
> 国内 CDN 设置源站为 remixicon.com 即可，这样也不用同时维护两处的部署。

**Comment by xiaochunjimmy** [comment]
@YunYouJun 非常非常感谢，很详细，这部分我们先做一下调研研究一下。
