### ISSUE TITLE
Folder protected

### ISSUE THREAD

**Issue by davilla20** [Remix-Design/RemixIcon#19]
## Icon Request

* Icon name: Folder protected
* Tags of this icon: folder-protected, directory-protected, folder-secured
* Use case: 
* Screenshots of similar icons:
![folder-protected-outline-icon-450w-1021501303](https://user-images.githubusercontent.com/6358916/56340591-07412800-61bb-11e9-99a9-fd5c0d22f471.jpg)

**Comment by xiaochunjimmy** [comment]
Hi, my friend, 
We've finished the design of `Folder protected` with the name of `folder-shield`.
You can get them in the [`Document`](https://remixicon.com/#document) category of our website or GitHub.
