### ISSUE TITLE
in safari the website con't download png icon

### ISSUE THREAD

**Issue by EnObj** [Remix-Design/RemixIcon#191]
**Describe the bug**
when I want to download some beautiful icons on your website in safari browser I only can download SVG and cover to png by myself, but if I choose windows the problem is not exists.

**To Reproduce**
1. open https://remixicon.com on safari
2. Choose some beautiful icons to icon folder
3. open the folder and click download PNG button, it do nothing, I open console there are nothing error.

**Expected behavior**
I hope the website can download icon png to my local on safari, it will be cool.

**Screenshots**

**Device (please complete the following information):**
 - OS:macOS 10.15.4
 - Browser& amp;Version: 13.1 (15609.1.20.111.8)
 - Website Version: 2.4.1

**Additional context**
SORRY my English is not good🙈

**Comment by wendygaoyuan** [comment]
Thank you. I'll fix this in the next version
