### ISSUE TITLE
Icon request： 粘贴板

### ISSUE THREAD

**Issue by Auxxxxlx** [Remix-Design/RemixIcon#193]
## Icon Request
粘贴板
* Icon name:  clipboard
* Tags of this icon: clipboard
* Use case: 
* Screenshots of similar icons:
<img width="507" alt="截屏2020-05-25 03 10 51" src="https://user-images.githubusercontent.com/13865581/82762751-5aad8d00-9e35-11ea-958e-b4fbd0068d4b.png">

**Comment by xiaochunjimmy** [comment]
这个是有的，在 Document 分类下搜索 clipboard 就可以， 没问题的话，您可以关闭这个 issue
