### ISSUE TITLE
Support for Tailwind CSS

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#194]
On the website we can get the icons as inline SVG files with a color of our choice.

When using [Tailwind](https://tailwindcss.com/) we can set colors by the div container like below.

```html
<div class="bg-red-500">
  <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M21 20a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9.49a1 1 0 0 1 .386-.79l8-6.222a1 1 0 0 1 1.228 0l8 6.222a1 1 0 0 1 .386.79V20zm-2-1V9.978l-7-5.444-7 5.444V19h14z"/></svg>
</div>
```

Notice the class `fill-current` that is added to the SVG. That class makes it possible for the SVG to be styled from the parent div container.

https://tailwindcss.com/docs/fill/

## RemixIcon + Tailwind CSS = true?

So to support Tailwind CSS you can add a checkbox "Support Tailwind CSS".
If checked, add the `fill-current` class for Tailwind CSS support.

**Comment by xiaochunjimmy** [comment]
Hey Jens,
Long time no see, I hope everything is going well for you.

Wendy resolved this issue yesterday, you can give it a try now.

If there are any other problems, please let us know.

**Comment by jenstornell** [comment]
@xiaochunjimmy

Hello! Everything fine from here. Hope you are doing well. I've tested it and it seems to work perfectly. I'll close this issue.

https://play.tailwindcss.com/FzBXkh2Z1N
