### ISSUE TITLE
in ' remixicon.web.app ' The list of icons in this address has not been updated to the new version .

### ISSUE THREAD

**Issue by paladio** [Remix-Design/RemixIcon#195]
The list of icons in [this address](https://remixicon.web.app/) has not been updated to the new version. Only this address is available in my country, please update the list of icons.

[remixicon.web.app](https://remixicon.web.app/)

**Comment by xiaochunjimmy** [comment]
So...
remixicon.com is still not accessible for you?

**Comment by Qualima** [comment]
No, the ' remixicon.com ' URL is not available to me.
Only occasionally does the site open with 10 refreshments.
