### ISSUE TITLE
Site not showing real icon names

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#198]
On the site it looks like below. It gives the names of the icons, but not the full names.

## Case 1

There are two icons called "home" but one is lined and the other is filled. When clicking on them we can see their real names "home-line" and "home-fill".

![image](https://user-images.githubusercontent.com/927011/83235062-9330cc00-a191-11ea-9e10-7561c352b761.png)

## Case 2

Here is another scenario. The icons below looks exactly the same and they have the same name. Still, the html for them are not the same.

```html
<i class="ri-close-line"></i>
<i class="ri-close-fill"></i>
```

![image](https://user-images.githubusercontent.com/927011/83235393-194d1280-a192-11ea-8ea7-e27c54f52a08.png)

## Possible solutions

I'm not sure which way is the best solution but here are a few suggestions.

1. Write the full names on the page.
1. With a very small text below each icon, write `line` or `fill` which then is like the type for them.

**Comment by xiaochunjimmy** [comment]
Emmm...
Yes, maybe it’s not easy for new users to tell which is `fill` and which is `line`. 
Old users some times may also get confused when the two icon looks the same.
Your suggestion is a simple and effective way. I'll think about this problem and try to find if there's another way to solve this problem.
