### ISSUE TITLE
Student, Teacher, School, Academia

### ISSUE THREAD

**Issue by Golotvinov** [Remix-Design/RemixIcon#199]
## Icon Request

* Icon name: Student
* Tags of this icon: student
* Use case: school and academia
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/39648288/83292584-a328ca00-a1ea-11ea-8c2f-73dd958e7d40.png)

It would be awesome if you add a **School / Academia section** with different icons.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/graduation-cap-fill
https://remixicon.com/icon/graduation-cap-line
