### ISSUE TITLE
Remixicon in a real project

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/remixicon#2]
I've been looking for a free icon pack a very long time that matches my requirements and finally I've found it.

**My requirements was**

- Free for commercial use
- Common icons in the pack
- "+file" and "+folder" icons. In other packages there was "+file" OR "+folder", never both.

As a little thank you, I'll give you a screenshot of my unfinished project, so you can see how the icons can be used. It's soon a markdown editor for PHP.

![image](https://user-images.githubusercontent.com/927011/52550656-41680500-2dd9-11e9-9e53-ce22d6ce9f2b.png)

The icons looks great for most part. The filetree is using 18px icons so in that case it gets a bit blurry (especially the text file icon). That however is not your fault, because you are using a 24px grid which makes the topbar in my case look awesome.

At the moment I can't make a donation (hopefully in the future), but I will gladly put a link to your icons in my readme.

Thanks!

**Comment by xiaochunjimmy** [comment]
1. First of all, thank you very much (from my heart) for using our icons in your project and taking time to provide feedback.

2. As you know, Remix Icon is a side project of us. Wendy and I spare time to maintain it. We can't provide multi-size icons (such as 18px, 20px) for now which takes a lot of time.

3. Feel free to use it, a donation is not required, it's only a way to show your love. We are very grateful to your star in GitHub.

4. You are the first one who opens issues in Github. To express my gratitude, I have redesigned folder icon and file icon with an 18px grid for your usage, they may look better~
![markdown](http://cdn.remixicon.com/markdown.svg)
![folder](http://cdn.remixicon.com/folder.svg)
![folder-open](http://cdn.remixicon.com/folder-open.svg)
![file-text](http://cdn.remixicon.com/file-text.svg)

5.Little advice: 
(1) It'll be more clear to show the state of folder by adding a "+ -" or a little arrow in front of your folder icon.
(2) Better not use #000000 color of icons and fonts, too much strong contrast.

**Comment by jenstornell** [comment]
2. I completely understand that. You can't do an icon pack for every pixel size. 24px is however a very good size to work with.

4. Fantastic! I'm very grateful! And yes, it looks awesome!

I will also need 18px of an image, refresh, plus, minus icons, but to not take your time, I can probably create them myself, I think,

*I also took your advice of making the icons less black, just like yours with #333. Plus minus signs not yet implemented*

**I've recommended Remixicon to be included into [Kirby CMS - Kosmos](https://getkirby.com/kosmos). Not sure how it goes, but it would be a nice addition. You deserve 2000 stars, not 63.**

![image](https://user-images.githubusercontent.com/927011/52574460-a6911a00-2e1c-11e9-8757-a0e155da31b2.png)

**Comment by xiaochunjimmy** [comment]
Thanks again~
Here's the image and refresh icon~
![](http://cdn.remixicon.com/image.svg)
![](http://cdn.remixicon.com/refresh.svg)
Plus and minus icon are easy to create with div+css,  
and you can also build it with SVG XML, it will be an interesting experience by drawing an icon with code, I think.

**Comment by jenstornell** [comment]
You are too kind! Thanks!

Yes, there are even pure css icon packs out there, like this one: https://saeedalipoor.github.io/icono/

If you want I can let you know when my project is released.

**Comment by xiaochunjimmy** [comment]
I'd like to know when your project is released.

Some icons in your free-icon-packs repo can give us inspirations to helps us improve our product, thanks~

By the way, the icon version on GitHub is newer than that on our website.
such as social and brands icons: https://github.com/Remix-Design/remixicon/tree/master/icons/Logos

**Comment by jenstornell** [comment]
My Markdown editor project has not yet been released, it needs more testing. However it's built apon my own filetree library, which is released and now also uses your 18px version of Remixcon.

https://github.com/jenstornell/staircase.js#libraries-used

![previewer](https://user-images.githubusercontent.com/927011/52961482-532e4700-339b-11e9-9762-8e5acd92ed8b.gif)

**Comment by xiaochunjimmy** [comment]
Good work~ Keep！

**Comment by jenstornell** [comment]
One piece of the puzzle of my (still unreleased) Markdown editor, is a login screen. I created a new repo of that to keep it separated.

https://github.com/jenstornell/wall

Once again your icons really shines! 👍 

![image](https://user-images.githubusercontent.com/927011/53947505-292c9280-40c6-11e9-8e57-78c40772b4c6.png)

**Comment by jenstornell** [comment]
Finally it has been released. I have used it a while myself to write content, but my guess is that I need more documentation.

https://github.com/jenstornell/cursor

![image](https://user-images.githubusercontent.com/927011/55156634-c2494900-515a-11e9-8859-9d2425ff44aa.png)

**Comment by xiaochunjimmy** [comment]
Nice work man~
I think it will be better if there was a live preview demo website for visitors.
