### ISSUE TITLE
Key Icon

### ISSUE THREAD

**Issue by dotintechno** [Remix-Design/RemixIcon#20]
## Icon Request

* Icon name: key
* Tags of this icon: key
* Use case: Lock key
* Screenshots of similar icons: 
![Screenshot 2019-04-24 at 4 52 07 PM](https://user-images.githubusercontent.com/34878080/56655823-7a620700-66b1-11e9-82d3-c3faabb27d30.png)
![Screenshot 2019-04-24 at 4 51 43 PM](https://user-images.githubusercontent.com/34878080/56655870-91a0f480-66b1-11e9-8ffc-31343944a43e.png)

**Comment by xiaochunjimmy** [comment]
Hi Dotintechno, 
We've finished the design of `Key Icons`.
You can get `Key icons` from the [Life](https://github.com/Remix-Design/RemixIcon/tree/master/icons/Life) folder on GitHub or our [website](https://remixicon.com/#life).
They are also available in fonts files.
