### ISSUE TITLE
Icon Req: Graduation Hat

### ISSUE THREAD

**Issue by elitepixels** [Remix-Design/RemixIcon#200]
## Icon Request

* Icon name: Graduation Hat
* Tags of this icon: graduation, university, college, student, degree, hat
* Use case: for schools and in UI
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/64798457/83321281-22121700-a26c-11ea-80da-bd89ffe1c0a5.png)

![image](https://user-images.githubusercontent.com/64798457/83321288-2d654280-a26c-11ea-8078-422ea5c47b24.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/graduation-cap-fill
https://remixicon.com/icon/graduation-cap-line
