### ISSUE TITLE
Github link on homepage

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#21]
When using a site like yours I often look for the Github icon, to go to the repo. In some cases it's fixed at the top right, in other cases it's part of the menu. In your case it's kind of hidden.

It's possible to go to the repo by clicking "Usage" or "Request" but for someone that does not know, it does not indicate that these links goes to Github.

My suggestion is to add a link with the github icon somewhere at the top of the homepage. As a bonus I think you will have even more stars that way.

**Comment by xiaochunjimmy** [comment]
Thank you so much for your advice~
A friend of mine has the same confusion about this.
I'll make the entrance of GitHub more clearly.

**Comment by xiaochunjimmy** [comment]
I'm glad to tell you we have updated our website and we added the GitHub link in the navigation bar.
