### ISSUE TITLE
Why do we need import whole remixIcon.css

### ISSUE THREAD

**Issue by FocusThen** [Remix-Design/RemixIcon#224]
![image](https://user-images.githubusercontent.com/47830409/86021944-60008780-ba32-11ea-9351-2a8258c67d90.png)

# solution
- need code split.
- i wanna do import { riHomeLine } from 'remixIcon'

**Comment by xiaochunjimmy** [comment]
If you just need one icon, why use `.css`? You could just use the `.svg` format.
You can also choose some icons and generate your own custom `fonts` files from our website, but the CDN service only provides a complete package.

When you use our products for free, I don’t expect your gratitude, but please don’t be mean
