### ISSUE TITLE
可以发布一版微信小程序可用的npm版图标吗？

### ISSUE THREAD

**Issue by deajax** [Remix-Design/RemixIcon#225]
可以发布一版微信小程序可用的npm版图标吗？可以用过小程序npm构建的，目前小程序拉下来以后构建时提示npm找不到入口文件

**Comment by XiKun-TW** [comment]
小程序直接用 base64 转码后就可以使用了。目前小程序自定义字体也只能用这种方式来做。

deajax <notifications@github.com>于2020年6月30日 周二08:17写道：
