### ISSUE TITLE
详情问引入的问题

### ISSUE THREAD

**Issue by 604119757** [Remix-Design/RemixIcon#228]
您好，请问font中的remixicon.glyph.json和remixicon.symbol.svg这两个文件也需要引入项目中吗

**Comment by xiaochunjimmy** [comment]
按需取用即可，remixicon.glyph.json不需要引入；remixicon.symbol.svg 是另一种不同于字体的使用方式，如果不需要的话也可以不引入的。

**Comment by 604119757** [comment]
好的 谢谢您
