### ISSUE TITLE
Add icon preview in release note

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#24]
Currently, you are only showing the list of icons names in the release note instead of that I would like to suggest to showcasing the icon name and preview or else you can also add a version filter with the search bar

**Comment by xiaochunjimmy** [comment]
Could you tell us why should this be valuable for users? I'd like to know how can I solve the problems that you and other users met. Such as why this feature is important for you, what problems that you want to solve.

**Comment by iamrishishah** [comment]
As of now, there is no option in the website where can I see all newly updated icons. So I use copy and paste command to see all new updates icons, and it takes a lot of efforts.

**Comment by xiaochunjimmy** [comment]
Hey man,  
we have updated our website and now you can preview icons and even download them just in the release note window. No more copy and paste.
</br>
Oh by the way, if you like Remix Icon, I hope you can Star our project to support us.  
There are a lot of good projects in GitHub and people often use `Star` to mark what they like.
