### ISSUE TITLE
Reply and forward icons

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#241]
## Icon Request

* Icon name: reply and forward 
* Tags of this icon: reply, left arrow, right arrow, forward
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/49694573/89706241-6cf18e80-d981-11ea-9733-a3f9a8a0ceca.png)

**Comment by xiaochunjimmy** [comment]
The `reply` and `reply-all` icons have been added to our icons months ago. You can find them in the `Business` category.
The `forward` icon can be found in the `system` category.
Or just search `forward`.

**Comment by iamrishishah** [comment]
Yes. I know. But I need single stoke icons as per attachment because it produce much clear appearance on screen.

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/corner-up-left-double-line
