### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by lanyusan** [Remix-Design/RemixIcon#248]
Are you going to keep the server up? I still plan to use your icons but if the server is going down I have to give up.

But still huge thanks to maintainer and contributors anyway.

Good luck with your new endeavors.

**Comment by xiaochunjimmy** [comment]
Thank you for your remind. I was trying to solve this problem.


| |
章萧醇
|
|
woaichidapi@163.com
|
签名由网易邮箱大师定制


On 08/24/2020 09:40，lanyusan<notifications@github.com> wrote：

Are you still going to keep the server up? I still plan to use your icons but if the server is going down I have to give up.

But still huge thanks to maintainer and contributors anyway.

Good luck with your new endeavors.
