### ISSUE TITLE
Reserved icon

### ISSUE THREAD

**Issue by papenx** [Remix-Design/RemixIcon#26]
## Icon Request

* Icon name: Reserved
* Tags of this icon: Reserve, reserved
* Use case: Food and restaurants
* Screenshots of similar icons: https://www.flaticon.com/free-icon/food-and-restaurant_1717051#term=reserve&page=1&position=13

**Comment by xiaochunjimmy** [comment]
[This](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Life/reserved-fill.svg) is the reserved icon with filled style.  
[This](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Life/reserved-line.svg) is the reserved icon with outlined style.
