### ISSUE TITLE
Adding "help" tag to `questionnaire` icon

### ISSUE THREAD

**Issue by locness3** [Remix-Design/RemixIcon#27]
Would be great to have a "help" tag for the `questionnaire` icon.

**Comment by xiaochunjimmy** [comment]
Thank you so much for your advice and we'll add the "help" tag for the questionnaire icon the next version.  
I'd close this issue after the updating of our website.

**Comment by xiaochunjimmy** [comment]
I'm glad to tell you we have updated our icons and tags.  
Now you can find the `questionnaire` icon with the keywords of `help`
