### ISSUE TITLE
Remix Icon Website is Down -  Require Immediate Attention

### ISSUE THREAD

**Issue by philson-philip** [Remix-Design/RemixIcon#274]
When I tried to go to https://remixicon.com/, It is returning error. Website is not loading. Require Immediate Attention!

**Comment by xiaochunjimmy** [comment]
Is the website available now? I can visit it on my side.

**Comment by philson-philip** [comment]
@xiaochunjimmy I think it is blocked on my network. When I tried using VPN, It is working. Thanks.
