### ISSUE TITLE
Icon request: Mastodon

### ISSUE THREAD

**Issue by kogakure** [Remix-Design/RemixIcon#28]
## Icon Request

* Icon name: Mastodon
* Tags of this icon: logo, microblogging, social media
* Use case: Icon for microblogging service Mastodon
* Screenshots of similar icons: https://en.wikipedia.org/wiki/Mastodon_(software)#/media/File:Mastodon_Logotype_(Simple).svg

**Comment by xiaochunjimmy** [comment]
Thank you for your icon suggestion.
I'm sorry we have finished the next version(v1.2.1) of the icon package which will be released in a few days. So you may wait for more weeks till we update it.

**Comment by xiaochunjimmy** [comment]
You can find the Mastodon icon [here](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/mastodon-fill.svg) now.
You can also search for it on our website [remixicon.com](https://remixicon.com)
