### ISSUE TITLE
Education/Graduation Cap

### ISSUE THREAD

**Issue by ajaygorecha** [Remix-Design/RemixIcon#280]
## Icon Request

* Icon name: Education/Graduation Cap
* Tags of this icon: cap
* Use case: 
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/32031612/103136433-7425f880-46e6-11eb-8c02-af3a1d9603a8.png)
![image](https://user-images.githubusercontent.com/32031612/103136441-830cab00-46e6-11eb-9cca-ce58e49045d3.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/graduation-cap-line
https://remixicon.com/icon/graduation-cap-fill
