### ISSUE TITLE
tiktok icon

### ISSUE THREAD

**Issue by hyedyhyedy** [Remix-Design/RemixIcon#284]
## Icon Request

* Icon name: tiktok
* Tags of this icon: 
* Use case: for social icons
* Screenshots of similar icons:
<img width="1086" alt="Screenshot 2021-01-15 at 10 51 47" src="https://user-images.githubusercontent.com/36624358/104709871-b22f9e80-571f-11eb-8043-758d6b11b2f4.png">

**Comment by williamwilkinson** [comment]
Came here to request as well!

**Comment by IamINFJ** [comment]
it's 2022 already...

**Comment by xiaochunjimmy** [comment]
Here's the Tiktok icons
https://remixicon.com/icon/tiktok-line
https://remixicon.com/icon/tiktok-fill
