### ISSUE TITLE
Bug report: icon `zhihu-line` is bolder than `zhihu-fill`

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#29]
**Describe the bug**
The `zhihu-line` icon is bolder than `zhihu-fill` icon.

**To Reproduce**
1. Go to <https://remixicon.com/>
2. Search `zhihu`
3. See error...

**Expected behavior**
`zhihu-line` icon is thinner than `zhihu-fill` icon.

**Screenshots**
![深度截图_选择区域_20190519232103](https://user-images.githubusercontent.com/25154432/57984411-25d26180-7a8e-11e9-9d0c-ac82642c6a2b.png)

**Device (please complete the following information):**
 - OS: [Deepin 15.10]
 - Browser Version [Chrome 73.0.3683.86(64-bit)]
 - Website Version [1.5.0]

**Additional context**
Thanks for your beautiful icons.
If my opinion is wrong, please tell me why.

**Comment by xiaochunjimmy** [comment]
感谢朋友的反馈~
不过...这个知乎的logo在顺序上确实没错...对于logo这一个分类，填充风格（第二排）采用的是logo的原始图标（或者经过屏幕像素解析度调整过的原始图标）按照24px网格调整大小后的图标；而line风格（第一排）则是按照remix icon规范重绘的风格化图标，比较明显的特征是2px的线条粗细（也有个别跳脱2px粗细的，不如line的logo）；
对于知乎的logo，在缩放到24px大小之后，其线条粗细已经小于2px了；而按照remix icon风格重绘的知乎图标，看起来反而比原始的粗...

**Comment by YunYouJun** [comment]
明白了，感谢您详细的解释。
