### ISSUE TITLE
Icon request: hashtag

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#30]
## Icon Request

* Icon name: hashtag
* Tags of this icon: tag, hash
* Use case: before header or tag
* Screenshots of similar icons:  ![image](https://user-images.githubusercontent.com/25154432/57984556-7dbd9800-7a8f-11e9-85b4-0e58600c0c32.png)

**Comment by xiaochunjimmy** [comment]
收到~会在后续版本更新。
不过，v1.2.1版本的图标内容已经封版了，在后续几天会发布（目前还有一些bug没处理完）。所以 # 图标会更新在v1.2.2版本中。一般一个版本的发布时间大概在2-3周。

**Comment by jenstornell** [comment]
@xiaochunjimmy It's your repo and your rules, but I think it would be easier if we could keep it to english?

For me, the above says:

>...v.1.2.1...v1.2.2...2-3

**Comment by YunYouJun** [comment]
@jenstornell Yeah, you are right.
But what the words above are not important. He just wanted to tell me that he would do it in next releases.
And he found we are both from China, so maybe he thought it would be more convenient for me.

**Comment by xiaochunjimmy** [comment]
@jenstornell Hahaha, thanks for your reminder. Sorry for Non-Chinese friends.

**Comment by xiaochunjimmy** [comment]
Sorry for a long time waiting.
You can find it on our website [remixicon.com](https://remixicon.com) now.
感谢云游君的长期支持 😊
