### ISSUE TITLE
Cube icon

### ISSUE THREAD

**Issue by liviuang** [Remix-Design/RemixIcon#302]
## Cube Icon Request

* Icon name:  cube
* Tags of this icon: cube 
* Use case: very useful for packages, registries, development, etc.
* Screenshots of similar icons: 
![package-line](https://user-images.githubusercontent.com/295398/112121999-82da5980-8bc8-11eb-9d4a-608f0f0a9bed.png)

**Comment by xiaochunjimmy** [comment]
Same with https://github.com/Remix-Design/RemixIcon/issues/314

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/box-1-line
https://www.remixicon.com/icon/box-2-line
https://www.remixicon.com/icon/box-3-line
