### ISSUE TITLE
Icon request: douban

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#31]
## Icon Request

* Icon name: douban
* Tags of this icon: logo, book, film
* Use case: Icon for [douban](https://www.douban.com/)
* Screenshots of similar icons: ![image](https://user-images.githubusercontent.com/25154432/57998044-3c1a0500-7b02-11e9-91c0-f1826a487ff0.png)

**Comment by xiaochunjimmy** [comment]
豆瓣图标在此  [RemixIcon → Logos](https://remixicon.com/#logos)
