### ISSUE TITLE
The website code will be open source?

### ISSUE THREAD

**Issue by GallenHu** [Remix-Design/RemixIcon#312]
**Is your feature request about our website? Please describe.**

请问网站主页的代码有开源计划吗？因为一直期望有开源替代产品能实现 iconfont.cn 的主要功能。发现 gh-pages 分支仅包含生产环境代码...

**Comment by xiaochunjimmy** [comment]
抱歉，RemixIcon 网站部分暂时还没有开源计划，开源的仅仅是图标内容这一部分。
Pages 部分是构建完成的静态页面。
