### ISSUE TITLE
Icon request: netease cloud music

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#32]
## Icon Request

* Icon name: netease cloud music
* Tags of this icon: netease, cloud, music
* Use case: icon for [网易云音乐](https://music.163.com/)
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/25154432/57998121-a29f2300-7b02-11e9-8125-77122116621d.png)

**Comment by xiaochunjimmy** [comment]
这次同样增加了两款网页云音乐图标，一款是原始图标，一款是线性图标。
唯一美中不足的一点是，在网上找尽了资源也没找到官方提供的矢量版本，所以现在你看到的是我通过官方的位图转曲后手动绘制调整的版本。可能在某些极小的细节上会有一点点不同（非强迫症不影响）。
