### ISSUE TITLE
Skip arrow

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#323]
## Icon Request

* Icon name: skip
* Tags of this icon: skip, arrow, forward
* Use case: Skip to last or navigate on last section or page
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/49694573/120778300-ceec3780-c543-11eb-84e3-51f022fbd987.png)
![image](https://user-images.githubusercontent.com/49694573/120778336-d90e3600-c543-11eb-80f9-a716789b26b1.png)

**Comment by xiaochunjimmy** [comment]
May be this is the icon you needed. https://www.remixicon.com/icon/arrow-right-double-line
find more related icons in the Arrows category
