### ISSUE TITLE
Is remixicon on iconfont?

### ISSUE THREAD

**Issue by YunYouJun** [Remix-Design/RemixIcon#33]
您好，我在搜索图标的时候在 [iconfont](https://www.iconfont.cn/user/detail?spm=a313x.7781069.0.d214f71f6&uid=43754) 上发现了 remixicon 。
请问发布者是官方人员吗？会和官方库保持同步吗？

<https://www.iconfont.cn/user/detail?spm=a313x.7781069.0.d214f71f6&uid=43754>

> 如果是的话，我就可以直接在 iconfont 上引用了 :yum:

**Comment by xiaochunjimmy** [comment]
您好，非常感谢您的提醒。  
1. iconfont上的remixicon图标库并不是由官方人员上传的，可能是某个爱好者的个人行为，所以后续的更新情况不太清楚。  
2. 从iconfont下载的图标会比从官网下载的图标体积略大一些，iconfont平台对图标做了代码格式的格式化，增加了一小部分代码。  
3. 如果您觉得在iconfont上使用更加方便，可以暂时使用该用户的库，或者也可以提出您的改进建议，我们会在后期的迭代中让官网的易用性更强。
4. 后期可能会考虑上架到iconfont。（之前之所以一直没上架，其中一方面原因是目前更新维护的内容较多，很多内容不太容易脚本自动化，升级一次需要不少工作量。）如果我们上架到iconfont平台，会在这里通知您~
5. 有注意到该用户在iconfont平台开通了打赏功能，而remixicon是一款开源产品，如果该用户利用remixicon收取打赏收益，可能涉及到对开源协议的违反以及对remixicon的侵权（具体还需要再对协议规则研究一下）。

**Comment by YunYouJun** [comment]
- 希望能在 iconfont 上使用的主要原因是 iconfont 提供了图标项目和收藏功能。
- 官网提供了三种使用方案。
  - 我起初使用了 font 方案，图标会比同行字体略向上偏移，fontawesome 则保持在一行。可以自定义 css 样式解决。 不过因为引入 web font，对所有图标都进行了引入，所以比较影响速度。
  - 我尝试使用了 svg 方案，发现 svg 是所有的字体图标合并在一起的一个 svg。同样文件较大，比较影响速度。
  - 所以最后我仅对需要的 svg 进行了下载，通过 img 引入，但这种方式无法通过 css 自定义颜色。(网上也有一些方案，但都比较 hack，需要冗余代码，不够优雅。)只能修改 svg 图片本身 fill 属性。
  - iconfont 提供了仅将项目内收藏图片生成为 cdn js (也可以通过 svg 可通过 css 定义颜色)来引入，保证了速度和引入的便利。
- 期待 iconfont 的上架 :yum:

**Comment by xiaochunjimmy** [comment]
了解了，在自定义方面，目前iconfont提供的服务和功能确实更加丰富且便利，阿里的设计师和工程师也是利用业余时间维护了一个了不起的产品。时间精力允许的话，或许晚些会随着下一个版本一起上线到iconfont。  
再次感谢您对remixicon的支持~

**Comment by xiaochunjimmy** [comment]
朋友，说一下进展，实际上自从 v1.5.2 版本更新之后我就尝试过提交 RemixIcon 到 Iconfont，但是由于之前已经有用户上传过图标，官方以图标重复性太高为由拒绝了我的上传申请。我在他们的反馈渠道提交了 [issue](https://github.com/thx/iconfont-plus/issues/1292)，但可能已经很久没有人去管理了，至今没有收到答复。

**Comment by YunYouJun** [comment]
看了一下官方仓库的 Issue, 的确感觉好多没有处理。
不过我去 Iconfont 搜索了下，已经发现了 remix 官方的图标。
您看这个是不是？[Remix Icon | Iconfont](https://www.iconfont.cn/user/detail?spm=a313x.7781069.1998910419.dcc7d6115&userViewType=collections&uid=4031400)
最新日期是 2019-05-29，也许是刚通过？

---

以及我发现在官网最底端有相关说明。
> ©ALIMAMA MUX, powered by alimama THX.法律声明
转载内容版权归作者及来源网站所有，本站原创内容转载请注明来源，商业媒体及纸媒请先联系：zy99945@alibaba-inc.com

如果没有反馈的话，您要不尝试联系邮箱试试？

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/58555667-9d517f00-824c-11e9-971a-0c6bc00da94c.png)

我在所有图标库的首页推荐第一页上也发现了 Remix Icon。

**Comment by xiaochunjimmy** [comment]
这个链接确实是我们，不过我们包含15个分类的图标库，但审核通过的只有7个（我之前以为都没有通过），如果是这样的话，似乎库中有更新图标就可以审核通过，下次我在没有审核通过的库中各新增一点图标吧...

**Comment by xiaochunjimmy** [comment]
这个issue我就先关掉了。图标也借由 1.3.0 版本重新上传了。希望这次官方可以通过全部图标库
