### ISSUE TITLE
Puzzle/Plug-In/Extension Icon

### ISSUE THREAD

**Issue by a9dezign** [Remix-Design/RemixIcon#336]
## Icon Request

* Icon name: Puzzle
* Tags of this icon: Plugin, Puzzle, Extension, Add-on, Integration
* Use case: For App Plugin or Extension Icon
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/44572398/124801782-2587cf80-df4f-11eb-9c16-3f35da3b6855.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/puzzle-line

https://remixicon.com/icon/puzzle-2-line
