### ISSUE TITLE
Logos of games

### ISSUE THREAD

**Issue by stevenpersia** [Remix-Design/RemixIcon#34]
### Icons name: 
- Overwatch
- League of Legends
- Counter Strike : Global Offensive
- Unreal tournament
- Quake
- Rocket League
- Starcraft 2
- DOTA 2
- Super smash bros. ultimate

* Use case: Develop a platform of gaming.

**Comment by xiaochunjimmy** [comment]
I'm not sure some of the game logos can be translated to icons...  
Em... em...

**Comment by stevenpersia** [comment]
I understand. You can find some icons of game logos in icons8.com. Maybe it can help you create one.

https://icons8.com/icon/set/unreal/ios
https://icons8.com/icon/set/overwatch/ios
https://icons8.com/icon/set/league-of-legends/ios
https://icons8.com/icon/set/dota-2/ios

**Comment by xiaochunjimmy** [comment]
OK, I can try some game logos.   
The problem is Remix Icons are based on a 24*24px grid, so there are only a few pixels can be used, while the game logos contain many details.

**Comment by stevenpersia** [comment]
You are awesome ! Even if you can't do it, it's really cool of you to try.

**Comment by jenstornell** [comment]
Maybe it's just me, but I feel like this is not the right repo for game icons. All the other icons are for making web applications, more or less.

Game icons may be a good idea, I just think that it's the wrong place for it.

**Comment by itsezc** [comment]
I agree @jenstornell there are millions of games and even if you picked the top few they might involve some very complicated shapes for a very small audience, however I would add probably the following

- Unreal (https://cdn.worldvectorlogo.com/logos/unreal-1.svg)
- Unity (https://images.techhive.com/images/article/2015/03/unity-logo-100571261-large.jpg)

If any game related icons were to be added
