### ISSUE TITLE
Icon Request: Money Bill

### ISSUE THREAD

**Issue by justinfar** [Remix-Design/RemixIcon#347]
## Icon Request

* Icon name: Money Bill
* Tags of this icon: cash, money, bill
* Use case: Haven't found any suitable replacement in the current version of the library for representing a money bill
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/26432097/132110199-e961d796-fe96-4fd4-b3bc-e2c29858dfec.png)
![image](https://user-images.githubusercontent.com/26432097/132110205-6ef6604b-be3b-488b-beaa-01a5c71b2152.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/cash-line
