### ISSUE TITLE
Collection of Linux distributions

### ISSUE THREAD

**Issue by b0ngo** [Remix-Design/RemixIcon#35]
## Icon Request
There are a bunch of icons for different operating systems or their related companies like Android, Apple (iOS & MacOS), Windows (for any Windows version). Unfortunately, there is neither the Linux penguin nor are there any logos for major Linux distributions like Ubuntu, RHEL, CentOS, Gentoo, Arch, Debian, Linux Mint, openSUSE, Manjaro, Fedora. BSD logos are also missing.

It would be great if some of them are included in the next releases.

* Icon name: tux
* Tags of this icon: tux, penguin, linux, os
* Use case: Web site with comparison of different operating systems.
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/27992092/58111436-f8e29380-7be0-11e9-9eb6-a554429eeb21.png)

**Comment by xiaochunjimmy** [comment]
Thank you for your adveice~  
I'm not sure I can design all of the Linux systems icons, some of the logos are not easy to design into icons. but I'll try some of them.  
Maybe you can get some of them in the next version.

**Comment by jenstornell** [comment]
Like any kind of company icons, I don't think you should work too much on them. They are already icons created by these authors. Why redo their work?

I think it's better to create icons for web development, not games, not companies and not OS distrubutions. In general, not logos of any kind. But that's what I think.

I think social media icons is a good exception of my "rule" above.

**Comment by xiaochunjimmy** [comment]
Sorry I only designed 2 icons of Linux for now:
Ubuntu and CoreOs.
You can get more logo icons in the [Simple Icons](https://simpleicons.org/)
