### ISSUE TITLE
Sand clock

### ISSUE THREAD

**Issue by nagatarun90** [Remix-Design/RemixIcon#350]
## Icon Request

* Icon name: Sand clock
* Tags of this icon: clock, loading, timer 
* Use case: Status pending
* Screenshots of similar icons:
* 
![download](https://user-images.githubusercontent.com/39808326/132541063-78b896f3-baf2-462c-b07c-8870869b5d36.png)

**Comment by xiaochunjimmy** [comment]
Hope you'll like these icons:

https://www.remixicon.com/icon/hourglass-2-line
https://www.remixicon.com/icon/hourglass-2-fill

https://www.remixicon.com/icon/hourglass-line
https://www.remixicon.com/icon/hourglass-fill
