### ISSUE TITLE
Attempted import error: 'RiTranslate2' is not exported from 'react-icons/ri'

### ISSUE THREAD

**Issue by xreider** [Remix-Design/RemixIcon#352]
`import { RiTranslate2 } from 'react-icons/ri'`

Attempted import error: 'RiTranslate2' is not exported from 'react-icons/ri'

https://codesandbox.io/s/polished-rgb-2gdsq?file=/src/index.js

**Comment by wendygaoyuan** [comment]
Because RemixIcon in react-icons is incomplete, it has only 2172(https://github.com/react-icons/react-icons/releases/tag/v4.2.0)
Without ri-translate-2
![截屏2021-09-15 下午11 54 32](https://user-images.githubusercontent.com/25056241/133467207-0604c8e5-bb21-41af-a7aa-147900c043ad.png)
