### ISSUE TITLE
Icon request: Sun

### ISSUE THREAD

**Issue by kogakure** [Remix-Design/RemixIcon#36]
## Icon Request

* Icon name: Sun
* Tags of this icon: sun, light
* Use case: Would be a useful companion for the moon icon. Could be used to switch between dark/light mode on a website.
* Screenshots of similar icons: -

**Comment by xiaochunjimmy** [comment]
Yes, this icon is useful

**Comment by xiaochunjimmy** [comment]
You can get the `sun` icons in the `Weather` categories now. I also moved the `moon` icon from the `System` category to the `Weather` category.
