### ISSUE TITLE
Icon request - Remix framework

### ISSUE THREAD

**Issue by GuptaSiddhant** [Remix-Design/RemixIcon#363]
## Icon Request

* Icon name: remix-run
* Tags of this icon: remix, react, framework, web
* Use case: Showcasing apps created using Remix framework
* Screenshots of similar icons: https://avatars.githubusercontent.com/u/64235328?s=200&v=4

![Remix run](https://avatars.githubusercontent.com/u/64235328?s=200&v=4)

**Comment by xiaochunjimmy** [comment]
Remix Icons style:
https://remixicon.com/icon/remix-run-line

Original style:
https://remixicon.com/icon/remix-run-fill
