### ISSUE TITLE
Icon Request: Blogger

### ISSUE THREAD

**Issue by falasyam** [Remix-Design/RemixIcon#365]
## Icon Request

* Icon name: Blogger
* Tags of this icon: blogger
* Use case: blogger blogspot
* Screenshots of similar icons: https://www.blogger.com/img/logo_blogger_40px.png

**Comment by xiaochunjimmy** [comment]
Remix Icons style:
https://remixicon.com/icon/blogger-line

Original style:
https://remixicon.com/icon/blogger-fill
