### ISSUE TITLE
Icon request: Kakao Talk

### ISSUE THREAD

**Issue by w4-jamie** [Remix-Design/RemixIcon#37]
* Icon name: Kakao Talk
* Tags of this icon: logos
* Use case: Kakao Talk is South Korea's top messenger app with approximately 50 million monthly active users worldwide. 
* Screenshots of similar icons: https://play.google.com/store/apps/details?id=com.kakao.talk

**Comment by xiaochunjimmy** [comment]
Here are the logos of Kakao Talk:
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/kakao-talk-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/kakao-talk-line.svg
