### ISSUE TITLE
Arrow bar left Icon

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#371]
## Icon Request

* Icon name: Arrow bar left, right, top and bottom icon
* Tags of this icon: Arrow
* Use case: Icon to use to hide side menus and bars like Twitch
* Screenshots of similar icons: 
![image 2](https://user-images.githubusercontent.com/38047906/145895403-b08288b2-d036-4d8f-a0a8-c047ad7cd0c3.png)
![image 1](https://user-images.githubusercontent.com/38047906/145895208-42794f65-83a4-4e8c-a7fb-37875973d2a6.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/expand-left-line
https://www.remixicon.com/icon/expand-left-fill
