### ISSUE TITLE
Icon Request: fill color

### ISSUE THREAD

**Issue by percy507** [Remix-Design/RemixIcon#374]
## Icon Request

* Icon name: fill-color
* Tags of this icon: Editor
* Use case: Editor
* Screenshots of similar icons:  https://www.flaticon.com/premium-icon/fill_3894581?term=fill%20color&page=1&position=2&page=1&position=2&related_id=3894581&origin=search

![image](https://user-images.githubusercontent.com/18365078/147383310-0069514f-4f93-4df5-9582-d0c41493ec58.png)

**Comment by xiaochunjimmy** [comment]
@percy507 

Is those the icons you are looking for?

https://remixicon.com/icon/paint-fill
