### ISSUE TITLE
Icon request: Medium fill

### ISSUE THREAD

**Issue by Ngoakor12** [Remix-Design/RemixIcon#376]
## Icon Request: Medium
Medium have recently(2020) updated their icon and it would be nice to have the updated ones instead of the old icons. [Full update article](https://medium.com/blogging-guide/mediums-new-logo-2020-unfinished-ellipses-logomark-e24c059871e7)

* Icon name: medium-fill
* Tags of this icon: Logos
* Use case: Link to your medium account icon
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/54069197/148173408-5dbdd931-8d59-4e2a-9ad6-175bbe2d6527.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/medium-fill

**Comment by Ngoakor12** [comment]
I may have forgotten what I wanted to use this for, but thank you for eventually getting to it😅

**Comment by xiaochunjimmy** [comment]
Sorry it took so long to add this icon.
