### ISSUE TITLE
Icon request: Medium line

### ISSUE THREAD

**Issue by Ngoakor12** [Remix-Design/RemixIcon#377]
## Icon Request: Medium
Medium have recently(2020) updated their icon and it would be nice to have the updated ones instead of the old icons. [Full update article](https://medium.com/blogging-guide/mediums-new-logo-2020-unfinished-ellipses-logomark-e24c059871e7)

* Icon name: medium-line
* Tags of this icon: Logos
* Use case: Link to your medium account icon
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/54069197/148173930-81edc6d7-2e10-4429-bb41-36bc521b3827.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/medium-line
