### ISSUE TITLE
Cocktail

### ISSUE THREAD

**Issue by l0uisgrange** [Remix-Design/RemixIcon#378]
## Icon Request

* Icon name: cocktail
* Tags of this icon: cocktail, drink, beverage, alcohol
* Use case: Drink distribution, alcohol
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
Can those icons meet your needs?

cocktail, alcohol
https://remixicon.com/icon/goblet-fill
https://remixicon.com/icon/beer-fill

drink
https://remixicon.com/icon/drinks-2-line
