### ISSUE TITLE
Icon Request: Double Arrow (Left and Right)

### ISSUE THREAD

**Issue by barryels** [Remix-Design/RemixIcon#389]
## Icon Request

![arrow-double-left-s-line](https://user-images.githubusercontent.com/872849/152349338-ff06d287-3442-453d-892b-dff0f5711f0c.svg)
![arrow-double-right-s-line](https://user-images.githubusercontent.com/872849/152349342-0f4c041b-adb2-4eed-87c5-c76824c4265a.svg)

* Icon name: Double Arrow (Left and Right)
* Tags of this icon: arrow, (left or right), (backward or forward)
* Use case: For pagination to denote the buttons that would take you to the first page or the last page
* Screenshots of similar icons:

![pagination_tech-considerations](https://user-images.githubusercontent.com/872849/152349634-bc5f74b5-ec00-4dda-8a48-8cef1748eff1.png)

<img width="364" alt="Screenshot 2022-02-03 at 13 14 58" src="https://user-images.githubusercontent.com/872849/152349840-8e4d0770-f2ef-4c83-8d99-ea880528ff68.png">

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/arrow-left-double-line
https://www.remixicon.com/icon/arrow-right-double-line
