### ISSUE TITLE
Discount/Sale Icon

### ISSUE THREAD

**Issue by jannikbuscha** [Remix-Design/RemixIcon#397]
## Icon Request

* Icon name: `discount`
* Tags of this icon: `discount` `sale` `cheap`
* Use case: For adding it to a badge on a shopping-item
![image](https://user-images.githubusercontent.com/74017697/159171826-969794b9-a8dd-4360-907c-7a9d0c28eaf0.png)

* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/74017697/159171792-012ebffe-f583-4311-aac5-7b4657cd703c.png)
![image](https://user-images.githubusercontent.com/74017697/159171794-03e18199-0a9b-4650-80f0-e33f2793e671.png)

(not just a percent sign)

**Comment by xiaochunjimmy** [comment]
Maybe those icons could match your needs:

https://remixicon.com/icon/discount-percent-fill

https://remixicon.com/icon/price-tag-fill

https://remixicon.com/icon/price-tag-3-fill
