### ISSUE TITLE
Loader icon missing?

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#4]
## Icon Request

* Icon name: loader or spinner
* Tags of this icon: loader,spinner,ajax,waiting,delay
* Use case: For ajax requests
* Screenshots of similar icons: https://github.com/feathericons/feather/blob/master/icons/loader.svg

**Comment by jenstornell** [comment]
I just remember that I use the `refresh` icon in my tree, so I can use that icon in other parts of my app as well. What I missed was that both these icons server the same purpose, even if they look very different. I close this one again.

**Comment by jenstornell** [comment]
I still miss the "standard" ajax loading icon. I'll reopen this issue so you can have a look at it.

**Comment by xiaochunjimmy** [comment]
Got it, I've added it in my design plan.

Thank you for your contribution to helping us improve the tags.json,
In return, you can get the single loader icon [here](http://cdn.remixcdn.com/icon/loader.svg) if you are eager to use it.

Please do not close this issue till we published loader icons in the next version.

**Comment by xiaochunjimmy** [comment]
We updated our icon library and added 5 loader icons for you. Enjoy it
