### ISSUE TITLE
Video on/off (both)

### ISSUE THREAD

**Issue by patriciasacocbx** [Remix-Design/RemixIcon#401]
## Icon Request

I have already created both icons to use meanwhile, so I'm sharing them with you: https://drive.google.com/drive/folders/1HfHuhU_upGPKwd_cA4RcY0YazAvL7TCF?usp=sharing

* Icon name: video-line
* Tags of this icon: video, on, cam, camera, line
* Use case: video is on during a videocall
* Screenshots of similar icons: https://drive.google.com/file/d/1aqvQFXZQoGkZdAuCXwqWHp7B9-uskUmd/view?usp=sharing
---
* Icon name: video-off-line
* Tags of this icon: video, off, cam, camera, line
* Use case: video is off during a videocall
* Screenshots of similar icons: https://drive.google.com/file/d/1ouM1-JIEWfIlX_NTI6wyhqsJ5HbT7R9X/view?usp=sharing

**Comment by xiaochunjimmy** [comment]
Your design is excellent, and we will add it in the next version.
There are too many issues in history, and we are gradually addressing them.
