### ISSUE TITLE
Multiple folders

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#41]
## Icon Request

* Icon name: Multiple folders
* Tags of this icon: all folders, multiple folders
* Use case: Multiple folders inside a folder, all folders filter icon
* Screenshots of similar icons: http://prntscr.com/nt5zfa , https://www.flaticon.com/free-icon/folder_148963#term=folders&page=1&position=32

**Comment by xiaochunjimmy** [comment]
Thank you for your advice. 
If you can Star our project to support us we will be very thankful.

**Comment by iamrishishah** [comment]
Sure, why not.
As a designer I also would like to contribute in this project because you save our time. I really appreciate your efforts.

**Comment by xiaochunjimmy** [comment]
Thank you very much!
If you want to work with us to improve this icon library, you can try a few icons referring to the completed icons as a specification or styling guide. 
We will check the icons you designed according to the standard and decide whether to include it.
But I am sorry that we still have no written design style-guide.

**Comment by iamrishishah** [comment]
I think you should do that first. 

Because many of designer like me would like to help and contribute in this project and even you can also drop suggested icon list on the website so designers can easy to find and participate or join in this project. 

Good to have: You can also send some free [goodies](https://github.com/Remix-Design/RemixIcon/issues/44) to that designer who follow the style-guide and deliver well crafted icons

**Comment by xiaochunjimmy** [comment]
I see...
I would take some time to make a style-guild of RemixIcon for designers.
Thank you again for your advice.

**Comment by xiaochunjimmy** [comment]
Here are the folders icons:
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folders-line.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folders-fill.svg
You can also get them on our website.
And the icon style guide has been on my plan.
