### ISSUE TITLE
Shared and received folder

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#42]
## Icon Request

* Icon name: shared folder
* Tags of this icon: shared folder
* Use case: Folder has been shared with team members
* Screenshots of similar icons: A folder with right arrow

* Icon name: received folder
* Tags of this icon: received folder
* Use case: Folder has been received by a team members
* Screenshots of similar icons: A folder with left arrow

**Comment by xiaochunjimmy** [comment]
[folder-shared-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-shared-line.svg)
[folder-shared-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-shared-fill.svg)
[folder-received-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-received-line.svg)
[folder-received-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Document/folder-received-fill.svg)
