### ISSUE TITLE
Discord Icon is out of date

### ISSUE THREAD

**Issue by TomHelyer** [Remix-Design/RemixIcon#432]
**Describe the bug**
The discord icons are still the old discord icon

**Expected behaviour**
change the discord icon to the new one: https://discord.com/branding

**Comment by xiaochunjimmy** [comment]
Sorry for the late reply, we have updated the icon of Discord to the latest version.

https://remixicon.com/icon/discord-line
https://remixicon.com/icon/discord-fill
