### ISSUE TITLE
Add fill=currentColor to svg's

### ISSUE THREAD

**Issue by floydnant** [Remix-Design/RemixIcon#433]
**Is your feature request about the Usage? Please describe.**
Currently when using the `svg` approach, and want to control the color of the icon with the CSS `color` property, you'd have to add `fill="currentColor"` to the paths in each svg icon manually.

**Describe the solution you'd like**
It would be very convenient, if the svgs would already provide that. Like so:
```html
<svg ... >
    <path fill="currentColor" d="..." />
</svg>
```

**Comment by lqmanh** [comment]
+1, I'd love to see this get implemented too

**Comment by xiaochunjimmy** [comment]
Hi, @floydnant and @lqmanh, we've added `fill="currentColor"` to the latest version v4.0.0 icons. Please try it out and let us know if any problems.
