### ISSUE TITLE
School icon

### ISSUE THREAD

**Issue by Curogrammer** [Remix-Design/RemixIcon#437]
## Icon Request

* Icon name: School
* Tags of this icon: school, college, university
* Use case: For selecting school
* Screenshots of similar icons: https://icon-icons.com/icon/school/112596

**Comment by xiaochunjimmy** [comment]
Here's the icons
https://www.remixicon.com/icon/school-line
https://www.remixicon.com/icon/school-fill

Similar Icons
https://www.remixicon.com/icon/graduation-cap-line
https://www.remixicon.com/icon/graduation-cap-fill
