### ISSUE TITLE
home office icon

### ISSUE THREAD

**Issue by KRHelmholtzMunich** [Remix-Design/RemixIcon#438]
## Icon Request

* Icon name: Home Office
* Tags of this icon: home office, work from home, mobile work
* Use case: business, employee benefit
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/112101812/186699279-b8f468ee-f1e9-48b0-b164-e3434e064d85.png)
![image](https://user-images.githubusercontent.com/112101812/186699762-da1f4f52-832a-4d7b-a906-659d45e426d1.png)
![image](https://user-images.githubusercontent.com/112101812/186699874-ec05cbb5-bc0c-4003-a0ab-0941da795e42.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/home-office-line
