### ISSUE TITLE
Teaching icon

### ISSUE THREAD

**Issue by KRHelmholtzMunich** [Remix-Design/RemixIcon#439]
## Icon Request

* Icon name: Teaching
* Tags of this icon: teach, training, learning
* Use case: school, education, university, employee benefit, employee training
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/112101812/186700897-97407761-866f-4200-971a-9fe76aca4c72.png)
![image](https://user-images.githubusercontent.com/112101812/186701170-466027da-bbe9-425b-9ec1-ab1c735ffdd8.png)
![image](https://user-images.githubusercontent.com/112101812/186701237-4bc01fac-9d8e-4e81-8b88-db1f3b86dcd9.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/presentation-fill
https://www.remixicon.com/icon/presentation-line
