### ISSUE TITLE
Overline Icon

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [Remix-Design/RemixIcon#449]
## Icon Request

* Icon name: overline
* Tags of this icon: ri-overline 
* Use case: Text editor (rotating underline is not a workaround)
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/6233059/189377835-75579f3d-4e5a-4584-a0e6-1a13b1f33ca8.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/overline
