### ISSUE TITLE
Icon request: WeChat MiniProgram (微信小程序)

### ISSUE THREAD

**Issue by mingyoung** [Remix-Design/RemixIcon#45]
## Icon Request

* Icon name: WeChat MiniProgram (微信小程序)
* Tags of this icon: wechat, mini-program, mini-app
* Use case: Admin management system
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/6228858/58377497-c952d300-7fb4-11e9-9971-87c143f503e5.png)
![image](https://user-images.githubusercontent.com/6228858/58377500-d2dc3b00-7fb4-11e9-9196-21c40784d319.png)

**Comment by xiaochunjimmy** [comment]
Good suggestion

**Comment by xiaochunjimmy** [comment]
The original icons ：[mini-program-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/mini-program-fill.svg)
The remix-icon style icon：[mini-program-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/mini-program-line.svg)
You can also find them on our [website](https://remixicon.com) under the `logos` category.
