### ISSUE TITLE
remixicon.com down?

### ISSUE THREAD

**Issue by ChrisGudd** [Remix-Design/RemixIcon#450]
RemixIcon.com seems to be down :(

The requested URL '/' was not found on this server.
![down](https://user-images.githubusercontent.com/11297475/189399170-31cdc365-5326-477c-8aae-1074ad4d7988.png)

**Comment by Haojen** [comment]
I also get this error too

**Comment by chromodome** [comment]
Yep me too (2 hrs in after first comment)

**Comment by ChrisGudd** [comment]
Thankyfully it's in the wayback machine:
https://web.archive.org/web/20220908040303/http://www.remixicon.com/
![waybackmachine](https://user-images.githubusercontent.com/11297475/189417863-67c85b68-fb6c-499a-acfe-881623d9651f.png)

**Comment by ChrisGudd** [comment]
UPDATE: Its online again 👍

**Comment by xiaochunjimmy** [comment]
Thank you guys. Thanks for reminding. 
I've checked our sever, and I found the provider changed their pricing plan. Maybe there was a glitch along with that. Thankfully, it's OK now.
