### ISSUE TITLE
3x Pass icon

### ISSUE THREAD

**Issue by AntoinePoindron** [Remix-Design/RemixIcon#451]
Hi, I've made these 3 icons for my design system using remix icon :

- Pass valid
- Pass pending
- Pass expired

![pass-expired](https://user-images.githubusercontent.com/80094837/189930914-2e1bbda7-4224-4450-9f47-9cf1159840b5.svg)
![pass-pending](https://user-images.githubusercontent.com/80094837/189930917-04c92e75-faa2-4fc7-8cef-530191ebf681.svg)
![pass-valid](https://user-images.githubusercontent.com/80094837/189930921-0000774f-279b-4bec-baf0-094be86211fc.svg)

Hope it will be added to your library !

**Comment by joffreymougel** [comment]
Hi @AntoinePoindron and @xiaochunjimmy 

Thanks for this request, I like those and would like to use them too.
Do you have an idea when the icons can be added ? Could I make something to speed up the process ?

Have a nice day !!
Joffrey

**Comment by xiaochunjimmy** [comment]
Hi @AntoinePoindron ,

Thanks for the beautiful icons, we've added them to our library. Based on your design, I made a few sizing adjustments to make the icons look the same size.

Search `pass` on our website and you'll find them.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/6701827/230131740-35bea11d-c32a-419e-ab7a-5ce2a311e980.png">

cc @joffreymougel

**Comment by joffreymougel** [comment]
Many thanks @xiaochunjimmy !!

**Comment by AntoinePoindron** [comment]
Thanks, it will be so useful for us !


Le jeu. 6 avr. 2023 à 09:36, Joffrey Mougel ***@***.***> a
écrit :
