### ISSUE TITLE
Brain icon Request

### ISSUE THREAD

**Issue by grape4842** [Remix-Design/RemixIcon#452]
## Icon Request

* Icon name: Brain
* Tags of this icon: Brain, Health, Medical, Others, 
* Use case: 
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
Hi Grape,
Here are the Brain icons:

https://www.remixicon.com/icon/brain-line
https://www.remixicon.com/icon/brain-fill

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/6701827/229333752-4276c4c2-9ce0-4c37-a00d-7b57a29806dc.png">
