### ISSUE TITLE
CPU icon

### ISSUE THREAD

**Issue by jiu-virgil** [Remix-Design/RemixIcon#459]
## Icon Request

* Icon name: CPU
* Tags of this icon: circuit, electricity, cpu, micro
* Use case: A symbol for computational power, circuits or low level systems
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/68442514/196806850-9e6d3594-d071-4ccd-b7d5-d0afc724d1e6.png)

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/#icon-cpu-line

https://www.remixicon.com/#icon-cpu-fill
