### ISSUE TITLE
Https support for cdn

### ISSUE THREAD

**Issue by Carr0ter** [Remix-Design/RemixIcon#46]

**Comment by xiaochunjimmy** [comment]
感谢，CDN 现已支持 https 请求。使用 https 和 http 都可以获取资源，比如以下两个链接都可以访问：
https://cdn.remixicon.com/releases/v1.2.2/remixicon.css
http://cdn.remixicon.com/releases/v1.2.2/remixicon.css

---

Thank you there. Now you can use CDN service with an https request, such as:
https://cdn.remixicon.com/releases/v1.2.2/remixicon.css
