### ISSUE TITLE
public website offline (https://remixicon.com/)

### ISSUE THREAD

**Issue by benmkramer** [Remix-Design/RemixIcon#463]
**Describe the bug**
The remixicon site seems to be completely down.

**To Reproduce**
1. In browser try to open [https://remixicon.com/](https://remixicon.com/)
3. See site can't be reached error or similar

**Expected behavior**
Site loads and can browse and find great icons :D 

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2603478/198852162-ea39940b-e6d9-4866-aac6-561ea601eeeb.png">

**Device (please complete the following information):**
 - OS: Mac OS 13.0
 - Browser: `Chrome Version 106.0.5249.119 (Official Build) (arm64)` (also checked firefox, same issue)
 - Website Version: Unknown

**Additional context**
Also checked via `ping remixicon.com` (timeouts) and used a website to check if it was down which reported that it is.

Not urgent but in case it wasn't obvious to owners thought I'd drop an issue so you all know :)

**Comment by spuente** [comment]
Hi @benmkramer, I am encountering the same problem when trying to access https://remixicon.com/. However, when I try to access the site with `www` (https://www.remixicon.com/), it does work. This is most likely not a permanent solution, but I thought I'd share this workaround in case anyone else is encountering this issue and needs to access the site before it is properly fixed.

**Comment by benmkramer** [comment]
> Hi @benmkramer, I am encountering the same problem when trying to access https://remixicon.com/. However, when I try to access the site with `www` (https://www.remixicon.com/), it does work. This is most likely not a permanent solution, but I thought I'd share this workaround in case anyone else is encountering this issue and needs to access the site before it is properly fixed.

Nice, thanks for sharing! I was silly to not try that. I did try `http://` and `https://` though, not sure why I didn't think to add the www 🤦‍♂️

**Comment by wendygaoyuan** [comment]
Sorry, we recently modified our DNS servers and now the site （https://remixicon.com/ ） is fixed 🙇

**Comment by benmkramer** [comment]
Thank you, @wendygaoyuan!
