### ISSUE TITLE
Equal sign and its Variations

### ISSUE THREAD

**Issue by jobithmb** [Remix-Design/RemixIcon#467]
## Icon Request

* Icon name: Equals
* Tags of this icon: equal, sum, result
* Use case: math operations
* Screenshots of similar icons: https://www.flaticon.com/free-icon/equals-sign_1368

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/equal-line
https://www.remixicon.com/icon/equal-fill
