### ISSUE TITLE
Icon request: Hourglass

### ISSUE THREAD

**Issue by RatnadeepBiswakarma** [Remix-Design/RemixIcon#468]
Thanks for the awesome icons. Would it be possible to add an **hourglass** icon?

## Icon Request

* Icon name: hourglass
* Tags of this icon: hourglass, time, stock, duration
* Use case: 
* Screenshots of similar icons: https://icons.getbootstrap.com/icons/hourglass-split/

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/hourglass-2-line
https://www.remixicon.com/icon/hourglass-2-fill
https://www.remixicon.com/icon/hourglass-line
https://www.remixicon.com/icon/hourglass-fill
