### ISSUE TITLE
Size and fixed width

### ISSUE THREAD

**Issue by AndiLeni** [Remix-Design/RemixIcon#47]
I'd like to be able to change the icon size via a html class like in font awesome (``fa-2x, fa-lg``).
Also sometimes it is very usefull to have a fixed width for icons, for example to use them in lists. The class in fa would be ``fa-fw``

Is this already possible or do you plan to integrate these options in the future?

Regards
Andi

**Comment by xiaochunjimmy** [comment]
Thanks for your feedback Andi, we'll think about your suggestion.
It seems to be very convenient to resize icons. 
If we've integrated the class options, we'll get you known the first time.

**Comment by rendy44** [comment]
I've been digging the docs just to find is there any helper class to resize the icon. So far what I'm doing is create my own simple class with font-size attribute. (just in case someone else looking for this :) )

**Comment by xiaochunjimmy** [comment]
We have added sizing and fixed-width classes in the [`remixicon.css`](https://github.com/Remix-Design/RemixIcon/blob/master/fonts/remixicon.css) file. You can get the class information in the file contents.

**Comment by xiaochunjimmy** [comment]
I'll close this issue. If any problems, please feedback.
