### ISSUE TITLE
tiktok icon

### ISSUE THREAD

**Issue by pirius12** [Remix-Design/RemixIcon#470]
## Icon Request

* Icon name: tiktok
* Tags of this icon: tiktok
* Use case: titok
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/83941927/202528871-74d41719-257c-4732-b8c9-06905d3ded16.png)

**Comment by xiaochunjimmy** [comment]
Here's the Tiktok icons
https://remixicon.com/icon/tiktok-line
https://remixicon.com/icon/tiktok-fill
