### ISSUE TITLE
Auto fix / Auto Suggestion icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#476]
## Icon Request

* Icon name: star
* Tags of this icon: star , recommended, auto suggestions, auto fix
* Screenshots of similar icons:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/49694573/209772793-ced1ec1e-046d-46ad-a5ee-8a1fea5a0028.png">

**Comment by xiaochunjimmy** [comment]
Hi Rishi,

Long time no see. 

We've launched the 3.0.0 new version of RemixIcon, including some AI /Auto-Suggestion related icons.
Here's the icon list:

https://www.remixicon.com/icon/bard-fill
https://www.remixicon.com/icon/shining-fill
https://www.remixicon.com/icon/sparkling-fill
https://www.remixicon.com/icon/sparkling-2-fill
