### ISSUE TITLE
Media Icons (Playback Speed, Forward 10sec, Rewind 10sec

### ISSUE THREAD

**Issue by Maruti-Ram** [Remix-Design/RemixIcon#477]
### Icon Category: Media Icons

Icon name: Playback Speed
<img width="307" alt="image" src="https://user-images.githubusercontent.com/19895288/209869366-06520abd-7188-40a5-a9fd-9e0ca59d6973.png">

* Icon name: Forward 10sec
*  Icon name: Forward 30sec
*  Icon name: Rewind 10sec
*  Icon name: Rewind 30sec
---
* Tags of this icon: Media Icons
* Use case: Media Controls 
---
* Screenshots of similar icons:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/19895288/209869251-15cb3319-01d0-4af0-b219-0f75632727fc.png">

**Comment by xiaochunjimmy** [comment]
Hi, We've added many new icons in this version, including your suggestions.

You'll find them under the 「Media」category

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/6701827/229334133-7dc9b0c5-6152-468d-aee9-d0902c3aeab0.png">
