### ISSUE TITLE
Consider adding `font-display: swap`?

### ISSUE THREAD

**Issue by rendy44** [Remix-Design/RemixIcon#48]
Hi, will you consider adding a `lazy-load` option when loading font file using `font-display: swap`

Maybe something like `<i class="remixicon-account-box-fill remixicon-lazy"></i>` will make this options is optional,

The goal of this option is to reach a higher score in google speed insight which tells us that the icon is invisible during loading font file until it's loaded completely.

**Comment by xiaochunjimmy** [comment]
Sorry, this is the first time that I heard about this option helper since I am a designer, not a professional developer and we can not use google service in China.
Could you tell me which font-icon service use `font-display: swap`? I would like to spike it first and get more information about this option before we decide whether to add this option to RemixIcon in the future.

**Comment by YunYouJun** [comment]
`font-display: swap` in fonts mean load default font (like: `Microsoft YaHei`, `PingFang SC`) in browser if your web font is not yet loaded.
Once the font is loaded, switch to your custom web fonts.
> Without it, the page will be blank until the font is loaded.

I think this is what he want.
![image](https://user-images.githubusercontent.com/25154432/58557089-1f8f7280-8250-11e9-80bf-a29ab89186d3.png)![image](https://user-images.githubusercontent.com/25154432/58557049-02f33a80-8250-11e9-9697-efede4033238.png)

**Comment by xiaochunjimmy** [comment]
Oh, I see... Thank you for your explanation. @YunYouJun 

So, is this what you want? @rendy44 
```css
.remixicon-lazy {
    font-display: swap
}
```

**Comment by Uranbold** [comment]
@xiaochunjimmy You should add it on globally. Check the Google Font it has already added it. Google Page Speed report now always suggesting add the Font display property. The correct one is swap.

Thanks.
