### ISSUE TITLE
gtrr notion icon

### ISSUE THREAD

**Issue by n1203** [Remix-Design/RemixIcon#481]
## Icon Request

* Icon name: notion logo
* Tags of this icon: https://www.notion.so/
* Use case: <i className="ri-notion-fill"></i>
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
Here are Notion icons:

https://www.remixicon.com/icon/notion-line
https://www.remixicon.com/icon/notion-fill

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/6701827/229333911-6e931f7e-1d72-4108-9942-e3f77d2830c8.png">

**Comment by xiaochunjimmy** [comment]
@Niko030303 

Sorry, could you please explain in detail? I don't quite understand the meaning of `not responsive`.

**Comment by Niko030303** [comment]
> @Niko030303
> 
> Sorry, could you please explain in detail? I don't quite understand the meaning of `not responsive`.

when I want to use this icon as `<i class="ri-notion-line"></i>` , it can't be rendered on the page
