### ISSUE TITLE
Graduation Cap

### ISSUE THREAD

**Issue by Sang-Buster** [Remix-Design/RemixIcon#482]
## Icon Request

* Icon name: graduation-cap
* Tags of this icon: Design or User & Faces
* Use case: Use as a link to google scholar, research gate, etc,.
* Screenshots of similar icons:
![Grad-cap-ex](https://image.shutterstock.com/image-vector/graduation-hat-cap-line-art-260nw-256935676.jpg)

**Comment by xiaochunjimmy** [comment]
Check these icons:
https://remixicon.com/icon/graduation-cap-line
https://remixicon.com/icon/graduation-cap-fill
