### ISSUE TITLE
新增图标建议 [茶，饮料，咖啡，汉堡]

### ISSUE THREAD

**Issue by stars-one** [Remix-Design/RemixIcon#489]
不知道作者老哥何时回归，先提个issue

tea
coffee
hamburger
drink

## Icon Request

* Icon name: 
* Tags of this icon: 
* Use case: 
* Screenshots of similar icons:

**Comment by stars-one** [comment]
参考 字节官方图标 http://iconpark.oceanengine.com/official

**Comment by xiaochunjimmy** [comment]
收到，food 类型的图标

**Comment by xiaochunjimmy** [comment]
目前已经有了单独的 Food 分类，后续也会陆续添加食品图标，如果你设计工作过程中遇到了需要的，可以单独再提 Issue，当前问题先关闭掉
