### ISSUE TITLE
Tiktok icon

### ISSUE THREAD

**Issue by alckordev** [Remix-Design/RemixIcon#491]
* Icon name: tiktok-line
* Tags of this icon: logo
* Use case:  Use as a link
* Screenshots of similar icons:
![tik-tok-flat-icon-template-black-color-editable-tik-tok-flat-icon-symbol-flat-illustration-for-graphic-and-web-design-free-vector](https://user-images.githubusercontent.com/16854024/218950601-dbecad4a-bb70-4589-9949-6b0d1416af0f.jpg)

**Comment by RanaUbaidullah** [comment]
I also want

**Comment by marine-maiden** [comment]
I second this

**Comment by xiaochunjimmy** [comment]
Here's the Tiktok icons
https://remixicon.com/icon/tiktok-line
https://remixicon.com/icon/tiktok-fill

**Comment by alckordev** [comment]
> Here's the Tiktok icons https://remixicon.com/icon/tiktok-line https://remixicon.com/icon/tiktok-fill

Thanks

**Comment by RanaUbaidullah** [comment]
Take this
https://remixicon.com/icon/tiktok-line
