### ISSUE TITLE
js, bootstrap icon 

### ISSUE THREAD

**Issue by Bunyodbek1505** [Remix-Design/RemixIcon#493]
js, bootstrap icon give icons similar to this

**Comment by xiaochunjimmy** [comment]
Do you mean RemixIcon for Javascript and bootstrap components? 
or JS and bootstrap logo?

**Comment by xiaochunjimmy** [comment]
https://www.remixicon.com/icon/javascript-fill
https://www.remixicon.com/icon/bootstrap-fill
