### ISSUE TITLE
希望在system能增加带圆圈的正确，check，close图标。

### ISSUE THREAD

**Issue by IvanID** [Remix-Design/RemixIcon#495]
## Icon Request

* Icon name: check-circle
* Tags of this icon: check, success 
* Use case: 
* Screenshots of similar icons: 

* Icon name: close-circle
* Tags of this icon: close, error
* Use case: 
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
同学是指这两组图标吗？或者是否可以提供类似的截图以便我快速定位需求
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/6701827/223326444-ce5c4f03-8aa1-4da7-ae92-58f7ebbdc5ad.png">

**Comment by IvanID** [comment]
对的！我当时怎么没找到。谢谢你！



IVAN&nbsp;DESIGN
***@***.***







                       
原始邮件
                       
                     

发件人："章萧醇"< ***@***.*** &gt;;

发件时间：2023/3/7 13:12

收件人："Remix-Design/RemixIcon"< ***@***.*** &gt;;

抄送人："IvanID"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [Remix-Design/RemixIcon] 希望在system能增加带圆圈的正确，check，close图标。 (Issue #495)




 
同学是指这两组图标吗？或者是否可以提供类似的截图以便我快速定位需求
