### ISSUE TITLE
Font family icon

### ISSUE THREAD

**Issue by periode** [Remix-Design/RemixIcon#499]
Hello!

Thanks for the nice work. I'm using all these icons for [my academic work](https://source.enframed.net) :)

## Icon Request

* Icon name: Font-family
* Tags of this icon: Font-family, serif, sans-serif
* Use case: to allow users to choose between preset font families in an app
* Screenshots of similar icons:
![](https://www.w3schools.com/css/serif.gif)

One icon could be enough, but I can imagine having one icon for **serif**, **sans-serif** and **mono** would be helpful as well!

**Comment by xiaochunjimmy** [comment]
@periode Thanks for the suggestion. Now you can get those icons in version v3.2.0. I also added some other related Icons:

https://remixicon.com/icon/font-family
https://remixicon.com/icon/font-sans-serif
https://remixicon.com/icon/font-sans
https://remixicon.com/icon/font-mono
