### ISSUE TITLE
check-double-line

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/remixicon#5]
## Icon Request

* **Icon name:** check-double-line
* **Tags of this icon:** check,double
* **Use case:** In my case, I would like it in a pricing table to make the last items in the list really stand out, compared to the check icon.
* **Screenshots of similar icons:** https://thenounproject.com/term/double-check/1003313/

You already have a nice check-icon. So if you make this icon, make sure that looks similar to that one:

https://github.com/Remix-Design/remixicon/blob/master/icons/System/check-line.svg

**Comment by jenstornell** [comment]
I fixed it myself. If you want it, here it is.

```text
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g>
    <path d="M7 15.2l9.2-9.2 1.4 1.4 -10.6 10.6 -6.4-6.4 1.4-1.4 5 5Z"/>
    <path d="M13 15.2l9.2-9.2 1.4 1.4 -10.6 10.6 -6.4-6.4 1.4-1.4 5 5Z"/>
  </g>
</svg>
```

**Comment by xiaochunjimmy** [comment]
Wow~ lol~
I will take your advice, and I will add this icon to subsequent versions.
