### ISSUE TITLE
Database icon

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#50]
## Icon Request

* Icon name: database
* Tags of this icon: database, db
* Use case: A more "standard" looking database icon.
* Screenshots of similar icons: https://cdn3.iconfinder.com/data/icons/programming/100/database_4-512.png

**Comment by xiaochunjimmy** [comment]
Em... yes, as you wish my friend. 
Maybe the database icon we've already designed is not very clear and standard.

**Comment by itsezc** [comment]
The current database icon really isn't clear, something similar to the one proposed on the screen shot would be great!

**Comment by xiaochunjimmy** [comment]
My friend, the new database icon's name is `database-2`, you can find them quickly by searching it on our [website](https://remixicon.com). I hope you'll like this one.
