### ISSUE TITLE
Chevron-Icons

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#501]
## Icon Request

* Icon name: chevrons-icons
* Tags of this icon: Media
* Use case: To use in paginations components to advance to the last page for example
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/38047906/227929082-61e6346c-87e2-40b8-ab79-0039b4d80b8e.png)

**Comment by xiaochunjimmy** [comment]
Check our new website and you'll find your icons at the first category - **Arrows**.
https://remixicon.com/
