### ISSUE TITLE
Tailwind CSS logo request

### ISSUE THREAD

**Issue by silham** [Remix-Design/RemixIcon#502]
## Icon Request

* Icon name: Tailwind CSS logo
* Tags of this icon: logo
* Use case: web development 
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/79428366/228220241-778cfb14-ffd5-4fa9-b66c-4a1205ea15c9.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/tailwind-css-line
https://remixicon.com/icon/tailwind-css-fill

Hi @silham The icon you proposed has been completed and launched. Hope you like this project and Star our repo to support our efforts.
