### ISSUE TITLE
Calendar-Error | Calendar-Warning

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#504]
## Icon Request

* Icon name: Calendar-x or calendar-error | calendar-warning
* Tags of this icon: Business
* Use case: A calendar icon with an error mark and/or with warning a user with a date is wrong or invalid
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/38047906/228223376-df95a865-bd95-4be7-a0b5-a1bab8478e65.png)

**Comment by xiaochunjimmy** [comment]
Thanks for the suggestion. Now you can get those icons in version v3.2.0.

https://remixicon.com/icon/calendar-close-line
https://remixicon.com/icon/calendar-close-fill
