### ISSUE TITLE
Hourglass icon

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#505]
## Icon Request

* Icon name: Hourglass
* Tags of this icon: System
* Use case: An alternative to timer/clock to when the document is almost due or time is running out, consider putting error/warning/check marks will be good too
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/38047906/228224210-9daaefc4-3585-436c-bf9d-4f149e570351.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/hourglass-line
https://remixicon.com/icon/hourglass-fill

https://remixicon.com/icon/hourglass-2-line
https://remixicon.com/icon/hourglass-2-fill
