### ISSUE TITLE
Loop Icon

### ISSUE THREAD

**Issue by davi-lessa** [Remix-Design/RemixIcon#506]
Icon name: Loop
Tags of this icon: media
Use case: player controls button
Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/84092110/228908147-8fa5f80e-c23a-4355-99f8-bdd7c7c6d823.png)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/loop-left-line

https://remixicon.com/icon/refresh-line
