### ISSUE TITLE
Icons copied without empty box | v3.0.0

### ISSUE THREAD

**Issue by funk4d** [Remix-Design/RemixIcon#507]
**Describe the bug**
For example in previous version _arrow-drop-left-line_ icon copied with empty box and size of this icon was 24x24px. For now it copies without empty box and size of icon is 5,66x8,49px.

**Comment by xiaochunjimmy** [comment]
Ah, I got it.
You are a Sketch user, right?

**Comment by funk4d** [comment]
> You are a Sketch user, right?

RIght!

**Comment by xiaochunjimmy** [comment]
I think we can fix it soon for Sketch users.

We intentionally removed the empty box because more and more users are all from Figma, and the box is useless for them.

**Comment by funk4d** [comment]
@xiaochunjimmy, perfect, that was easy to find 😉 Thank you!

**Comment by aprilogao** [comment]
> 
你好，3.1.0更新说明里的Pallet不知道在哪开启，点击图标复制SVG粘贴到sketch还是小数点像素😭
