### ISSUE TITLE
Check all icon

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/RemixIcon#51]
## Icon Request

* Icon name: check-all
* Tags of this icon: check, check-all, checkboxes
* Use case: Let's say we have a column with checkboxes and at the top we want an icon to check them all. We could have an empty checkbox, but that may need explaining. **Also note that in case implemented, there are two states, empty and checked**
* Screenshots of similar icons: https://img.icons8.com/ios/420/check-all.png

**Comment by xiaochunjimmy** [comment]
This is a good suggestion Jens.
Like your words, a check-all icon is more clear than a checkbox icon in my scenario.
It also looks like a muti-check icon which used to activate the function of `muti-check`.

**Comment by jenstornell** [comment]
Just as a complement, I'll give a screenshot as well. When toggle the first checkbox, all other checkboxes should be checked. In that case a check-all icon would make sense.

![image](https://user-images.githubusercontent.com/927011/58711163-2dfb9c80-83be-11e9-909f-0ba66789a10c.png)

**Comment by xiaochunjimmy** [comment]
Here are your icons. Thank you for your advice, Jens.

[checkbox-multiple-blank-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/checkbox-multiple-blank-fill.svg)
[checkbox-multiple-blank-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/checkbox-multiple-blank-line.svg)

[checkbox-multiple-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/checkbox-multiple-fill.svg)
[checkbox-multiple-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/checkbox-multiple-line.svg)
