### ISSUE TITLE
Icon request: Kick

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#518]
## Icon Request

Kick is a new social platform similar to twitch, that has soared in popularity

* Icon name: kick
* Tags of this icon: kick, logo
* Use case: social media
* Screenshots of similar icons:
* 
![image](https://user-images.githubusercontent.com/33750251/229626632-b2f8daff-d643-41a7-840b-ea522583a5fa.png)

**Comment by xiaochunjimmy** [comment]
Thanks for the suggestion. Now you can get those icons in version v3.2.0.

https://remixicon.com/icon/kick-line
https://remixicon.com/icon/kick-fill
