### ISSUE TITLE
Usage Question?

### ISSUE THREAD

**Issue by Uranbold** [Remix-Design/RemixIcon#52]
Hello,

Instead of inserting SVG, Can we set the Font name and Insert Font Symbol on the program?

Thanks.

**Comment by YunYouJun** [comment]
Hello, this is my solution. [RemixIcon | Codepen](https://codepen.io/YunYouJun/pen/PrYbNP)
I hope that can be some help for you.

Symbol can not import external resources, so I paste [it](https://raw.githubusercontent.com/Remix-Design/RemixIcon/master/fonts/remixicon.symbol.svg#remixicon-album-line) all in.

**Comment by Uranbold** [comment]
Thanks but I mean if I wanna use it on Photoshop then first I need to install the Font and then how do I use it like Regular Font like setting the fontsizes?

For Example, FontAwesome has Unicode Glyph?

I need Unicode Glyph CheatSheat?

Thanks.

**Comment by YunYouJun** [comment]
Sorry, I don't understand it very clearly.
Is this what you need?
```css
.remixicon-4k-fill:before { content: "\ea01"; }
```
You can find more in <https://github.com/Remix-Design/RemixIcon/blob/master/fonts/remixicon.css>.

**Comment by Uranbold** [comment]
Hello,

If I insert it on Photoshop it's not working.

**Comment by YunYouJun** [comment]
Did you install [remixicon.ttf](https://github.com/Remix-Design/RemixIcon/blob/master/fonts/remixicon.ttf)?

Sorry, I don't know how to use icon font in Photoshop.

**Comment by Uranbold** [comment]
No :) IconFont is like windows font you know? We are changing Fonts on PhotoShop right? I wanna use this Icon on Photoshop. After changing the fonts Photoshop is not displaying the fonts like SVG?

Thanks.

**Comment by YunYouJun** [comment]
Hello, I test it in GIMP(like photoshop) and success.
![image](https://user-images.githubusercontent.com/25154432/59193780-69197f00-8bb9-11e9-80ff-7fb7a72e3873.png)
I enter `\ee79` by [remixicon.css](https://github.com/Remix-Design/RemixIcon/blob/master/fonts/remixicon.css.).
I think you just need to install [remixicon.ttf](https://github.com/Remix-Design/RemixIcon/blob/master/fonts/remixicon.ttf) and then input unicode.

**Comment by wendygaoyuan** [comment]
1. Install remixicon.ttf
2. Open Glyphs panel, select `Type` > `Panels` > `Glyphs panel`
<img width="640" alt="open Glyphs panel" src="https://user-images.githubusercontent.com/25056241/59197477-01b4fc80-8bc4-11e9-98fd-a93d7d1b693b.png">
3.Select `remixicon` and `Entire Font`
<img width="648" alt="select remixIcon" src="https://user-images.githubusercontent.com/25056241/59197665-6b350b00-8bc4-11e9-998b-b489604af085.png">
Then you can use remixicon in Photoshop ~

**Comment by Uranbold** [comment]
Thanks, @wendygaoyuan @YunYouJun Really appreciate it.
