### ISSUE TITLE
Icon request: Blender

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#529]
## Icon Request

https://www.blender.org/

* Icon name: blender
* Tags of this icon: blender, design
* Use case: For 3D design
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/229635423-d04d91b4-3eb8-45ba-88a8-653d0c405eaf.png)

**Comment by xiaochunjimmy** [comment]
Hi Chiru, this icon has been added in v3.1.0
