### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by VanquishedWombat** [Remix-Design/RemixIcon#535]
## Icon Request

* Icon name:  Font
* Tags of this icon:  font-select
* Use case:  Some editors like MS Word use a dropdown for font name (and size) selection. However, for a minimal design of toolbar it would be good to have an icon representing font selection.  Something like the 'A' in the font-color icon would be ideal.
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/55594003/230311077-a2f593a3-9e7b-4b4b-baec-126aed648dec.png)

**Comment by xiaochunjimmy** [comment]
@VanquishedWombat 
Thanks for the suggestion. Now you can get those icons in version v3.2.0. I also added some other related Icons:

https://remixicon.com/icon/font-family
https://remixicon.com/icon/font-sans-serif
https://remixicon.com/icon/font-sans
https://remixicon.com/icon/font-mono
