### ISSUE TITLE
Icon shifted down - Flutter usage

### ISSUE THREAD

**Issue by nipunapereratb** [Remix-Design/RemixIcon#536]
**Describe the bug**
Before v3.0.0 there weren't any issues with the icons, but after the new version, every icon is shifted down.
We are using the icons in a Flutter application and now the icons are wrongly placed

**To Reproduce**
1. Download the font package and check the .ttf file

**Expected behavior**
The icons should appear like in the left side of the screenshot below

**Screenshots**
![Screenshot 2023-04-06 at 15 50 33](https://user-images.githubusercontent.com/100197486/230398434-cba175dc-6a7d-4b40-8daa-d5ab1207de18.png)

**Device (please complete the following information):**
 - OS: MacOS 13.0.1

**Additional context**
Is there any way to use any of the previous versions?

Thank you.

**Comment by xiaochunjimmy** [comment]
1. In version 3.0.0, we have readjusted the baseline of the icons. Theoretically, the baseline of v3.0.0 is more reasonable. I am curious if you manually adjusted the icon offset of version 2.5.0 before. If so, readjusting the offset should suffice.
2. You can download previous versions on the [Release](https://github.com/Remix-Design/RemixIcon/releases) page. GitHub is a version control tool where you can find all the historical versions.

**Comment by nipunapereratb** [comment]
Hi @xiaochunjimmy we didn't adjust the offset manually, that's how we found out the icons were shifted down.

Thank you for the response, let us know.

**Comment by n-ce** [comment]
I faced the same issue for the icons on my website. I had to use bottom margin ultimately.

**Comment by mchesnokov** [comment]
Same issue with some of the google icons on flutter web on mobile devices.

**Comment by wendygaoyuan** [comment]
@nipunapereratb @mchesnokov @n-ce  Did you download the font file you are using from the website's collection?

**Comment by n-ce** [comment]
> @nipunapereratb @mchesnokov @n-ce Did you download the font file you are using from the website's collection?

Yes. Also, I downloaded again today and it seems the issue has been solved.

**Comment by wendygaoyuan** [comment]
> > @nipunapereratb @mchesnokov @n-ce Did you download the font file you are using from the website's collection?
> 
> Yes. Also, I downloaded again today and it seems the issue has been solved.

We fixed this issue 2 days ago

**Comment by nipunapereratb** [comment]
Its seems working fine now, thank you
