### ISSUE TITLE
Drag Icon (6 dots)

### ISSUE THREAD

**Issue by Hutsko** [Remix-Design/RemixIcon#537]
## Icon Request

* Icon name: Draggable
* Tags of this icon: drag, drop, move, dots
* Use case: when users need to drag something they usually look for an icon with dots which they drag with a cursor (it works like a handle)
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/27406893/230446728-426bba17-37a3-46a4-af6b-f9e381414e63.png)
![image](https://user-images.githubusercontent.com/27406893/230446823-6c31d240-2d20-4e44-a517-f2540cc70176.png)
![image](https://user-images.githubusercontent.com/27406893/230446862-46ecbd6c-aaf8-418b-89de-e5b277c674ee.png)
![image](https://user-images.githubusercontent.com/27406893/230447341-3873b3fa-52fd-4aa5-8ce7-d749e4f7b820.png)
![image](https://user-images.githubusercontent.com/27406893/230447377-c6c931c6-d56b-4a14-94a7-ec391b424d08.png)
![image](https://user-images.githubusercontent.com/27406893/230447429-d2977efb-2fa6-430a-8894-d63871f84392.png)

**Comment by xiaochunjimmy** [comment]
Thanks for the advice.
Now you can get this icon in version v3.2.0.

https://remixicon.com/icon/draggable
