### ISSUE TITLE
v.3.1.0 didn't get published to NPM on release

### ISSUE THREAD

**Issue by docmars** [Remix-Design/RemixIcon#538]
Hey there! Just wanted to let you know that v3.1.0 appears not to have made it to NPM, so when attempting to install it, 3.0.0 is the latest version available using package managers.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/758090/230476809-b33380ab-e3f8-49e8-b0dd-5f891daf2821.png">

**Comment by wendygaoyuan** [comment]
Actions runner had an issue, it has been fixed
