### ISSUE TITLE
Possible mislabeling of pass-valid and pass-expired icons.

### ISSUE THREAD

**Issue by shindradavid** [Remix-Design/RemixIcon#542]
The pass-valid icon has a cross while the pass-expired icon has a mark.

**Expected behaviour**
A pass-valid icon with a check and a pass-expired icon with a cross

**Screenshot**
![bug-report](https://user-images.githubusercontent.com/111683723/231720824-5b7db6c3-de1b-4b4d-8466-ef6d359c178a.png)

**Comment by xiaochunjimmy** [comment]
OMG! Thank you for the notification! We'll fix it this weekend

**Comment by xiaochunjimmy** [comment]
The issue has been fixed.
