### ISSUE TITLE
Defect in volume icons

### ISSUE THREAD

**Issue by WRtux** [Remix-Design/RemixIcon#544]
### Describe the bug

The sound waves in these icons are not symmetric, or to be more precise, not perfect quarter arcs.

### Screenshot

![Defect](https://user-images.githubusercontent.com/34528883/231799977-703e420b-6e99-4bc4-ba0d-42667e2bb1d9.PNG)

### Suggestion

I made a corrected version of `volume-up-line`, attached below. (Note that **the left part of this icon is resized** to meet my needs.)

![volume-up-line](https://user-images.githubusercontent.com/34528883/231800651-78eb1a1c-2ecd-4984-b59f-fe4b0a0487d1.svg)

**Comment by xiaochunjimmy** [comment]
The issue has been fixed.
