### ISSUE TITLE
收藏夹中下载的font在页面上宽高不同，icon未在中心位置

### ISSUE THREAD

**Issue by 352718784** [Remix-Design/RemixIcon#548]
**Describe the bug**
收藏icon并下载收藏夹内的fonts，在项目中引用发现icon位置不在中心位置

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/52225733/233247526-de0f40ae-5970-4c81-a818-72a6fb500465.png)
![image](https://user-images.githubusercontent.com/52225733/233247754-5578c76f-2e42-42a9-b175-e472c268859e.png)

**Device (please complete the following information):**

**Additional context**

**Comment by wendygaoyuan** [comment]
这很奇怪，能提供下生成的ttf字体文件吗？

**Comment by 352718784** [comment]
> 下生成的字体文件吗？

[remix-icon.zip](https://github.com/Remix-Design/RemixIcon/files/11302644/remix-icon.zip)
下载的字体库压缩包 
很奇怪的是，如果我使用cdn中的文件（https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css），并没有发现这样的问题

**Comment by qsfty** [comment]
我也遇到了，字体底部有一部分被截断了
![mm1](https://github.com/Remix-Design/RemixIcon/assets/20365990/36f90a2f-6d9a-4d5b-8650-149da5cc5407)

应该是一个通病

@wendygaoyuan

**Comment by reruin** [comment]
遇到同样的问题。

**Comment by wendygaoyuan** [comment]
已修复上线，朋友们刷新下官网，重新生成试试 @reruin @qsfty @352718784
