### ISSUE TITLE
Icon Request: Spotify

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#55]
## Icon Request

* Icon name: Spotify
* Tags of this icon: spotify
* Use case: Spotify is a very popular music streaming app
* Screenshots of similar icons:
![Spotify Logo](https://user-images.githubusercontent.com/33750251/59486049-ec63fa80-8e6f-11e9-8d17-9a31324a63e8.png)

**Comment by xiaochunjimmy** [comment]
[spotify-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/spotify-line.svg)

[spotify-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/spotify-fill.svg)
