### ISSUE TITLE
Audio Icon

### ISSUE THREAD

**Issue by imaadesh** [Remix-Design/RemixIcon#557]
**Is your feature request about our website? Please describe.**
Yes. I could not find an icon to represent an audio. most of it is either sound or speakers. Can you help create an icon for audio

**Is your feature request about the Usage? Please describe.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Something on this line.
https://cdn-icons-png.flaticon.com/512/2778/2778524.png

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/voiceprint-line

Is this the icon you were looking for?

**Comment by imaadesh** [comment]
Yes. This helpsSent from my iPhoneOn 04-May-2023, at 10:47 AM, 章萧醇 ***@***.***> wrote:﻿
https://remixicon.com/icon/voiceprint-line
Is this the icon you were looking for?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



DISCLAIMER: The contents of this email, including any attachments that it may contain, are privileged and confidential information, and may also constitute as proprietary, and are intended solely for the use of the addressee(s). If you are not the intended recipient, please notify the sender by email and delete the original message. Unintended recipients are strictly prohibited from copying, disclosing, and/or distributing such contents in any manner or form. Opinions, conclusions, and other information in this transmission that do not relate to the official business of Amagi, including all its affiliates, shall be understood as neither given nor endorsed by it. Any statements made herein that are tantamount to contractual obligations, promises, claims or commitments shall not be binding on the Company unless expressly and specifically stated as otherwise, or followed by written confirmation, by an authorized signatory of the Company.
