### ISSUE TITLE
Icon Request: Consoles and Gamepads

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#56]
## Icon Request

* Icon name: playstation, xbox, nintendo, gamepad
* Tags of this icon: playstation, xbox, gamepad, controller
* Use case: 
* Screenshots of similar icons:
![Console Logos](https://user-images.githubusercontent.com/33750251/59486187-6bf1c980-8e70-11e9-9954-cbdaab333bad.png)
![Xbox Controller](https://user-images.githubusercontent.com/33750251/59486223-8b88f200-8e70-11e9-9279-e836dc317c43.png)
![PS4 Controller](https://user-images.githubusercontent.com/33750251/59486294-c5f28f00-8e70-11e9-9af3-117cdc1eed13.png)
![Wii Controller](https://user-images.githubusercontent.com/33750251/59486271-b07d6500-8e70-11e9-84d3-00dbe1851e94.png)

**Comment by itsezc** [comment]
Thank you for the wonderful new icons available in the new release, they look amazing! @xiaochunjimmy

**Comment by xiaochunjimmy** [comment]
We would add gamepad icons in the future, so we won't close this issue for now.

**Comment by YunYouJun** [comment]
I just wanted to make a request like this, then find it.
Looking forward to the completion of the icon.
😋

**Comment by xiaochunjimmy** [comment]
Here are `Consoles and Gamepads` related icons. @YunYouJun @itsezc
You can find them in the `Device` category.

https://remixicon.com/#icon-gamepad-line
https://remixicon.com/#icon-gamepad-fill

https://remixicon.com/#icon-remote-control-line
https://remixicon.com/#icon-remote-control-fill

https://remixicon.com/#icon-remote-control-2-fill
https://remixicon.com/#icon-remote-control-2-fill
