### ISSUE TITLE
Please add the "min" and "minus" to find subtract icon(s)

### ISSUE THREAD

**Issue by Loosie94** [Remix-Design/RemixIcon#560]
**Is your feature request about our website? Please describe.**
Website

**Is your feature request about the Usage? Please describe.**
Yes, about the search

**Is your feature request related to a problem? Please describe.**
Please add the "min" and "minus" keywords, to find the subtract icon. Was looking long for this.

**Describe the solution you'd like**
The keywords to be added to find minus icon

**Comment by xiaochunjimmy** [comment]
Thank for the advices, we've added the keywords in v3.4.0
