### ISSUE TITLE
Terminated and Rejected icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#566]
Terminated is when the user or organisation want to stop the delivery
User and building(organisation) icon with **indeterminate-circle-line** element
<img width="181" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/6d070f0e-ec92-4b1a-a43f-4e195916cad6">

Rejected is when the user or organisation want to reject the delivery request
[User-unfollow-line ](https://remixicon.com/icon/user-unfollow-line)
**Close** icon needed with building(organisation)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/user-forbid-line
