### ISSUE TITLE
新更新的图标的粗细似乎和原来的不一致

### ISSUE THREAD

**Issue by mozhux** [Remix-Design/RemixIcon#567]
**Describe the bug**
新更新的图标粗细和原来的不一致，
![image](https://github.com/Remix-Design/RemixIcon/assets/46953371/68cc1b6c-3f73-4b94-85a8-162c705e97eb)

放到https://icomoon.io/app/#/select 后处理的结果就粗挺多的。

**To Reproduce**
3. See error...

**Expected behavior**

**Screenshots**
![image](https://github.com/Remix-Design/RemixIcon/assets/46953371/68cc1b6c-3f73-4b94-85a8-162c705e97eb)

**Device (please complete the following information):**
 - OS: [e.g. OSX 10.14.2]
 - Browser& amp;Version [e.g. Chrome 71.0.3578.98(64-bit)]
 - Website Version [e.g. 1.2.1]

**Additional context**

**Comment by xiaochunjimmy** [comment]
很奇怪，理论上是一致的；你试试下载图标的时候勾选上「Pallet」选项，然后再导入 iconmoon
<img width="807" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/fd8b132a-51dc-47db-a3fd-dc632632a7e3">

**Comment by mozhux** [comment]
> 

收到，我改天试试，重构一下。
