### ISSUE TITLE
Icon Request: Reddit

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#57]
## Icon Request

* Icon name: reddit
* Tags of this icon: reddit
* Use case: Reddit is a popular forums / discussion boards and is widely used
* Screenshots of similar icons:
![Reddit Logo](https://user-images.githubusercontent.com/33750251/59486444-3699ab80-8e71-11e9-9f9a-836e431dcbfd.png)

**Comment by xiaochunjimmy** [comment]
[reddit-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/reddit-line.svg)

[reddit-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/reddit-fill.svg)
