### ISSUE TITLE
2D Basic Shapes Icons

### ISSUE THREAD

**Issue by Rhyan-eduardo** [Remix-Design/RemixIcon#572]
2D Basic Shapes

* Icon name: Shapes
* Tags of this icon: editor , design
* Use case: media editor , draw applications
* Screenshots of similar icons:
![Screenshot_1](https://github.com/Remix-Design/RemixIcon/assets/67023605/1a3fef43-c718-4cc3-9e0d-74f5036f4fc6)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/circle-line
https://remixicon.com/icon/triangle-line
https://remixicon.com/icon/pentagon-line
https://remixicon.com/icon/hexagon-line
https://remixicon.com/icon/octagon-line
https://remixicon.com/icon/square-line
https://remixicon.com/icon/rectangle-line

**Comment by Rhyan-eduardo** [comment]
wow. thank you for adding the mentioned icons, it helps a lot in my projects and in future community projects, I appreciate your willingness to add the suggestions, very grateful
