### ISSUE TITLE
一个微不足道的小建议

### ISSUE THREAD

**Issue by ScarletDor** [Remix-Design/RemixIcon#577]
我是这样想的啦，你看日本的emoji，里面有非常多的日本文化的东西，作为一款非常棒的图标库，是否可以考虑一下关于中国文化的符号标志，比如灯笼啊什么的

反而很好奇为什么会有一个十字架🤣

**Comment by xiaochunjimmy** [comment]
很棒的建议啊！中国有蛮多不错的文化元素可以考虑进来；

十字架图标的来源于一个用户的反馈，他们有个功能是逝者相关的，十字架、蜡烛可能会在不同文化的背景下代表逝者含义；所以十字架倒不是代表了文化属性之类的；

不过我们有个原则是会优先添加大家在工作中实际遇到的图标需求，所以相对宽泛的建议会晚一些；结合咱们这个话题本身，比如有用户需要 Animals 的图标类型，然后可以结合中国的十二生肖

**Comment by ScarletDor** [comment]
原来是这样，我还以为是啥基督什么的，还在想怎么没有个圣诞树哈哈哈哈哈
