### ISSUE TITLE
dribbble 图标的fill 和 line 是不是搞反了

### ISSUE THREAD

**Issue by liushiwie** [Remix-Design/RemixIcon#579]

**Comment by liushiwie** [comment]
还有reactjs、openai、openbase

**Comment by xiaochunjimmy** [comment]
其实没反，在 LOGO 这个栏目中，Fill 的大体规则是「使用其原始LOGO」，然后 line 是「按照 RemixIcon 的风格标准绘制」，而不是 Fill 比 Line 粗；有的 logo 原始就是比较细的，适配了 RemixIcon 风格之后反而显得比较粗，就像是搞反了；
