### ISSUE TITLE
Icon Request: Genders

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#58]
## Icon Request

* Icon name: male, female etc.
* Tags of this icon: male, female etc.
* Use case: Identify genders
* Screenshots of similar icons:
![Common genders](https://user-images.githubusercontent.com/33750251/59486672-03a3e780-8e72-11e9-958a-27225600dc3a.png)

**Comment by xiaochunjimmy** [comment]
On my god

**Comment by xiaochunjimmy** [comment]
I only added 2 icons of genders. Most of them seem uncommon in our life.
Maybe we'll add all of them in the future when they are more official.
[genderless-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/User/genderless-line.svg)
[genderless-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/User/genderless-fill.svg)

[travesti-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/User/travesti-line.svg)
[travesti-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/User/travesti-fill.svg)
