### ISSUE TITLE
RFID icon

### ISSUE THREAD

**Issue by agaprabowo** [Remix-Design/RemixIcon#580]
## Icon Request

* Icon name: RFID
* Tags of this icon: Device
* Use case: for app that use RFID technology
* Screenshots of similar icons:

![image 1](https://github.com/Remix-Design/RemixIcon/assets/68990155/c1a9d8b1-08b4-4f0d-b8f5-ee5cc6be2094)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/rfid-line
