### ISSUE TITLE
Infinity Symbol

### ISSUE THREAD

**Issue by PauloVBettio** [Remix-Design/RemixIcon#585]
## Icon Request

* Icon name: Infinity Symbol
* Tags of this icon: Infinite, Infinity, Endless, Loop, Forever, Math, Eternal
* Use case: Math and anything related to infinity
* Screenshots of similar icons: 
![image](https://github.com/Remix-Design/RemixIcon/assets/74562432/a5d5d0f5-5296-475a-b55c-d62ec9342a7b)

**Comment by xiaochunjimmy** [comment]
Check it out here:
https://remixicon.com/icon/infinity-line

Please star our project if you like it
