### ISSUE TITLE
Svelte icon request

### ISSUE THREAD

**Issue by alanielbahl** [Remix-Design/RemixIcon#588]
## Svelte icon

* Icon name: Svelte icon xd
* Tags of this icon: Dev, Framework, Programming, Code
* Use case: Dev portfolios and dev projects
* Screenshots of similar icons: 
![Svelte](https://github.com/Remix-Design/RemixIcon/assets/83141708/30d4a061-809d-49e9-8f9b-e6976795c33b)
![Svelte](https://simpleicons.org/icons/svelte.svg)

**Comment by dufu1991** [comment]
这个好，上次做 https://stdf.design 站点的时候没有 Svelte icon，还专门找了半天才找到一个合适的。希望顺便把 Tailwind CSS 的也加上。
题外话，非常感谢 RemixIcon，我的两个开源项目都用了。

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/svelte-fill

https://remixicon.com/icon/svelte-line
