### ISSUE TITLE
## Icon Request  * Icon name:  no available data 

### ISSUE THREAD

**Issue by haidarabdillah** [Remix-Design/RemixIcon#589]
## Icon Request

* Icon name:  no available data 
* Tags of this icon: table/data
* Use case: use it when no data available/no transaction data
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/113880800/99c11b81-e63d-417d-a282-d582051ea6e0)
![image](https://github.com/Remix-Design/RemixIcon/assets/113880800/6f270409-168d-4bee-be23-c2e1a1ea2923)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/file-forbid-line

**Comment by xiaochunjimmy** [comment]
I've also made a new icon for your case:
https://remixicon.com/icon/file-close-line

Please star our project if you like it
