### ISSUE TITLE
Dropdown List Icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#596]
## Icon Request

* Icon name: dropdown 
* Tags of this icon: drodown, field
* Screenshots of similar icons:
<img width="271" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/89b928ce-2431-4922-80ef-4418210ce83b">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/dropdown-list
