### ISSUE TITLE
Half star

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/remixicon#6]
## Icon Request

* Icon name: star-half
* Tags of this icon: star,half
* Use case: When converting the number 3.5 to icons, a half star icon would come in handy
* Screenshots of similar icons: https://fontawesome.com/icons/star-half-alt?style=solid

**Comment by xiaochunjimmy** [comment]
Got it~
We will update in the next icon version(not website version)

**Comment by xiaochunjimmy** [comment]
Now you can find the `star-half` and `star-half-s` icon in the `System` category.

Website version v1.3.2
Icon version v1.1.1
