### ISSUE TITLE
Icon Request: Netflix

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#60]
## Icon Request

* Icon name: netflix
* Tags of this icon: netflix
* Use case: Netflix is a popular tv and show streaming service
* Screenshots of similar icons:
![Netflix icon](https://user-images.githubusercontent.com/33750251/59487006-313d6080-8e73-11e9-8c50-3a5660761138.png)

**Comment by xiaochunjimmy** [comment]
[netflix-line.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/netflix-line.svg)

[netflix-fill.svg](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/netflix-fill.svg)
