### ISSUE TITLE
Search Library

### ISSUE THREAD

**Issue by a9dezign** [Remix-Design/RemixIcon#601]
## Icon Request

* Icon name: 
* Tags of this icon: 
* Use case: 
* Screenshots of similar icons:
<img width="126" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/44572398/050156b6-52c8-40ea-92d3-6a8d89d2dd71">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/menu-search-line

**Comment by a9dezign** [comment]
Thank you ❤️
