### ISSUE TITLE
Media Folders

### ISSUE THREAD

**Issue by LauraWebdev** [Remix-Design/RemixIcon#602]
## Icon Request

* Icon name: folder-video, folder-image
* Tags of this icon: video folder, image folder, media folder
* Use case: Media libraries, Media filters
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/7365286/a86a4420-27ea-4942-94f5-11f3e4919099)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/folder-image-line
https://remixicon.com/icon/folder-video-line

https://remixicon.com/icon/file-image-line
https://remixicon.com/icon/file-video-line
