### ISSUE TITLE
Meta Threads logo

### ISSUE THREAD

**Issue by CptCorporate** [Remix-Design/RemixIcon#605]
## Icon Request

* Icon name: Threads logo
* Tags of this icon: threads
* Use case: Link to Threads Social Account
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/1021345/03da0176-53f3-4e08-ab3e-c90e010d20f8)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/threads-fill
