### ISSUE TITLE
Tent icon

### ISSUE THREAD

**Issue by xanthipe** [Remix-Design/RemixIcon#608]
## Icon Request

* Icon name: tent
* Tags of this icon: camping, tent, outdoors, building?
* Use case: Similar to other building icons - normally used for marking out a campsite or similar on a map. In my specific case, differentiating an event happening at a campsite rather than the local woods.
* Screenshots of similar icons:
  * Font Awesome: ![image](https://github.com/Remix-Design/RemixIcon/assets/7863997/e859607e-fa36-4b98-9e7a-d5f590ab0321)
  * Flat Icon: ![image](https://github.com/Remix-Design/RemixIcon/assets/7863997/c6370b74-9101-43a1-8eb1-65bad28300d3) & ![image](https://github.com/Remix-Design/RemixIcon/assets/7863997/f1d0ea96-b776-4452-b48e-5a9276d9dd4b)
  * Google Maps: ![image](https://github.com/Remix-Design/RemixIcon/assets/7863997/3381033e-852f-4df5-8345-08b1ac987d3d)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/tent-line
https://remixicon.com/icon/tent-fill
