### ISSUE TITLE
PDF icon

### ISSUE THREAD

**Issue by Aleboeuf** [Remix-Design/RemixIcon#610]
## Icon Request

* Icon name: file-pdf-1, file-pdf-2
* Tags of this icon: pdf, file, adobe, print
* Use case: in a button for downloading a .pdf file
* Screenshots of similar icons: https://icons8.com/icon/set/pdf/fluency or https://icons8.com/icon/set/pdf/fluency

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/file-pdf-2-line
https://remixicon.com/icon/file-pdf-2-fill
