### ISSUE TITLE
Icons Page Not Responsive

### ISSUE THREAD

**Issue by kumarankit999** [Remix-Design/RemixIcon#612]
**Describe the bug**
The Icons are not responsive in a way that, We are not able to Copy the Tag of the respective Icon.

**To Reproduce**
3. See error...

**Expected behavior**
All the Pages should be responsive and at any dimension , we are able to copy the tag of the desired icons

**Screenshots**

![image](https://github.com/Remix-Design/RemixIcon/assets/111564362/495595be-49dc-4c3d-a9f3-cac2fe2ad1dc)

![image](https://github.com/Remix-Design/RemixIcon/assets/111564362/e58e9ffe-ee01-445b-9ecb-02187edc2dcc)

**Device (please complete the following information):**
 - OS: Windows
 - Browser& amp; Version [e.g. Chrome 71.0.3578.98(64-bit)]
 - Website Version v3.4.0
**Additional context**

**Comment by xiaochunjimmy** [comment]
May I know in what case you need to copy tags in such a small window? Why not use a larger window directly?
