### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by dennemark** [Remix-Design/RemixIcon#613]
## Icon Request

* Icon name: Tree
* Tags of this icon:  tree, plant, nature i.e.
* Use case: Icon for planting trees or show category of trees on maps.
* Screenshots of similar icons: 
![image](https://github.com/Remix-Design/RemixIcon/assets/29654902/4b0d9296-c9ba-4238-86da-31a294dbb208)

Thanks for your effort, the icon library is already so big and great! I am surprised I did not find a tree yet :)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/tree-line
https://remixicon.com/icon/tree-fill

**Comment by dennemark** [comment]
Looks beautiful, thanks!!!
