### ISSUE TITLE
Better Sorting icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#616]
* Icon name: sort by alphabetical, sort by numerical

## Icon Request
![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/052f6362-3388-4e92-8513-ce2b1e41ba49)

![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/617853e4-246c-4fc5-ac9d-ffef05aec0dc)

**Comment by xiaochunjimmy** [comment]
<img width="654" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/fcc5cf6c-8636-434f-820b-93f2975f9aad">
https://remixicon.com/icon/sort-alphabet-desc
https://remixicon.com/icon/sort-number-desc
