### ISSUE TITLE
Dice

### ISSUE THREAD

**Issue by adrianchmuraa** [Remix-Design/RemixIcon#618]
## Icon Request

* Icon name: dice
* Tags of this icon: dice, random 
* Use case: For random generator features on wesbites
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/106346480/f45ae8bd-f569-42f8-bafd-5cb0c98e4421)
![image](https://github.com/Remix-Design/RemixIcon/assets/106346480/73717cd3-d4a3-4802-9fc0-f004f7aab4cc)
![image](https://github.com/Remix-Design/RemixIcon/assets/106346480/e54d48df-883c-401c-8f50-59baa63e7321)
![image](https://github.com/Remix-Design/RemixIcon/assets/106346480/246bb33f-144c-4141-960e-02c0232a6b31)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/dice-line
you can also find other related icons in our project
<img width="861" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/162b8158-18bf-4b3c-8246-9e4b34b09c38">
