### ISSUE TITLE
Share-bracket icon

### ISSUE THREAD

**Issue by iamdarkle** [Remix-Design/RemixIcon#619]
## Icon Request

Lately a new type of icon for "sharing" has been gaining a lot of traction, I see it on more and more sites, for example Twitter, Reddit... I think it would be a great addition to include.

* Icon name: share-bracket
* Tags of this icon: System, sharing
* Use case: Share button
* Screenshots of similar icons:

![Screenshot 2023-08-08 150748](https://github.com/Remix-Design/RemixIcon/assets/15818451/fa803ed1-c194-4f08-87bd-7ccf2fa73068)

![Screenshot 2023-08-08 150933](https://github.com/Remix-Design/RemixIcon/assets/15818451/dab42b90-0ff8-4eac-90ce-4fcc1583bf5d)

**Comment by iamdarkle** [comment]
`Share-2` has been released with `3.6.0` so we can close @xiaochunjimmy ?

**Comment by xiaochunjimmy** [comment]
Wow, you are so fast. I'm about to tell you the good news. 

I will close this issue.
