### ISSUE TITLE
Icon Request: Weather Icons

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#62]
## Icon Request

* Icon name: sun, rain, cloudy, storm etc.
* Use case: Websites, UIs or Apps that have weather functionality 
* Screenshots of similar icons:
![Weather icons](https://user-images.githubusercontent.com/33750251/59487276-14555d00-8e74-11e9-97a9-0fb92d6ffce2.png)

**Comment by xiaochunjimmy** [comment]
I'd like to add the `sun` icon first，and some others in the future. thank you for your advice.
we hope the `request` is something you really need rather than what you think we should have. There's too much icon gallery we do not have for now and they are a huge work. So we always design what you need first, thank you for your understanding.

**Comment by xiaochunjimmy** [comment]
Finally, 
we've added 28 pair of weather icons. You can find them at the bottom of our website [remixicon.com](https://remixicon.com).

**Comment by itsezc** [comment]
Great, absolutely! 

However we should consider adding some additional ones (especially for warnings) i.e. 

Cyclone / Tornado:

![image](https://user-images.githubusercontent.com/33750251/64995312-c9177400-d8d2-11e9-9ab7-80370ba84c9c.png)

Flood:

![image](https://user-images.githubusercontent.com/33750251/64995352-e4827f00-d8d2-11e9-948f-30ea7c55dbfb.png)

Earthquake:

![image](https://user-images.githubusercontent.com/33750251/64995426-1abffe80-d8d3-11e9-8271-dc1974c978aa.png)

Would be amazing to see these as many icon frameworks out there don't even come close to these.

**Comment by itsezc** [comment]
@xiaochunjimmy Thanks for the new additions, however there is an icon `flashlight` which is in the wrong category 

Also here are few more icons we could possibly add:

![image](https://user-images.githubusercontent.com/33750251/72226279-6cc61780-3587-11ea-9c0e-21f374e5c57a.png)

![image](https://user-images.githubusercontent.com/33750251/72226282-73ed2580-3587-11ea-859f-e74312009ce6.png)

![image](https://user-images.githubusercontent.com/33750251/72226285-91ba8a80-3587-11ea-9e6c-5da481817337.png)


![image](https://user-images.githubusercontent.com/33750251/72226295-9da64c80-3587-11ea-8758-e3f635d61e11.png)

![image](https://user-images.githubusercontent.com/33750251/72226301-a72fb480-3587-11ea-8b70-cdde488363df.png)
