### ISSUE TITLE
add it to pub.dev 

### ISSUE THREAD

**Issue by alialnaghmoush** [Remix-Design/RemixIcon#624]
I hope to add the remix icon in pub.dev  so that we depend on it in our flutter projects as a reliable source

**Comment by alialnaghmoush** [comment]
3m it's easy to add to pub.dev

**Comment by alialnaghmoush** [comment]
Is there anything new about adding to pub.dev?

**Comment by leewei0923** [comment]
> Is there anything new about adding to pub.dev?

thank you!
https://pub.dev/packages/remixicon
