### ISSUE TITLE
Info icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#628]
## Icon Request

Request to add(not update) new [i] icon where you can use Slab i. Because many user may think it's a ! icon when they see the current sans version

* Icon name: info
* Tags of this icon: information
* Screenshots of similar icons:
<img width="157" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/8b350bdf-ef01-4ee8-a3b7-14a6d7dd226d">
<img width="147" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/4fa6f9b3-ade3-4673-bdaa-58dea447ef8d">

**Comment by iamrishishah** [comment]
Icon with circle is missing @xiaochunjimmy

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/information-2-line
https://remixicon.com/icon/information-2-fill

<img width="234" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/cb2993f2-a39b-4425-9400-59bfd2cbc65b">
