### ISSUE TITLE
Feature Request: Add Glyphs on the Website

### ISSUE THREAD

**Issue by Uranbold** [Remix-Design/RemixIcon#63]
Hello,

Could you please add all icon Glyphs to Copy Ready Lists like this -> https://ionicons.com/v2/cheatsheet.html

Thanks.

**Comment by xiaochunjimmy** [comment]
This is a feature we were thinking to support in the future, thank you for your advice.

**Comment by Uranbold** [comment]
I can help with this. If you give the correct format :)

**Comment by xiaochunjimmy** [comment]
Very appreciate of your offer, this feature is still in the interactive design phase.
The website is not an open-source project for now and we would connect you if needed, thank you so much.

**Comment by YunYouJun** [comment]
@xiaochunjimmy Will you consider making the official website open source? I think it is a good idea.

**Comment by Uranbold** [comment]
@xiaochunjimmy If you invite me then I can ready to help.

**Comment by xiaochunjimmy** [comment]
We've launched the v2.0.0 version of RemixIcon. 
Now you can copy the HTML Class names of icons easily from our website.

Sorry for a 2-month waiting (we've been busy in our work in the past months and we can only spare little time to maintain Remixicon).

**Comment by hevi1991** [comment]
If I don't want to specify a color, like the previous version, how do I operate in version 2.0?

如果我不想指定颜色，就像上个版本那样，如何在版本 2.0操作?

**Comment by xiaochunjimmy** [comment]
@hevi1991 上一个版本不指定颜色的话系统在展示上会默认赋予黑色，但代码里其实是没有色值的。这次不指定的话也会默认给到黑色色值。你是希望保持没有色值的状态的吗？这样需求的场景是？如果需求场景比较重要，我们考虑看要不要再新版本中适配一下

**Comment by hevi1991** [comment]
@xiaochunjimmy 嗯，非常感谢你的开源作品 ：），我目前使用没色值的svg格式做为web前端的图标。这样我去赋予css color的时候就可以填充图标的颜色了。假如默认给黑色的话，没办法灵活赋色。

![](http://ww2.sinaimg.cn/large/006y8mN6gy1g72hqrbqngj30pw07kgmf.jpg)

**Comment by XiKun-TW** [comment]
> @xiaochunjimmy 嗯，非常感谢你的开源作品 ：），我目前使用没色值的svg格式做为web前端的图标。这样我去赋予css color的时候就可以填充图标的颜色了。假如默认给黑色的话，没办法灵活赋色。
> 
> ![](https://camo.githubusercontent.com/6c0fe54b3d85a14343930bdf10c761c682a21fa9/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f30303679386d4e3667793167373268717262716e676a3330707730376b676d662e6a7067)

如果你是直接 copy、past svg 的话，在 fill 选项中去掉颜色值 即可。如果你是使用 background-image 这种方式的话，目前应该是无解的（即使不设置默认颜色）。

**Comment by hevi1991** [comment]
> > @xiaochunjimmy 嗯，非常感谢你的开源作品 ：），我目前使用没色值的svg格式做为web前端的图标。这样我去赋予css color的时候就可以填充图标的颜色了。假如默认给黑色的话，没办法灵活赋色。
> > ![](https://camo.githubusercontent.com/6c0fe54b3d85a14343930bdf10c761c682a21fa9/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f30303679386d4e3667793167373268717262716e676a3330707730376b676d662e6a7067)
> 
> 如果你是直接 copy、past svg 的话，在 fill 选项中去掉颜色值 即可。如果你是使用 background-image 这种方式的话，目前应该是无解的（即使不设置默认颜色）。

这是我的图标组件使用的样式代码，去掉fill之后，都会变成黑色。
以前没有色值的时候，完美符合我的需求。
```css
.svg-icon {
    width: 1em;
    height: 1em;
    vertical-align: -0.15em;
    fill: currentColor;
    overflow: hidden;
  }
```

**Comment by XiKun-TW** [comment]
> > > @xiaochunjimmy 嗯，非常感谢你的开源作品 ：），我目前使用没色值的svg格式做为web前端的图标。这样我去赋予css color的时候就可以填充图标的颜色了。假如默认给黑色的话，没办法灵活赋色。
> > > ![](https://camo.githubusercontent.com/6c0fe54b3d85a14343930bdf10c761c682a21fa9/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f30303679386d4e3667793167373268717262716e676a3330707730376b676d662e6a7067)
> > 
> > 
> > 如果你是直接 copy、past svg 的话，在 fill 选项中去掉颜色值 即可。如果你是使用 background-image 这种方式的话，目前应该是无解的（即使不设置默认颜色）。
> 
> 这是我的图标组件使用的样式代码，去掉fill之后，都会变成黑色。
> 以前没有色值的时候，完美符合我的需求。
> 
> ```css
> .svg-icon {
>     width: 1em;
>     height: 1em;
>     vertical-align: -0.15em;
>     fill: currentColor;
>     overflow: hidden;
>   }
> ```

有两个方式可以解决你的问题：
1. 目前我们是有 default color 的，所以可以使用 override 的方式去 override default color
2. 将目前 copy 的 svg 图片中的 fill 去掉，这样的话也能达到同样的效果

可以参考 code pen
https://codepen.io/Gougougogogo/pen/oNvPexa

**Comment by hevi1991** [comment]
> > > > @xiaochunjimmy 嗯，非常感谢你的开源作品 ：），我目前使用没色值的svg格式做为web前端的图标。这样我去赋予css color的时候就可以填充图标的颜色了。假如默认给黑色的话，没办法灵活赋色。
> > > > ![](https://camo.githubusercontent.com/6c0fe54b3d85a14343930bdf10c761c682a21fa9/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f30303679386d4e3667793167373268717262716e676a3330707730376b676d662e6a7067)
> > > 
> > > 
> > > 如果你是直接 copy、past svg 的话，在 fill 选项中去掉颜色值 即可。如果你是使用 background-image 这种方式的话，目前应该是无解的（即使不设置默认颜色）。
> > 
> > 
> > 这是我的图标组件使用的样式代码，去掉fill之后，都会变成黑色。
> > 以前没有色值的时候，完美符合我的需求。
> > ```css
> > .svg-icon {
> >     width: 1em;
> >     height: 1em;
> >     vertical-align: -0.15em;
> >     fill: currentColor;
> >     overflow: hidden;
> >   }
> > ```
> 
> 有两个方式可以解决你的问题：
> 
> 1. 目前我们是有 default color 的，所以可以使用 override 的方式去 override default color
> 2. 将目前 copy 的 svg 图片中的 fill 去掉，这样的话也能达到同样的效果
> 
> 可以参考 code pen
> https://codepen.io/Gougougogogo/pen/oNvPexa

@XiKun-TW 谢谢你，学习到了。

不过我暂时在用着 download 里面的打包 svg 文件，里面还没有配置默认颜色。
![](http://ww1.sinaimg.cn/large/006y8mN6gy1g72jrx57euj320g0jun05.jpg)

**Comment by xiaochunjimmy** [comment]
@XiKun-TW 我觉得可以设定为：当颜色为#000的时候，咱们默认不添加fill，因为系统会在没有fill的时候赋予黑色效果；除了#000的时候，我们都添加上fill色值属性。copy也是一样，如果用户调整了除了黑色的颜色，我们copy可以带上颜色，默认还是去除fill属性。好不？
