### ISSUE TITLE
Nodejs & Tailwind

### ISSUE THREAD

**Issue by aadrshkashyp** [Remix-Design/RemixIcon#638]
## Icon Request

* Icon name: Nodejs
* Tags of this icon:  nodejs
* Use case: Backend Tech Stack

![CleanShot 2023-09-03 at 06 55 35](https://github.com/Remix-Design/RemixIcon/assets/81368991/6c58957e-17f8-4e09-80eb-ff9510251f91)

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12 1.85c-.27 0-.55.07-.78.2l-7.44 4.3c-.48.28-.78.8-.78 1.36v8.58c0 .56.3 1.08.78 1.36l1.95 1.12c.95.46 1.27.47 1.71.47c1.4 0 2.21-.85 2.21-2.33V8.44c0-.12-.1-.22-.22-.22H8.5c-.13 0-.23.1-.23.22v8.47c0 .66-.68 1.31-1.77.76L4.45 16.5a.26.26 0 0 1-.11-.21V7.71c0-.09.04-.17.11-.21l7.44-4.29c.06-.04.16-.04.22 0l7.44 4.29c.07.04.11.12.11.21v8.58c0 .08-.04.16-.11.21l-7.44 4.29c-.06.04-.16.04-.23 0L10 19.65c-.08-.03-.16-.04-.21-.01c-.53.3-.63.36-1.12.51c-.12.04-.31.11.07.32l2.48 1.47c.24.14.5.21.78.21s.54-.07.78-.21l7.44-4.29c.48-.28.78-.8.78-1.36V7.71c0-.56-.3-1.08-.78-1.36l-7.44-4.3c-.23-.13-.5-.2-.78-.2M14 8c-2.12 0-3.39.89-3.39 2.39c0 1.61 1.26 2.08 3.3 2.28c2.43.24 2.62.6 2.62 1.08c0 .83-.67 1.18-2.23 1.18c-1.98 0-2.4-.49-2.55-1.47a.226.226 0 0 0-.22-.18h-.96c-.12 0-.21.09-.21.22c0 1.24.68 2.74 3.94 2.74c2.35 0 3.7-.93 3.7-2.55c0-1.61-1.08-2.03-3.37-2.34c-2.31-.3-2.54-.46-2.54-1c0-.45.2-1.05 1.91-1.05c1.5 0 2.09.33 2.32 1.36c.02.1.11.17.21.17h.97c.05 0 .11-.02.15-.07c.04-.04.07-.1.05-.16C17.56 8.82 16.38 8 14 8Z"/></svg>

* Icon name: Tailwind
* Tags of this icon:  tailwind
* Use case: CSS Library

![CleanShot 2023-09-03 at 06 56 00](https://github.com/Remix-Design/RemixIcon/assets/81368991/ef3be013-564f-4a83-ba42-5cdfd1ae3aaa)

<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 15 15"><path fill="none" stroke="currentColor" stroke-linejoin="round" d="M7.5 3C5.633 3 4.467 4 4 6c.7-1 1.517-1.375 2.45-1.125c.533.143.913.557 1.334 1.015C8.471 6.636 9.265 7.5 11 7.5c1.867 0 3.033-1 3.5-3c-.7 1-1.517 1.375-2.45 1.125c-.533-.143-.913-.557-1.334-1.015C10.029 3.864 9.235 3 7.5 3ZM4 7.5c-1.867 0-3.033 1-3.5 3c.7-1 1.517-1.375 2.45-1.125c.533.143.913.557 1.334 1.015C4.971 11.136 5.765 12 7.5 12c1.867 0 3.033-1 3.5-3c-.7 1-1.517 1.375-2.45 1.125c-.533-.143-.913-.557-1.334-1.015C6.529 8.364 5.735 7.5 4 7.5Z" clip-rule="evenodd"/></svg>

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/nodejs-fill
https://remixicon.com/icon/tailwind-css-fill

**Comment by xiaochunjimmy** [comment]
Hi @aadrshkashyp 
The icon you proposed has been completed and launched. Hope you like this project and Star our repo to support our efforts.
