### ISSUE TITLE
Site Search bar doesn't support Uppercase

### ISSUE THREAD

**Issue by n-ce** [Remix-Design/RemixIcon#640]
**Describe the bug**
Main website fails to show search results if input contains uppercase letters.

**To Reproduce**
1. Go to https://remixicon.com
2. Click on Search Bar
3. Search 'Settings' 
4. No Results Found

**Expected behavior**
Results should be found because 'Settings' icon clearly exists in the library

**Screenshots**
![chrome_screenshot_12 Sep 2023 12_29_26 GMT+05_30](https://github.com/Remix-Design/RemixIcon/assets/69345507/8b7084df-a0df-434d-b5eb-8ac839ce78ae)

**Comment by wendygaoyuan** [comment]
Thank you for your bug feedback, we have fixed this bug now
