### ISSUE TITLE
Icon Request (Kan-Ban view card icon)

### ISSUE THREAD

**Issue by sriraam-rs** [Remix-Design/RemixIcon#641]
## Icon Request

* Icon name: Kan-Ban view/card icon or Cards icon
* Tags of this icon: Kan-Ban view, Cards
* Use case: Used to select Kan-Ban view when the data is showed in Table view.
* Screenshots of similar icons:
![Kan-Ban line icon (custom)](https://github.com/Remix-Design/RemixIcon/assets/129825179/5146a920-9a82-4408-8bbf-c9d0353e9f58)
![Kan-Ban filled icon (custom)](https://github.com/Remix-Design/RemixIcon/assets/129825179/0190d0c7-eb0b-40c5-939a-360c58488773)

<img width="711" alt="Screenshot 2023-09-14 at 8 35 53 PM" src="https://github.com/Remix-Design/RemixIcon/assets/129825179/46fede3e-d3cd-4f21-b6e4-320d3165d25e">

**Comment by xiaochunjimmy** [comment]
We've added some view icon, including kanban/board view
<img width="885" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/246d81c3-9957-4b20-a168-7e3513a3a2d3">
https://remixicon.com/icon/kanban-view-2
https://remixicon.com/icon/kanban-view
