### ISSUE TITLE
Flip horizontal and vertical icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#650]
## Icon Request
* Tags of this icon: flip horizontal, flip vertical
* Screenshots of similar icons:
<img width="163" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/eaf5426d-643a-45c5-b4a0-63a216684db6">

<img width="121" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/cc469d52-2919-4fe6-9220-a46e71918cea">

**Comment by koebel** [comment]
we were also looking for this type of icon for flipping the preview of an image in our [web app](https://github.com/owncloud/web-app-dicom-viewer). I've modified your 'split-cells-horizontal' and 'split-cells-vertical' icon slightly to match our use case. This is how we imagine the UI to look like: 
![Screen Shot 2024-01-03 at 15 32 08](https://github.com/Remix-Design/RemixIcon/assets/8348693/98a1c81e-6e62-4b3e-9cd6-6b833cd5e3f7)

**Comment by xiaochunjimmy** [comment]
Hi @koebel, thank you for the PR.
But currently, we don't have a way to directly accept PRs. In our current release process, we pull icons directly from Figma through the API. I will discuss this issue with my colleagues @wendygaoyuan and figure out how to allow community members to contribute content in the future. For now, I might redraw the relevant icons myself. The icons you contributed are great, and I can use them as a reference for future updates.

**Comment by xiaochunjimmy** [comment]
<img width="547" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/bb5cb1b8-ded1-49ec-84e7-b438cd021047">

**Comment by iamrishishah** [comment]
@xiaochunjimmy request to add this version as well

![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/d5e8b393-7647-40f7-8e06-bd1f3565be74)
