### ISSUE TITLE
Indian Currency

### ISSUE THREAD

**Issue by jogigleaming** [Remix-Design/RemixIcon#652]
## Icon Request

* Icon name: 
* Tags of this icon: 
* Use case: 
* Screenshots of similar icons:

**Comment by dhruvabhat24** [comment]
**### @xiaochunjimmy** Can you assign it to me

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/money-rupee-circle-line
https://remixicon.com/icon/money-rupee-circle-fill
