### ISSUE TITLE
Icon Request: Twitch

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#66]
## Icon Request

* Icon name: twitch
* Tags of this icon: twitch
* Use case: Twitch is an online streaming platform for gamers, programmers etc.
* Screenshots of similar icons:
![Twitch Logo](https://user-images.githubusercontent.com/33750251/60287499-f541db00-9909-11e9-9600-467526a65c4f.png)

**Comment by xiaochunjimmy** [comment]
Here are the twitch icons. Sorry for a long time waiting.
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/twitch-line.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/twitch-fill.svg

**Comment by itsezc** [comment]
Thank you and no worries!
