### ISSUE TITLE
equaliser icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#663]
## Icon Request

require an equalizer icon design with 2 strokes, featuring both circular and rectangular options. The icon should be available in both horizontal and vertical formats.

* Icon name: equaliser icon
* Tags of this icon: equaliser icon, tune icon, settings, filter
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/1dae332b-342f-40a3-8aa8-34d056df3c4c)
<img width="121" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/082eb3df-7447-4a35-afe1-49ec6ed4dc45">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/equalizer-2-line
https://remixicon.com/icon/equalizer-3-line
