### ISSUE TITLE
Info Strikethrough icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#668]
## Icon Request

* Icon name: Info icon
* Tags of this icon: info off, info strikethrough icon 
* Use case: Designed an interface where users can switch between an informative view and a simple view. In an informative view, we want to display all information, obviously, and we need to add a switch option where users can easily switch between the info and non-information views.

**Comment by iamrishishah** [comment]
@xiaochunjimmy need this icon in urgent base if possible

**Comment by Dhruvabhat24** [comment]
Can you please assign it to me

**Comment by Dhruvabhat24** [comment]
I have raised the pull request can you review it

**Comment by Dhruvabhat24** [comment]
> ## Icon Request
> * Icon name: Info icon
> * Tags of this icon: info off, info strikethrough icon
> * Use case: Designed an interface where users can switch between an informative view and a simple view. In an informative view, we want to display all information, obviously, and we need to add a switch option where users can easily switch between the info and non-information views.

I have raised the pull request can you please review it

**Comment by xiaochunjimmy** [comment]
Hi @dhruvabhat24, Thank you for the PR. However, I think your design did not match his needs.

**Comment by dhruvabhat24** [comment]
> Hi @dhruvabhat24, Thank you for the PR. However, I think your design did not match his needs.

Well Thanks for the review I will try some other issues

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/information-off-line

**Comment by iamrishishah** [comment]
@xiaochunjimmy in the current icon the letter is somehow doesn’t look prominent. Letter i should be clear 

![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/b8e8ad74-21f9-4417-b371-f36282413036)
![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/60aecca4-d0dc-4525-8327-0b7231d42998)
