### ISSUE TITLE
Image Circle

### ISSUE THREAD

**Issue by augiethehuman** [Remix-Design/RemixIcon#671]
## Icon Request

* Icon name: Image Circle
* Tags of this icon: 
* Use case: Image uploading
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
Can you add more details to this issue? I still can't figure out what you need based on the information above.

**Comment by augiethehuman** [comment]
Here is an example: https://api.iconify.design/majesticons:image-circle.svg
