### ISSUE TITLE
File Stack

### ISSUE THREAD

**Issue by augiethehuman** [Remix-Design/RemixIcon#672]
## Icon Request

* Icon name: File Stack
* Tags of this icon: 
* Use case: File archive
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
Could you please provided a similar icon to this? It's difficult to determine what exactly it looks like based on this name.

**Comment by nico-frey** [comment]
> Could you please provided a similar icon to this? It's difficult to determine what exactly it looks like based on this name.

Not entirely sure, but I think he means something like this: 
<img width="372" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49398439/71770b39-5bc5-432c-98c9-a25076728af3">

(the first one fits the "archive" a little better)

**Comment by augiethehuman** [comment]
> > Could you please provided a similar icon to this? It's difficult to determine what exactly it looks like based on this name.
> 
> Not entirely sure, but I think he means something like this: <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/49398439/287829631-71770b39-5bc5-432c-98c9-a25076728af3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjMzNTIsIm5iZiI6MTcwMTcyMzA1MiwicGF0aCI6Ii80OTM5ODQzOS8yODc4Mjk2MzEtNzE3NzBiMzktNWJjNS00MzJjLTk4YzktYTI1MDc2NzI4YWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDIwNTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYjYwNzA2NzdiZGVkNWNhOGE4NTYyOWQxMDgzNGI0MTZhNzQwZWE4ZjdmNWY0ZDFhMDMyYTVmYjY4ZjY3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zL4SYPUceXARJ2xWH_XPn2tESA_1cG3jU1emK4FG94">
> 
> (the first one fits the "archive" a little better)

Correct, the one on the left. Here is another example: https://www.streamlinehq.com/icons/core-solid/interface-essential/contents/archive-document

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/archive-stack-line
https://remixicon.com/icon/archive-stack-fill
