### ISSUE TITLE
Flow direction icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#674]
## Icon Request

* Icon name: flow direction
* Tags of this icon: flow direction
* Use case: change the direction of flow from left to right or right to left and same icon style needed for top to bottom and bottom to top
* Screenshots of similar icons:
<img width="194" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/779b7163-e21c-4da4-b9f8-56bd60432b26">

**Comment by dhruvabhat24** [comment]
Hi @iamrishishah & @xiaochunjimmy 

Pull request has been raised for this issue 
Screenshot have attached.

**Comment by dhruvabhat24** [comment]
@xiaochunjimmy @iamrishishah can you please review them

**Comment by xiaochunjimmy** [comment]
Hi @dhruvabhat24, I've reviewed your PR and I think your icons are not what this Issue needed. Besides, there are also two problems with your design:
1. The arrow icons we've already have in our library.
2. The icon style did not match our style guide: 24px box size, 2px line weight

**Comment by dhruvabhat24** [comment]
Thank you for the review 
I will try once again

**Comment by xiaochunjimmy** [comment]
<img width="204" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/c69db9b2-2111-4628-a894-75885d39484d">
