### ISSUE TITLE
manual file download is not working.....icons display with cdn only ...

### ISSUE THREAD

**Issue by mrashidtufail** [Remix-Design/RemixIcon#679]
manual file download is not working.....icons display with cdn only 

i added file in the head tag by downloading it but it is not working.......it is only working with cdn

**Comment by xiaochunjimmy** [comment]
Can you please provide a detailed description of what manual file download refers to? What is the link for?

**Comment by mrashidtufail** [comment]
hi @xiaochunjimmy 
i am using this method
Download Manually
Download [remixicon.css](https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css) file, add it to the <head> tag of your html document. 
provided in readme file..... when i use this method icons are not showing ..... but when i use cdn link it works fine

**Comment by wendygaoyuan** [comment]
![CleanShot 2023-11-22 at 11 21 54@2x](https://github.com/Remix-Design/RemixIcon/assets/25056241/03450611-c29a-4a92-bd52-33f52017094d)
hi, Have you downloaded the font file of @font-face in css? If not, it will not work. You can open the console of the browser to check.

**Comment by mrashidtufail** [comment]
hey @wendygaoyuan could you please write the complete instruction step by step ...thank you in advance
