### ISSUE TITLE
Slideshow, Carousel, Stacked Icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#680]
Screenshots of similar icons:
<img width="469" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/527f4709-dae6-41c0-a322-8edf354204c1">

**Comment by xiaochunjimmy** [comment]
<img width="881" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/7e539e82-8ee6-403b-ae01-2737ed139e3f">
