### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by roberttran-cc** [Remix-Design/RemixIcon#681]
## Icon Request

* Icon name: ram
* Category: Device
* Tags of this icon: ram, memory, electronics, hardware
* Use case: when presenting hardware specifications
* Screenshots of similar icons: [examples on flaticon.com](https://www.flaticon.com/search?type=icon&search-group=all&word=ram&license=&color=&shape=&current_section=&author_id=&pack_id=&family_id=&style_id=&type=)

<img src="https://github.com/Remix-Design/RemixIcon/assets/102976382/89a04a99-9b97-4291-9587-2eea6f83880e" width="128" />

**Comment by nico-frey** [comment]
Good idea, adding some examples:

<img width="947" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49398439/b0b0c2d2-a6cb-419e-85d9-48daa3e1d770">

**Comment by xiaochunjimmy** [comment]
<img width="245" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/1f3551ea-7328-4a80-8edc-cbc8fcd0a906">

https://remixicon.com/icon/ram-line
https://remixicon.com/icon/ram-fill

**Comment by nico-frey** [comment]
Awesome @xiaochunjimmy !!!

**Comment by roberttran-cc** [comment]
Thank you very much @xiaochunjimmy: as usual, those icons look fantastic!

And thank you for all the hard work on the overall Remix Icon project: you and the Remix team are the real MVPs.

**Comment by hsablonniere** [comment]
:tada: Awesome!!!
