### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by danimt** [Remix-Design/RemixIcon#682]
## Icon Request

* Icon name: Ethereum
* Tags of this icon: crypto eth
* Use case: crypto
* Screenshots of similar icons:
<img width="87" alt="Screenshot 2023-11-22 at 14 22 31" src="https://github.com/Remix-Design/RemixIcon/assets/204050/d7506acc-b1e3-4caf-8516-8dc2ebe54538">

**Comment by danimt** [comment]
For my usecase specifically we only use Tezos and Ethereum.

So **Tezos** would be great too, if possible:
![Screenshot 2023-11-27 at 11 33 31](https://github.com/Remix-Design/RemixIcon/assets/204050/7716d701-4508-45ba-b145-06084c89514e)

And I guess **Bitcoin**:
![image](https://github.com/Remix-Design/RemixIcon/assets/204050/eb73c288-fd7a-472a-95ee-45124eea74f9)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/eth-fill
https://remixicon.com/icon/btc-fill
https://remixicon.com/icon/xtz-fill

We also added bnb and xrp icon
