### ISSUE TITLE
document or file

### ISSUE THREAD

**Issue by tahirjanovm** [Remix-Design/RemixIcon#684]
## Icon Request

* Icon name: document and file
* Tags of this icon: file_tick or which you want
* Use case: document and file
* Screenshots of similar icons: 
![document_submit_icon](https://github.com/Remix-Design/RemixIcon/assets/136474350/b4f44458-c207-493c-a953-56d5ef949cf8)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/file-check-line
<img width="204" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/219523f0-7b8a-4216-9978-a964ded97e2e">

**Comment by tahirjanovm** [comment]
Can you add 3 line bottom of the file? like i sent pic

**Comment by xiaochunjimmy** [comment]
We hope that this icon can be part of a set with other icons and have the same standards, so there should not be three lines added.

If  you need this, I think I can separately provide you the SVG file.
