### ISSUE TITLE
Text Snippet Icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#685]
## Icon Request

* Icon name: text snippet
* Tags of this icon: text snippet, text templates
* Screenshots of similar icons:
<img width="366" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/8783b384-1e9c-41d9-bc6b-9e8338271653">

**Comment by xiaochunjimmy** [comment]
<img width="298" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/532a6816-c600-4a21-b52d-589285c6d2cb">
https://remixicon.com/icon/text-block
https://remixicon.com/icon/text-snippet
