### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by NewMediaStudio** [Remix-Design/RemixIcon#686]
## Icon Request

* Icon name: Users
* Tags of this icon:  Multiple Users, User Group
* Use case: Identifying a group of users, defining permissions 
* Screenshots of similar icons:

![image](https://github.com/Remix-Design/RemixIcon/assets/15107444/7be458b3-3d79-4c9d-8604-3e24335813f5)

![image](https://github.com/Remix-Design/RemixIcon/assets/15107444/875af630-01c5-4b75-af19-63434b72876d)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/group-3-line
https://remixicon.com/icon/group-3-fill
