### ISSUE TITLE
eth-fill.svg has wrong size

### ISSUE THREAD

**Issue by cyberalien** [Remix-Design/RemixIcon#687]
**Describe the bug**
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Finance/eth-fill.svg has incorrect height of 25 instead of 24

**Comment by xiaochunjimmy** [comment]
Thank you for the reminder, we will fix this issue in the next version.

**Comment by xiaochunjimmy** [comment]
I've fixed this issue
