### ISSUE TITLE
Police Badge Icon

### ISSUE THREAD

**Issue by SMY19** [Remix-Design/RemixIcon#690]
## Icon Request

* Icon name: Police Badge
* Tags of this icon: police 
* Use case: 
* Screenshots of similar icons:

**Comment by SMY19** [comment]
![image](https://github.com/Remix-Design/RemixIcon/assets/147166837/ced9cce9-e581-4352-9be2-9b0f5ce04235)

**Comment by xiaochunjimmy** [comment]
Can this icon meet your needs?

https://remixicon.com/icon/shield-star-line

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/police-badge-line
https://remixicon.com/icon/police-badge-fill
