### ISSUE TITLE
Alibaba Cloud Icon

### ISSUE THREAD

**Issue by Qmlio** [Remix-Design/RemixIcon#691]
## Icon Request

* Icon name: Alibaba Cloud Icon
* Tags of this icon: Cloud Platforms
* Use case: Used when developing apps and websites that support alibaba cloud platform operations
* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/alibaba-cloud-line
https://remixicon.com/icon/alibaba-cloud-fill
