### ISSUE TITLE
Snowflake

### ISSUE THREAD

**Issue by ItsBranK** [Remix-Design/RemixIcon#692]
## Icon Request

* Icon name: Snowflake
* Tags of this icon: Snowflake, Snow, Flake, Cold, Winter, Frozen
* Use case: Alternative to the snow option in weather, as the snowflake under the cloud is small and harder to make out in smaller sizes. Could do different snow flake types too.
* Screenshots of similar icons:
* 
![zJ5nAyz](https://github.com/Remix-Design/RemixIcon/assets/23649425/fbc4d567-9155-4ddc-ac27-59509be34507)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/snowflake-fill

**Comment by ItsBranK** [comment]
Heck yeah, this is just what I needed; thanks!
