### ISSUE TITLE
Math formula icon

### ISSUE THREAD

**Issue by bogdancondorachi** [Remix-Design/RemixIcon#694]
## Icon Request

* Icon name: Square Root
* Tags of this icon: square-root, formula, math
* Use case: Defines use of a math formula in editor
* Screenshots of similar icons: 
![image](https://github.com/Remix-Design/RemixIcon/assets/39380741/f15b35fd-cc01-4e11-81f8-0038566e9951)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/formula
https://remixicon.com/icon/square-root

**Comment by xiaochunjimmy** [comment]
Hi @bogdancondorachi The icon you proposed has been completed and launched. Hope you like this project and Star our repo to support our efforts.
