### ISSUE TITLE
Missalignment in Bootstrap Navbar

### ISSUE THREAD

**Issue by AndiLeni** [Remix-Design/RemixIcon#70]
The icons are not aligned correctly when used inside of a bootstrap navbar.
Is there any solution known to fix this problem?

Regards
Andi 

Left icon: remixicon
Right icon: fontawesome
![Unbenannt](https://user-images.githubusercontent.com/13385771/60354887-95146d00-99cd-11e9-82de-d0f648f6d806.PNG)

**Comment by AndiLeni** [comment]
Furthermore, I noticed, that remixicons unfortunately do not play well with bootstrap at all.
I had to assign custom css manually to every icon which requires an enormous amount of work.

**Comment by ashfahan** [comment]
Hello @AndiLeni can u provide a minimal test case on codepen or other online editor.

i would like to look into the issue and submit a pull request if there is some way to solve it

**Comment by wendygaoyuan** [comment]
Hi, @AndiLeni 
Maybe this could be useful

``` css
.nav-link i {
  vertical-align: middle;
} 
```

**Comment by AndiLeni** [comment]
@wendygaoyuan this made it definitely better, but still not as opimal as I wished.

@ashfahan here is a simple jsfiddle with the tip from @wendygaoyuan already implemented:

https://jsfiddle.net/AndiLeni/v4bms6y8/3/

**Comment by ashfahan** [comment]
Hi , @wendygaoyuan  i tested the link. Even after an hour of struggle cant seem to find a proper fix for it. Maybe its related to font. something like font kerning or packing not sure though 

during testing i found vertical-align: text-top; to look better than middle.

**Comment by AndiLeni** [comment]
I used vertical-align: sub.
In my case this was the best solution.

**Comment by wendygaoyuan** [comment]
@AndiLeni  @ashfahan 
 I tested it and found two ways (https://codepen.io/wendygaoyuan/pen/WQZXwV)

1. `inline-flex` and `align-items`

```html
<a>
    <i class="remixicon-admin-fill"></i> Button
</a>
```
```css
a {
  display: inline-flex;
  align-items: center;
}
```

2. `inline-block` and `vertical-align` (Add HTML tags to text)
```html
<a>
    <i class="remixicon-admin-fill"></i> <span>Button</span>
</a>
```
```css
i[class^="remixicon"],
span {
  display: inline-block;
  vertical-align: middle;
}
```
But it seems to be on the low side as a whole

**Comment by ashfahan** [comment]
@wendygaoyuan The first way is nicer than the 2nd way because most front end developers use different fonts and because of font line-height it kinda hard to work with vertical align property .

@AndiLeni i suggest you use the flexbox vertical align rather than vertical align property.

**Comment by xiaochunjimmy** [comment]
This problem may be caused by the baseline of the font icon. After all, a font icon is a kind of typography, which has an attribute called baseline. 
We are trying to find a way to name the correct baseline of RemixIcon so that we can make the font icons look in the vertical center, but change baseline is a dangerous action which may cause style problems of the old version users who updated their RemixIcon fonts to the baseline-changed versions.

**Comment by ashfahan** [comment]
to fix the alignment the ground breaking changes needs to be done but yeah it will be a problem for old user. release major update for it ?

**Comment by xiaochunjimmy** [comment]
@ashfahan emmm, maybe v2.0.0 in the near future [happy]
