### ISSUE TITLE
scroll-to-bottom

### ISSUE THREAD

**Issue by pdesoyres-cc** [Remix-Design/RemixIcon#704]
## Icon Request

* Icon name: scroll-to-bottom
* Tags of this icon: arrow, scroll
* Use case: an icon-only button next to a scroll area, that lets users scroll to the bottom.
* Screenshots of similar icons:

![image](https://github.com/Remix-Design/RemixIcon/assets/104012218/1da759f4-8d2c-478b-b6bf-949c799ac180)

**Comment by xiaochunjimmy** [comment]
Hi there, we've added the `scroll-to-bottom` icon in the latest version.

Hope you could star our repo if you like it. This is very helpful for our enthusiasm for open source.
