### ISSUE TITLE
Defibrillator and its environment

### ISSUE THREAD

**Issue by DynamoRed** [Remix-Design/RemixIcon#705]
### AED
* Icon name: **aed** *(Category: Health & Medical)*
* Tags of this icon: defibrillator, aed
* Use case: In a medical equipment display frame, in the same idea as the icon of the stethoscope, thermometer or infrared thermometer
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/44113746/e799e3b3-ceba-4bb7-aa60-0c1d3be3f4e1)

---

## AED Electrodes
* Icon name: **aed-electrodes** *(Category: Health & Medical)*
* Tags of this icon: defibrillator, aed, electrodes
* Use case: In a medical equipment display frame, in the same idea as the icon of the stethoscope, thermometer or infrared thermometer
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/44113746/38ed1d2d-798c-4b11-ad3f-3fec8f532e57)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/aed-line

https://remixicon.com/icon/aed-electrodes-line
