### ISSUE TITLE
play  pause  stop ，这三个看起来比其他的图标小一圈，明明已经有mini了

### ISSUE THREAD

**Issue by ScarletDor** [Remix-Design/RemixIcon#706]
如题

**Comment by ScarletDor** [comment]
还有加减乘除那些符号也小一圈，现在同样宽度的图标放在一起不同一，看着很难受qaq

**Comment by xiaochunjimmy** [comment]
这些早起基于场景绘制的，当时结合 UI 来看，这样的尺寸会比较合理。比如 ⏩快进图标是两个播放图标，那一个播放图标确实会看起来小一些。如果在当前的使用中带来困惑，可以提场景和需求，我们觉得合理的话会跟进

**Comment by ScarletDor** [comment]
> 这些早起基于场景绘制的，当时结合 UI 来看，这样的尺寸会比较合理。比如 ⏩快进图标是两个播放图标，那一个播放图标确实会看起来小一些。如果在当前的使用中带来困惑，可以提场景和需求，我们觉得合理的话会跟进

remix图标库相对于其他图标库最大的优势我认为是图标尺寸的统一，开发者可以不用针对每个图标调整尺寸，播放器的这些图标确实和其他现有的图标尺寸不同，我感觉既然有mini图标了，标准尺寸的播放器图标可以统一调整。比如说快进是两个播放三角符号，参考emoji，▶️和⏩，可以很好的统一尺寸，而不是像现在这样简单的连到一起。

使用场景来说，我有一个菜单栏，上面有一些类似购物的那种图标，右侧有一个简易mp3播放器，但是播放器图标明显小，很难看。

最后，开发者大佬辛苦啦！！

**Comment by ScarletDor** [comment]
还有运算符号那些像加减乘除，我想用close图标来做关闭按钮，和其他的按钮放在一起也会显得很小。既然乘号的英文叫close，也没有第二个表示关闭的叉号close图标，那么close图标我认为应该和其他图标大小一致。

而且其他图标也会有这些问题，与其单独添加一个close图标表示关闭，不如调整现有的这些图标的尺寸，让他们和其他图标尺寸统一，我认为可以一举两得qaq

**Comment by xiaochunjimmy** [comment]
嗯.... 调整的话可能也会影响到之前已经在使用的用户，我想一下。

乘号和关闭拆分，是个不错的思路

**Comment by ScarletDor** [comment]
> 嗯.... 调整的话可能也会影响到之前已经在使用的用户，我想一下。
> 
> 乘号和关闭拆分，是个不错的思路

噗噗老哥辛苦啦！

还有播放器图标呜呜呜，不行单独加个-plus版qaq。我把play和play-list图标放一起真的差别好明显呜呜呜，手动修改图标大小的话就又会影响图标直接的间距了，呜呜呜太难了

**Comment by ScarletDor** [comment]
![2024-1-25 11-9-21](https://github.com/Remix-Design/RemixIcon/assets/12579360/bad00051-f0dc-453c-bb49-d727beef1d26)

这是同样大小的字体，图标放一起大小差别巨大

**Comment by xiaochunjimmy** [comment]
新增了大号尺寸的图标系列，在 Media 分类下可以看到

**Comment by xiaochunjimmy** [comment]
另外喜欢的话别忘了 Star 本项目哈

**Comment by ScarletDor** [comment]
爱你爱你！！点了点了！！
