### ISSUE TITLE
Icon Request: Copyright

### ISSUE THREAD

**Issue by zottelchin** [Remix-Design/RemixIcon#71]
## Icon Request

* Icon name: copyright
* Tags of this icon: copyright, legal, law
* Use case: mention author
* Screenshots of similar icons: &copy;

**Comment by xiaochunjimmy** [comment]
Here are the copyright icons, sorry for a long time waiting.
https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/copyright-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/copyright-line.svg

**Comment by zottelchin** [comment]
thanks, appreciate your work!
