### ISSUE TITLE
Improve Search Functionality

### ISSUE THREAD

**Issue by Abdulsaboor2004** [Remix-Design/RemixIcon#711]
Hi, 
The search bar doesn't work like it should. I mean, whenever I try searching for an icon and write half of its name, it doesn't appear (i.e., if you've to search for “Instagram / Facebook” you'll have to write entire spelling instead of insta / fb).

Also, if you search “Social Media”, nothing appears. You've to search for each platform, one by one.

I saw this problem and think it would be an improvement for remix icon. 

Thanks for listening to us.
> I 💖 Remix Icon.

![issue](https://github.com/Remix-Design/RemixIcon/assets/125990601/5c2bea29-e4a7-47d4-b430-829ce4fe5964)

**Comment by xiaochunjimmy** [comment]
Currently, we achieve the search function by manually maintaining search keywords. In the future, it may be possible to open it up for users to maintain keywords together.

I tried typing "insta" and was able to search for Instagram.

**Comment by Abdulsaboor2004** [comment]
Alright brother
