### ISSUE TITLE
为什么现在复制svg会自动添加fill属性呢？

### ISSUE THREAD

**Issue by ScarletDor** [Remix-Design/RemixIcon#712]
网站使用css来更改颜色，复制粘贴svg很方便，结果现在svg自动包含了fill，还得手动删除，之前明明都没有的qaq

**Comment by xiaochunjimmy** [comment]
是指增加了一个 fill=CurrentColor 属性吗？这个会影响从父级的 css 属性控制颜色吗？

**Comment by ScarletDor** [comment]
> 是指增加了一个 fill=CurrentColor 属性吗？这个会影响从父级的 css 属性控制颜色吗？

是的，现在颜色会默认为CurrentColor，影响css属性控制颜色

**Comment by wendygaoyuan** [comment]
svg 添加 currentColor 时可以继承元素的文本颜色或父类的颜色，能更方便的动态修改图标去适配不同主题。
但网站上的 copy 把 currentColor 加到了 path 上，改到 svg 上会更好些。
目前网站已经修改。

**Comment by ScarletDor** [comment]
好多了，很感谢！
