### ISSUE TITLE
Media: Reverse, Fast Forward to End, Fast Reverse to Start

### ISSUE THREAD

**Issue by oscargus** [Remix-Design/RemixIcon#715]
## Icon Request

Naming can be discussed, but in some applications one would like the fast forward/rewind buttons ending with a bar. Similarly, a "reverse" button, i.e., a mirrored play button is useful. There are suitable Unicode code points for all of them:
https://www.compart.com/en/unicode/U+23ED
https://www.compart.com/en/unicode/U+23EE
https://www.compart.com/en/unicode/U+23F4

Maybe one should also add mini versions, although for my use, the standard sizes are enough.

* Icon name: reverse, rewind-to-start, forward-to-end? 
* Tags of this icon: Media
* Use case: Going to start or end, playing backwards
* Screenshots of similar icons: ⏴⏭⏮

Since these should be quite simple to obtain from the existing ones, I can provide a PR (for the icons, not sure how to build the font) if you think that they are worthwhile to add.

**Comment by xiaochunjimmy** [comment]
But our current update process does not yet support PR (pushing directly from Figma to GitHub via API), so there is currently no way to merge your PR, sorry

**Comment by xiaochunjimmy** [comment]
We've added the icons you need. Please check it in the latest version.

Hope you could star our repo if you like it. This is very helpful for our enthusiasm for open source.

**Comment by oscargus** [comment]
Thanks! Great!

I'll try to add rust bindings to this font (to make it easier to use in rust) and then use them in https://surfer-project.org/

**Comment by oscargus** [comment]
Ahh, seems like there are actively maintained bindings already: https://docs.rs/egui-remixicon/latest/egui_remixicon/ (just in case someone is interested).
