### ISSUE TITLE
weight / heavy / kilo icon

### ISSUE THREAD

**Issue by EliotSlevin** [Remix-Design/RemixIcon#718]
## Icon Request

* Icon name: Weight
* Tags of this icon: weight, heavy, dense, kilo, pound, gram, large
* Use case: There isn't really any icon to represent the concept of a weight. Or something being heavy. A weight icon could be used to both represent weight measurements (e.g. for shipping inputs), or that something is heavy, or maybe even large. 
* Screenshots of similar icons:

![Screenshot 2024-01-15 at 1 36 32 PM](https://github.com/Remix-Design/RemixIcon/assets/4987326/2eefdb84-ea9b-45f0-8309-6ff50b2bb0a0)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/weight-fill

**Comment by xiaochunjimmy** [comment]
@EliotSlevin Hope you like this project and Star our repo to support our efforts.

**Comment by EliotSlevin** [comment]
Amazing! No I love remixicon, we use it exclusively through a product I work on, stedi.com
