### ISSUE TITLE
Icon(s) Request: Travel Icons

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#72]
## Icon Request

* Icon name: plane, car
* Tags of this icon: plane, car
* Use case: Travel icons for modes of transportation
* Screenshots of similar icons:

![Plane](https://user-images.githubusercontent.com/33750251/61346204-b5f31400-a84f-11e9-8ecd-7299303a19ef.png)

![Car](https://user-images.githubusercontent.com/33750251/61346233-d327e280-a84f-11e9-87a7-b39bf170aeb3.png)

**Comment by xiaochunjimmy** [comment]
Travel icons for modes of transportation have been added to the `[Map](https://remixicon.com/#map)` category.

We are very Appreciate for your donation days ago. It will greatly encourage us to move on.

**Comment by itsezc** [comment]
Perfect, thank you!
