### ISSUE TITLE
Kebab Icon Request

### ISSUE THREAD

**Issue by vagabondachi** [Remix-Design/RemixIcon#722]
## Icon Request

* Icon name: Kebab menu
* Tags of this icon: #kebabmenu
* Use case: Kebab menu is a vertical three-dot shape used for overflow menu, or external navigation. 
* Screenshots of similar icons: 
![image](https://github.com/Remix-Design/RemixIcon/assets/88590758/9add1fe9-f93d-4c7f-8b3e-452a8388a2ad)

**Comment by iamrishishah** [comment]
It's already there
https://remixicon.com/icon/more-2-fill

@xiaochunjimmy I think you need add "Kebab menu" as tag to improve the search
