### ISSUE TITLE
希望新增公式图标

### ISSUE THREAD

**Issue by svipchao** [Remix-Design/RemixIcon#723]
示例
https://yesicon.app/pajamas/formula

**Comment by xiaochunjimmy** [comment]
感谢建议，暂时也可以先用这两款图标顶一下，下个版本会更新你需要的款式
https://remixicon.com/icon/functions
https://remixicon.com/icon/subscript

**Comment by xiaochunjimmy** [comment]
新增了：
公式图标：https://remixicon.com/icon/formula
开根号图标：https://remixicon.com/icon/square-root
