### ISSUE TITLE
Mobile download icon request

### ISSUE THREAD

**Issue by slavcosergi** [Remix-Design/RemixIcon#725]
## Icon Request

* Icon name: Mobile Download
* Tags of this icon: mobile, download, phone, arrow
* Use case: Download application for mobile
* Screenshots of similar icons:
![mobile-download](https://github.com/Remix-Design/RemixIcon/assets/10498246/d8856983-a235-4893-84a2-12c1e3efd57e)

**Comment by iamrishishah** [comment]
Desktop download 
<img width="36" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/49694573/7d3e075d-e0e7-4fab-a781-c39ca4310c76">

**Comment by xiaochunjimmy** [comment]
@slavcosergi The icon you proposed has been completed and launched. 
Hope you like this project and Star our repo to support our efforts.

https://remixicon.com/icon/mobile-download-line
