### ISSUE TITLE
Icon request: <item alignment>

### ISSUE THREAD

**Issue by rwenzel22** [Remix-Design/RemixIcon#728]
## Icon Request

* Icon name: 

1. align-item-left
2. align-item-center
3. align-item-left

* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/93221078/935f3c31-7699-46b4-9ee8-2fd4acbcdd80)

Thank you, from Brazil.

**Comment by xiaochunjimmy** [comment]
Hi @rwenzel22 The icon you proposed has been completed and launched!

Hope you like this project and Star our repo to support our efforts.

<img width="882" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/ece8c096-90d0-495b-9b23-3f533a4bfaf2">

**Comment by rwenzel22** [comment]
Thanks @xiaochunjimmy .
