### ISSUE TITLE
Tooth Icon 

### ISSUE THREAD

**Issue by nikkisingh0204** [Remix-Design/RemixIcon#729]
## Icon Request

* Icon name: Tooth
* Tags of this icon: tooth, teeth
* Use case: Designing of dentist related stuffs
* Screenshots of similar icons:
<img width="446" alt="Screenshot 2024-02-02 at 2 18 26 AM" src="https://github.com/Remix-Design/RemixIcon/assets/44700984/c2d31303-6d2f-4486-b738-c6a951c70082">

**Comment by xiaochunjimmy** [comment]
Hi @nikkisingh0204 The icon you proposed has been completed and launched. 

Hope you like this project and Star our repo to support our efforts.

https://remixicon.com/icon/tooth-line
https://remixicon.com/icon/tooth-fill

**Comment by nikkisingh0204** [comment]
Thanks @xiaochunjimmy 🙂
