### ISSUE TITLE
Size and color section option when I download the icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#73]
**There should be popup appear when I download the icon.**

1. Selecting file format - png and svg
2. Size selection - 16px, 24px, 32px, 64px, 128px
3. Color picker - default color pallet with hex code option
4. Add to collection (Future request)

**Inspiration**

![image](https://user-images.githubusercontent.com/49694573/61576616-bf070e00-aaf9-11e9-838f-43da31d3e0f6.png)

**Comment by xiaochunjimmy** [comment]
Hi, Rrishishah, your requestions were already in our dev plan, all the UI design has been finished, but the codes still need time (God bless Weny). You may see these features in the version 2.0. (cool smile)

**Comment by xiaochunjimmy** [comment]
We've launched v2.0.0 of our website. You can find the new features you need easily from the new website. 
[www.remixicon.com](https://remixicon.com)
Sorry for a 2-month waiting (we've been busy in our work in the past months and we can only spare little time to maintain Remixicon).
