### ISSUE TITLE
Driver's license / ID card

### ISSUE THREAD

**Issue by evadecker** [Remix-Design/RemixIcon#730]
## Icon Request

* Icon name: Driver's license / ID card
* Tags of this icon: card, identity, user, license, badge
* Use case: My personal use case is building an app which guides users through the legal name change process (including State ID) but I could imagine this also being used for applications which request a user's State ID to confirm their identity, or alternatively to be used as a "badge" or "keycard" icon for access controls. There are no user card icons in the library currently; the closest thing is the credit card icon.
* Screenshots of similar icons:

<img width="435" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/4117920/1f35d654-7644-4b92-beff-61e9c3a0ff16">

Attached is an SVG I created by altering the aspect ratio of the existing credit card icon and adding the small user outline used in the `shield-user` icon.

[id-card.svg](https://github.com/Remix-Design/RemixIcon/assets/4117920/855b9ec0-faf0-492b-aee7-e4afc787b0c3)

**Comment by xiaochunjimmy** [comment]
Thank you for your contribution. I will add this icon in the upcoming update.

**Comment by evadecker** [comment]
> Thank you for your contribution. I will add this icon in the upcoming update.

Fantastic! Thank you!

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/id-card-line
https://remixicon.com/icon/id-card-fill

Your icon is online, I made a little adjustment.

**Comment by evadecker** [comment]
Looks great, thank you!
