### ISSUE TITLE
Expand icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#732]
## Icon Request

* Icon name: expand
* Tags of this icon: expand, two opposite arrows
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/49694573/111a3cd5-70b4-4288-b453-b3c7ec52f62f)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/expand-diagonal-line
https://remixicon.com/icon/expand-diagonal-2-line
