### ISSUE TITLE
Expanded variant of gallery-view

### ISSUE THREAD

**Issue by jiu-virgil** [Remix-Design/RemixIcon#733]
Icon name: gallery-view-expanded
Tags of this icon: (existing gallery-view tags), expand, expanded, small
Use case: 
![image](https://github.com/Remix-Design/RemixIcon/assets/68442514/6fe9ee2c-d20c-4a44-9200-26ee5b7885f7)
Expanded view of an image gallery, grid of posts, etc.

Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/68442514/920fc199-44dd-457a-b2eb-68f240642f37)

**Comment by xiaochunjimmy** [comment]
You mean you need a gallery icon with 9 cells?

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/layout-grid-2-line

**Comment by xiaochunjimmy** [comment]
Hi @jiu-virgil 
The icon you proposed has been completed and launched. Hope you like this project and Star our repo to support our efforts.
