### ISSUE TITLE
Dashbord with class name and hex code

### ISSUE THREAD

**Issue by m0ntelo** [Remix-Design/RemixIcon#75]
Trying to use RemixIcon in a project is difficult to use because it does not have a panel accessible with the hex codes and class names to copy/paste.

**Comment by Uranbold** [comment]
Check this https://github.com/Remix-Design/RemixIcon/issues/63

**Comment by xiaochunjimmy** [comment]
We've already worked on this.
Thank you for your feedback.

**Comment by xiaochunjimmy** [comment]
We've launched the v2.0.0 website. You can copy and paste the class names in a simple way and you can also change the icon color and size.

But can not copy Unicodes for now. There's some technical challenge of this feature. Does this feature necessary for users?

**Comment by m0ntelo** [comment]
@xiaochunjimmy In mobile applications such as xamarim the icons are called by hex code. in the project i'm running a team needs a lib that works both on web and mobile.
