### ISSUE TITLE
java的line和fill类型是不是反了?

### ISSUE THREAD

**Issue by stars-one** [Remix-Design/RemixIcon#758]
如下图所示,应该是fill的类型那个才是加粗吧?

![image](https://github.com/Remix-Design/RemixIcon/assets/31400169/43c93978-6bab-43bd-a232-855c18306605)

**Comment by xiaochunjimmy** [comment]
其实没反，对于 logo 这个分类，后来对 fill 的定义是使用原始 logo，而 line 是 Remix Icon 风格的线性图标。
Java 的原始 logo 确实是太细了

**Comment by stars-one** [comment]
好的
