### ISSUE TITLE
希望加一个复制svg的功能

### ISSUE THREAD

**Issue by 95junminhuang** [Remix-Design/RemixIcon#76]
**Is your feature request about our website? Please describe.**

**Is your feature request about the Usage? Please describe.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by xiaochunjimmy** [comment]
感谢建议，本功能已在 2.0 版本的计划中，目前正处于开发阶段，大概不久可以上线。

**Comment by xiaochunjimmy** [comment]
兄台可以去官网看下，已经上线了~
