### ISSUE TITLE
Tailwind Css

### ISSUE THREAD

**Issue by Mr-Code-Rajesh** [Remix-Design/RemixIcon#768]
## Icon Request

* Icon name:  Tailwind css
* Tags of this icon:  &#xF517;
* Use case: 
* Screenshots of similar icons: <i class="ri-tailwind-css-fill"></i>

**Comment by xiaochunjimmy** [comment]
We have this icon, but it seems you didn't find it. May I ask what keywords you searched for?

https://remixicon.com/icon/tailwind-css-fill
https://remixicon.com/icon/tailwind-css-line
