### ISSUE TITLE
Can not search with Chinese after translated with Google Chrome translator

### ISSUE THREAD

**Issue by xiaochunjimmy** [Remix-Design/RemixIcon#77]
**Describe the bug**
在Chrome浏览器将网站自动翻译为中文后，在搜索框中输入搜索关键词，筛选出结果后，删除关键词，重新输入关键词，关键词将不再生效，无法筛选出结果。

**Additional context**
参考issue：
https://github.com/vuejs/vue/issues/9160

**Comment by ineo6** [comment]
Today I found this bug.

You can try:

```html
<html lang="en" translate="no">
```

[MDN Doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate)

And fallback which should work for Edge and Chrome:

```html
<meta name="google" content="notranslate">
```
