### ISSUE TITLE
Icon Request: Xing

### ISSUE THREAD

**Issue by medialwerk** [Remix-Design/RemixIcon#78]
## Icon Request

* Icon name: Xing
* Tags of this icon: xing
* Use case: Same as the LinkedIn icons
* Screenshots of similar icons:
<img width="617" alt="xing icons" src="https://user-images.githubusercontent.com/738512/63509819-64d4e080-c4dd-11e9-98cc-a38868b5feaa.png">

**Comment by xiaochunjimmy** [comment]
Here's the `Xing` icon. ^_^
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Logos/xing-fill.svg

**Comment by medialwerk** [comment]
Yeay, thank you very much for this icon! :-)
