### ISSUE TITLE
Status/Progress Icons

### ISSUE THREAD

**Issue by augiethehuman** [Remix-Design/RemixIcon#788]
## Icon Request

* Icon name: Status/Progress Icons
* Tags of this icon: Circle, Status, Progress, Steps
* Use case: Used to show progress step by step.
* Screenshots of similar icons:
![CleanShot 2024-04-01 at 19 54 50@2x](https://github.com/Remix-Design/RemixIcon/assets/125620554/2e04f462-c1ac-4591-aa0d-bd19e24a4057)
![CleanShot 2024-04-01 at 19 54 45@2x](https://github.com/Remix-Design/RemixIcon/assets/125620554/a5e25b90-b92c-48c9-8c3e-2da083919be9)

**Comment by xiaochunjimmy** [comment]
We've already got some status/progress icons:
<img width="800" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/6701827/bf3f9998-4c32-4618-9ddf-b5438f820734">

**Comment by augiethehuman** [comment]
Oh my apologies. I must have put in an extra letter and they didn't know. The dashed version would still be greatly appreciated as it shows a "pending" progress.
