### ISSUE TITLE
Ideas for icons

### ISSUE THREAD

**Issue by Tactrus** [Remix-Design/RemixIcon#79]
Here are some icons I think would be nice to include if you get the chance
- [Binoculars](https://fontawesome.com/icons/binoculars?style=solid) (Search)
- Telescope (Search)
- [Gavel](https://fontawesome.com/icons/gavel?style=solid) (Moderation)
- [Verified badge](https://fontawesome.com/icons/badge-check?style=solid)
- [Ban](https://fontawesome.com/icons/ban?style=solid)
- [Cake](https://fontawesome.com/icons/birthday-cake?style=solid) (Birthdays/Important Dates)
- [Lightning Bolt](https://fontawesome.com/icons/bolt?style=solid)
- [Bullhorn](https://fontawesome.com/icons/bullhorn?style=solid) (Announcements)
- [Comment Slash](https://fontawesome.com/icons/comment-alt-slash?style=solid) (Empty comments)
- [External Link](https://fontawesome.com/icons/external-link?style=solid)
- [Gem](https://fontawesome.com/icons/gem?style=solid)
- [Gift](https://fontawesome.com/icons/gift?style=solid)

**Comment by xiaochunjimmy** [comment]
Thank you so much for your advice. We'll consider adding some of them in the next icon version.

**Comment by xiaochunjimmy** [comment]
Only a part of them has been finished for now.

**Comment by Tactrus** [comment]
Hi, the new icons look fantastic. Thank you for adding them, awaiting the rest 👍 

I'll reiterate the necessity of removing/fixing the spacing problem. Here are these icons as compared to font awesome (FA top, RI bottom) The icons float to the top left rather than centering themselves like font awesome. I think by fixing this problem it will bring these icons to a whole new level. On par with font awesome, and I'll be able to switch to these icons.

**Comment by hyedyhyedy** [comment]
Hi,

I hope there is an icon for a birthday, too! I think It could be a cake, a candle or a present. 
It'll be in user's profile. Thanks! 
https://www.flaticon.com/search/2?word=birthday
<img width="1003" alt="Screen Shot 2019-11-18 at 13 20 12" src="https://user-images.githubusercontent.com/36624358/69052251-e538ae00-0a06-11ea-9fad-fcbaca6e280f.png">

**Comment by xiaochunjimmy** [comment]
@hyedyhyedy You can search cake or gift on our website to find your icons~

**Comment by xiaochunjimmy** [comment]
@Tactrus Sorry the space problem still not fixed.
