### ISSUE TITLE
IA icon

### ISSUE THREAD

**Issue by alckordev** [Remix-Design/RemixIcon#799]
## Icon Request

Icon name: ia
Tags of this icon: Others
Use case: Like icon for any button or text
Screenshots of similar icons:

![image](https://github.com/Remix-Design/RemixIcon/assets/16854024/f4e16a5e-371a-462e-acfa-e7faad9bddb2)

**Comment by xiaochunjimmy** [comment]
Is this what you need?
https://remixicon.com/icon/sparkling-fill
https://remixicon.com/icon/sparkling-2-fill

**Comment by alckordev** [comment]
> Is this what you need? https://remixicon.com/icon/sparkling-fill https://remixicon.com/icon/sparkling-2-fill

Yes thanks!
