### ISSUE TITLE
.remixicon-file-ppt-line 2:before, error?

### ISSUE THREAD

**Issue by NEOTSO** [Remix-Design/remixicon#8]
```
.remixicon-file-ppt-line 2:before
```
is it should be
```
.remixicon-file-ppt-line:before
```
syntax error in wechat mini_program :D

**Comment by Moonsic** [comment]
`https://remixicon.com/fonts/remixicon.css` 里的第530行
```
.remixicon-file-ppt-line 2:before { content: "\f133"; }
```
中的`2`前面有个空格报了错，527行至531行一种有5个ppt的图标，官网上搜到只有4个，貌似第530行应该不存在。

**Comment by xiaochunjimmy** [comment]
感谢 @Moonsic 的反馈，帮我们指出了一个疏漏。
确实是多了一个带空格的图标，目前在v1.1.1版本中进行了删除修正；
另外，您在回复中提到的CDN的这个CSS地址已经不再更新维护了，目前最新的地址为：
```
http://cdn.remixicon.com/releases/v1.1.1/remixicon.css
```
地址中的`v1.1.1`是图标版本号，后期会随着图标的拓展更新（非官网导航栏logo后面的网站版本号），
README.MD中的地址也调整更新了~多谢~
