### ISSUE TITLE
Icon request: telephone number

### ISSUE THREAD

**Issue by NMTuan** [Remix-Design/RemixIcon#80]
希望增加电话键盘相关图标, 
1 2 3 4 5 6 7 8 9 0 * # 

另外, 还希望增加一个拖拽的图标,(一列4个点, 共两列)

**Comment by xiaochunjimmy** [comment]
电话键盘是指每个数字做一个图标吗？

**Comment by NMTuan** [comment]
是的, 虽然可以直接用数字*#完成, 但有时候数字和图标混排的时候, 统一效果还是蛮麻烦的. 所以希望直接出一套图标, 0-9 * # 12个

**Comment by xiaochunjimmy** [comment]
这个最终的使用场景就是用于拨号界面或者计算器界面之类的吗？

**Comment by NMTuan** [comment]
除了拨号界面, 计算器之类完整的界面组件外, 在通信行业里, 可能会用得更多.
比如, 可以为每个按键(按键组合)指定功能,常见与10086查话费之类的 .
这时候展示的可能就是一个按键(按键组合)列表.

也可以用与展示手机/固话号码, 邮编, 等等信息.
也可能用在rank排行列表,

**Comment by xiaochunjimmy** [comment]
数字图标已经完成更新。
拖拽图标还没有。
https://remixicon.com/#editor

**Comment by xiaochunjimmy** [comment]
数字的整体字形结构借鉴了MIUI的拨号界面，但细节有所不同，相比MIUI的“非衬线字体”数字字形，本套数字的字形更偏向于“图标”，字形的整体粗细比较均匀，虽然没有MIUI的字体耐看，但比较适合图标场景，像素对齐更友好，界面呈现更清晰。
