### ISSUE TITLE
Book Shelf  Icon

### ISSUE THREAD

**Issue by Qmlio** [Remix-Design/RemixIcon#807]
## Icon Request

* Icon name:  Book Shelf
* Tags of this icon:  Will be used when designing a books library 
* Use case: Indicate a books library, categories of books
* Screenshots of similar icons: don't have anything.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/book-shelf-line

**Comment by xiaochunjimmy** [comment]
The icon you recommended has been launched. Don't forget to star our repo if you like our project.
