### ISSUE TITLE
Stairs Icon

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#808]
Icon name: Stair Icons
Tags of this icon: Will be used to represent something that will be like stages or level
Use case: Indicate a progressive in tab menu
Screenshots of similar icons: https://game-icons.net/1x1/delapouite/stairs.html

**Comment by xiaochunjimmy** [comment]
The icon you recommended has been launched. Don't forget to star our repo if you like our project.

https://remixicon.com/icon/stairs-line
https://remixicon.com/icon/stairs-fill
