### ISSUE TITLE
Note with pen

### ISSUE THREAD

**Issue by Tiesco789** [Remix-Design/RemixIcon#809]
* Icon name: Note and pen
* Tags of this icon: create note or notation with pen
* Use case: will represent a note with a pen, like sign a paper and etc
* Screenshots of similar icons: https://game-icons.net/1x1/delapouite/notebook.html

**Comment by xiaochunjimmy** [comment]
Can this icon meet your needs?

https://remixicon.com/icon/draft-line

**Comment by Tiesco789** [comment]
yes, sure
