### ISSUE TITLE
Icon Bundler

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#81]
It would be really nice to pick and choose to create your own bundle optimized for a your application and I believe something similar to http://fontello.com would be epic.

It allows the user to select all of the icons they need and to generate an output file, this is especially useful when using the webfont approach.

**Comment by xiaochunjimmy** [comment]
User can pick and choose icons they like and generate a smaller font-icon pack on our website now. This is a new feature of v2.0.0.
If you have any trouble in using this new feature, please tell us the problems you met.

**Comment by itsezc** [comment]
Sorry I wasn't clear enough, I would like the ability to select all and then deselect the ones I do not like as it would take a lot longer selecting each one individually

**Comment by xiaochunjimmy** [comment]
We'll think about it, but most users only use a few icons of all, so we only allow users to select and add rather than select all.

This is the tool we use to generate icon fonts, maybe can solve your problems.
https://github.com/nfroidure/svgicons2svgfont
