### ISSUE TITLE
Telegram without box Icon

### ISSUE THREAD

**Issue by NeoxAzrot** [Remix-Design/RemixIcon#810]
## Icon Request

* Icon name: **telegram** (need to rename the old one as **telegram-box** for instance)
* Tags of this icon: **Logos**
* Use case: Use the Telegram logo **without the box around it**, to **maintain consistency** between the logos used.
* Screenshots of similar icons:

| Description        | Image                                                                                       |
|--------------------|---------------------------------------------------------------------------------------------|
| Similar Icon       | ![Similar Icon](https://github.com/Remix-Design/RemixIcon/assets/56161244/bbaf8fe6-bf9f-47e1-ada8-5b585bfeae77) |
| Actual Icon        | ![Actual Icon](https://github.com/Remix-Design/RemixIcon/assets/56161244/cc892ae4-527f-448f-9cc1-84c44edc559c)  |
| Other Logo Icons   | ![Other Logo Icons](https://github.com/Remix-Design/RemixIcon/assets/56161244/d0bedf5b-4002-4af9-bf1b-b9e74e3ae6f3) |

**Comment by xiaochunjimmy** [comment]
The icon you recommended has been launched. Don't forget to star our repo if you like our project.

https://remixicon.com/icon/telegram-2-line
https://remixicon.com/icon/telegram-2-fill
