### ISSUE TITLE
Restore/Reset Icon

### ISSUE THREAD

**Issue by JARVIS712** [Remix-Design/RemixIcon#814]
## Icon Request

* Icon name: Restore/reset
* Tags of this icon: reset to default value in a field
* Use case: when we edit a default message and go back to the default message we need a restore/reset icon
* Screenshots of similar icons: 
![image (1)](https://github.com/Remix-Design/RemixIcon/assets/47685542/7dac75bb-abf7-44e8-b172-c1ee95f5a755)

**Comment by xiaochunjimmy** [comment]
The icon you recommended has been launched. Don't forget to star our repo if you like our project.

https://remixicon.com/icon/reset-left-line
https://remixicon.com/icon/reset-left-fill
https://remixicon.com/icon/reset-right-line
https://remixicon.com/icon/reset-right-fill
