### ISSUE TITLE
The link is too fat, you can create a slimmer one

### ISSUE THREAD

**Issue by ken678** [Remix-Design/RemixIcon#815]
The link is too fat, you can create a slimmer one
![image](https://github.com/Remix-Design/RemixIcon/assets/15792472/e310c6aa-2c2d-4a69-9bd3-f51d9858e334)
Similar to the following
![image](https://github.com/Remix-Design/RemixIcon/assets/15792472/34393c1e-8d7b-4880-82b6-3f74cbb125a3)

**Comment by xiaochunjimmy** [comment]
这款可以满足需求吗？
https://remixicon.com/icon/link
