### ISSUE TITLE
Horizontal and Vertical

### ISSUE THREAD

**Issue by ken678** [Remix-Design/RemixIcon#816]
![image](https://github.com/Remix-Design/RemixIcon/assets/15792472/22fd1bc1-5415-46d8-bd04-4955a6d62e92)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/expand-horizontal-s-fill
https://remixicon.com/icon/expand-vertical-s-fill

The icon you recommended has been launched. Don't forget to star our repo if you like our project.
