### ISSUE TITLE
Eye Dropper Icon

### ISSUE THREAD

**Issue by yogaaltariz** [Remix-Design/RemixIcon#821]
## Icon Request

* Icon name: eyedropper
* Tags of this icon: eyedropper, color picker, color dropper
* Use case: The eyedropper icon is commonly used in digital design and editing applications, for example is palette creation, color contrast checker, color picker, etc.
* Screenshots of similar icons:
<img width="679" alt="image" src="https://github.com/Remix-Design/RemixIcon/assets/43367856/3b1a9da7-09fd-4eb7-83ac-a4c845084ccb">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/dropper-line
https://remixicon.com/icon/dropper-fill
The icon you recommended has been launched. Don't forget to star our repo if you like our project.

**Comment by yogaaltariz** [comment]
Cool, thanks for the update.
