### ISSUE TITLE
[Request] DNA icon

### ISSUE THREAD

**Issue by davidendico-owkin** [Remix-Design/RemixIcon#825]
## Icon Request

* Icon name: DNA
* Tags of this icon: health, medical, people, DNA, gene
* Use case: Used for any DNA people-related or health research content
* Screenshots of similar icons:
![image](https://github.com/Remix-Design/RemixIcon/assets/88389120/34b6d84d-0563-4853-8b37-5fa5927f8e1c)

And thanks for the amazing work you've done with that library! 💪

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/dna-line
https://remixicon.com/icon/dna-fill

The icon you recommended has been launched. Don't forget to star our repo if you like our project.
