### ISSUE TITLE
Icon Request: Translate Icon

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#83]
## Icon Request

* Icon name: translate
* Tags of this icon: translate
* Use case: Used to distinguish a change of locale
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/64987782-d6783280-d8c1-11e9-9cfc-9e0e9af81036.png)

![image](https://user-images.githubusercontent.com/33750251/64987819-ea239900-d8c1-11e9-9bab-447dd0aadb6c.png)

![image](https://user-images.githubusercontent.com/33750251/64987842-fc053c00-d8c1-11e9-8a93-64bc5d745ba3.png)

**Comment by xiaochunjimmy** [comment]
The issues with [in progress] tags means I have finished the design part.
They will be published in a short time.

**Comment by xiaochunjimmy** [comment]
I've finished the design of them. Have a look at them from our [website v2.1.0](https://remixicon.com/#editor).
