### ISSUE TITLE
[icon] User minus

### ISSUE THREAD

**Issue by VictorUvarov** [Remix-Design/RemixIcon#832]
You have a user add icon but no user minus icon.

<img width="162" alt="Screenshot 2024-06-07 at 7 58 52 AM" src="https://github.com/Remix-Design/RemixIcon/assets/35702719/3d174764-d2c3-40aa-ba4b-65cbed6dc3ca">

I wanted to use user minus as an unfollow icon, and the current unfollow icon feels like a user block icon.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/user-minus-line
https://remixicon.com/icon/user-minus-fill

The icon you recommended has been launched. Don't forget to star our repo if you like our project.
