### ISSUE TITLE
Icon Request: Stackshare

### ISSUE THREAD

**Issue by itsezc** [Remix-Design/RemixIcon#87]
## Icon Request

* Icon name: stackshare
* Tags of this icon: stackshare
* Use case: Stackshare has risen in popularity as a service to document your app's stack
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/33750251/65176143-1834e480-da4c-11e9-953f-b78fb3e31767.png)

Large companies all the way from Google to Uber use this service and it would be nice to see an icon for it, if the requested icons are too many I am able to help either by contributing via Pull Requests or monetarily whichever you prefer.

**Comment by xiaochunjimmy** [comment]
I will make a design guide for RemixIcon so that designers can build this product together with us.

**Comment by xiaochunjimmy** [comment]
Here are your icons.
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Development/share-stack-line.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Development/share-stack-fill.svg
You can also find them from our [website v2.1.0](https://remixicon.com/#development)

**Comment by itsezc** [comment]
This is great, however one small issue, the name is labelled in reverse it should be named stackshare or stack-share if you would like

**Comment by xiaochunjimmy** [comment]
(⊙o⊙)…
I'll fix it in the next version.
