### ISSUE TITLE
Icon Request: Fingerprint

### ISSUE THREAD

**Issue by Rijk** [Remix-Design/RemixIcon#89]
## Icon Request

* Icon name: Fingerprint
* Tags of this icon: fingerprint, password, identity, verification, touch-id
* Use case: See tags ;)
* Screenshots of similar icons: Really like this one [in Fontawesome](https://fontawesome.com/icons/fingerprint?style=regular).

<img width="200" alt="image" src="https://user-images.githubusercontent.com/159500/65815214-dd217680-e1ec-11e9-8696-8eb512b524e7.png">

**Comment by xiaochunjimmy** [comment]
You can type the search keyword `finger` from our website to find them. I've designed 2 styles of fingerprint icons. They cost me hours, maybe the most difficult icons of Remix-Icon.

**Comment by Rijk** [comment]
Ah, sorry about the difficulty! Really well done. :)

**Comment by xiaochunjimmy** [comment]
It doesn't matter.
The usage rate of fingerprint icons should be high.
Other users may need them, too.
Thank you for your suggestion.
