### ISSUE TITLE
Fediverse Icon

### ISSUE THREAD

**Issue by timotheegoguely** [Remix-Design/RemixIcon#890]
## Icon Request

* Icon name: Fediverse
* Tags of this icon: Logos
* Use case: social links
* Original SVG: https://commons.m.wikimedia.org/wiki/File:Fediverse_symbol.svg
* More info: https://symbol.fediverse.info/

**Comment by xiaochunjimmy** [comment]
Please check your icon, which we added in 4.4.0

https://remixicon.com/icon/fediverse-line
https://remixicon.com/icon/fediverse-fill

If you like our project, hope you can Star our project
