### ISSUE TITLE
X Icon Not Working

### ISSUE THREAD

**Issue by TiagoMendees** [Remix-Design/RemixIcon#891]
I've seted up remix icon on visual studio code in a project of mine and its working for all the icons but not of the twiiter or X social network.

![image](https://github.com/user-attachments/assets/ca54e8e4-7acc-44d2-9fea-2e5e794ffd00)
i copy the code and i put it on the the file as it it on the next image:

![image](https://github.com/user-attachments/assets/4e9978b1-e246-4bbc-afc3-0db03b1fda06)

but on the website it only appears like this
![image](https://github.com/user-attachments/assets/eb054417-ddda-4672-b94c-57dd6a692330)

i have tried this some times, im sure that it is a bug, and i also tried the other X icon which is the same as the one i used and its still not working.
I've used this codes:
<i class="ri-twitter-x-line"></i>
<i class="ri-twitter-x-fill"></i>

**Comment by xiaochunjimmy** [comment]
Please try using our latest version to see if it can be used normally.

v4.4.0

https://remixicon.com/icon/twitter-x-fill
