### ISSUE TITLE
Snooze

### ISSUE THREAD

**Issue by NeedMoreCoffee** [Remix-Design/RemixIcon#892]
## Icon Request

* Icon name: Snooze
* Tags of this icon: notification_paused
* Use case: snoozing an alert indication
* Screenshots of similar icons:
![notifications_paused](https://github.com/user-attachments/assets/51575dc9-2014-459b-a851-0c3ea56c8b74)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/notification-snooze-line
https://remixicon.com/icon/notification-snooze-fill

https://remixicon.com/icon/alarm-snooze-line
https://remixicon.com/icon/alarm-snooze-fill
