### ISSUE TITLE
Slashed icons

### ISSUE THREAD

**Issue by Jimmy-N1** [Remix-Design/RemixIcon#897]
It would be great to have variants of some common icons with a slash, to indicate the opposite process: for instance, a star icon to add a favorite, and its opposite a slashed star to remove from favorites.

* Icon name: Star slash
* Tags of this icon: star slash, star off
* Use case: remove a score, remove from favorites
* Screenshots of similar icons:
<img width="230" alt="Capture d’écran 2024-09-04 à 15 37 58" src="https://github.com/user-attachments/assets/7cbf8e93-c7b8-402b-aa56-a21b1c60bdca">

* Icon name: Flag slash
* Tags of this icon: flag slash, flag off
* Use case: un-flag, remove from review list
* * Screenshots of similar icons:
<img width="554" alt="Capture d’écran 2024-09-04 à 15 41 00" src="https://github.com/user-attachments/assets/68400f1f-6cae-4d52-b203-0a24f5661da4">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/star-off-line
https://remixicon.com/icon/star-off-fill

https://remixicon.com/icon/flag-off-line
https://remixicon.com/icon/flag-off-fill

**Comment by Jimmy-N1** [comment]
Wow, they look great, thank you so much for taking my proposition into
consideration!

Remixicon has been my go-to icons library ever since I discovered it. Big
fan of your work!
