### ISSUE TITLE
Home #9

### ISSUE THREAD

**Issue by DynamoRed** [Remix-Design/RemixIcon#898]
## Icon Request

* Icon name: home-9
* Tags of this icon: home, house, roof
* Use case: Main page of a website, roof element
* Screenshots of similar icons:
![image](https://github.com/user-attachments/assets/04a6e7f1-117f-4410-b283-210594ac8680)

**Comment by xiaochunjimmy** [comment]
Please check your icon, which we added in 4.4.0

https://remixicon.com/icon/home-9-line
https://remixicon.com/icon/home-9-fill

If you like our project, hope you can Star our project
