### ISSUE TITLE
Information overview Icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#899]
## Icon Request

* Icon name: information overview
* Tags of this icon: info, information overview
* Use case: To see overview of profile
* Screenshots of similar icons:
<img width="115" alt="image" src="https://github.com/user-attachments/assets/08138431-d53e-4120-9a66-a2b864748738">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/info-card-line
https://remixicon.com/icon/info-card-fill
