### ISSUE TITLE
Filter icon

### ISSUE THREAD

**Issue by papenx** [Remix-Design/RemixIcon#9]
## Icon Request

* Icon name: Filter
* Tags of this icon: #Filter
* Use case: Its gonna be very helpful for creating filtering features 
* Screenshots of similar icons: https://www.google.com/search?q=filter+icon&tbm=isch&source=univ&sa=X&ved=2ahUKEwiXuZD3m7LhAhUM7aYKHVt8AyMQsAR6BAgHEAE&cshid=1554236169132664&biw=1366&bih=608

**Comment by xiaochunjimmy** [comment]
Than you for using our icons and request icons to make it better~
You'll see `filter` icons  in the next version of icons.
For now you can use [`equalizer`](https://github.com/Remix-Design/remixicon/blob/master/icons/Media/equalizer-line.svg) icon if it matches your usage scenario.

**Comment by jenstornell** [comment]
I agree that a filter icon would be very useful as well. So I vote for it as well.

**Comment by xiaochunjimmy** [comment]
I'm glad to tell you we have add 3 `Filter` icons. You can find it by searching 'filter' in our [website](https://remixicon.com); or download them from GitHub.
[filter-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-line.svg)
[filter-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-fill.svg)
[filter-2-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-2-line.svg)
[filter-2-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-2-fill.svg)
[filter-3-line](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-3-line.svg)
[filter-3-fill](https://github.com/Remix-Design/RemixIcon/blob/master/icons/System/filter-3-fill.svg)

**Comment by papenx** [comment]
thanks 👍 
good job
