### ISSUE TITLE
Icon Request: Logout box right

### ISSUE THREAD

**Issue by Rijk** [Remix-Design/RemixIcon#90]
## Icon Request

* Icon name: Logout box right
* Tags of this icon: logout
* Use case: It makes more sense to me to have the arrow point in the same direction as login. Also, going right is associated with 'continuing', 'moving on', while moving left is associated with 'going back'.
* Screenshots of similar icons: [Fontawesome](https://fontawesome.com/icons/sign-out?style=regular)

<img width="193" alt="image" src="https://user-images.githubusercontent.com/159500/65815242-689b0780-e1ed-11e9-9f4b-eef92c2538fc.png">

I like the open arrow style and square box used here better as well, compared to the Remix ones:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/159500/65815260-b748a180-e1ed-11e9-998f-f60eb9c88b7e.png">

So maybe you can make both an alternate login-box-2 and logout-box-2 in this style. Great work by the way, really enjoying the library!

**Comment by Rijk** [comment]
Here's an example of how it would look, done with simple CSS rotate:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/159500/65815303-1a3a3880-e1ee-11e9-938e-e5549eafcef5.png">

**Comment by xiaochunjimmy** [comment]
Finished
