### ISSUE TITLE
Icon Request: PIX

### ISSUE THREAD

**Issue by ViniciusBazan** [Remix-Design/RemixIcon#902]
## Icon Request

* Icon name: pix payment method
* Tags of this icon: payment, pix, checkout, order, finance
* Use case: PIX is a Brazilian payment method for instant payment, similar to FedNow in the USA. Your icon would be used when finalizing an order or when displaying accepted payment methods
* Screenshots of similar icons:
![Captura de tela 2024-09-14 201153](https://github.com/user-attachments/assets/d3939ad6-883a-4acd-8b78-1da78c601248)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/pix-fill
https://remixicon.com/icon/pix-line

Please check your icon, which we added in 4.4.0

If you like our project, hope you can Star our project
