### ISSUE TITLE
Vercel Logo (Line and Filled)

### ISSUE THREAD

**Issue by ivanrpassos** [Remix-Design/RemixIcon#905]
## Icon Request

**- Icon name:** Vercel
**- Tags of this icon:** logo and development 
**- Use case:** Vercel is a maintener of Next.js framework and a complete plataform for developers. Focused in front-end development.

**Screenshots of similar icons:**

![vercel-dark](https://github.com/user-attachments/assets/8ea191af-9492-4e8f-a5c7-a337cb36ee00)
![vercel-light](https://github.com/user-attachments/assets/43d6de8a-5998-437a-8921-4391c4b9b884)

**Comment by ivanrpassos** [comment]
See this official documentation for all brands in Vercel.

https://vercel.com/geist/introduction

**Comment by xiaochunjimmy** [comment]
Please check your icon, which we added in 4.4.0

https://remixicon.com/icon/vercel-fill
https://remixicon.com/icon/vercel-line

**Comment by ivanrpassos** [comment]
Thanks for attention in this issue ❤️
