### ISSUE TITLE
Accessibility icon

### ISSUE THREAD

**Issue by 1ashua36** [Remix-Design/RemixIcon#906]
## Icon Request

* Icon name: Accessibility
* Tags of this icon: icon request
* Use case: Indicate if an activity/feature/form/etc is accessible
* Screenshots of similar icons: <img width="106" alt="Accessibility_icon" src="https://github.com/user-attachments/assets/95fcb202-ee12-4e4d-850f-55db9f267845">

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/issues/888

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/accessibility-line
https://remixicon.com/icon/accessibility-fill

https://remixicon.com/icon/wheelchair-line
https://remixicon.com/icon/wheelchair-fill
