### ISSUE TITLE
Icon Request: Cloud Upload/Download with open arrow

### ISSUE THREAD

**Issue by Rijk** [Remix-Design/RemixIcon#91]
## Icon Request

* Icon name: Cloud upload/download 2
* Tags of this icon: upload
* Use case: 
* Screenshots of similar icons: check out [Simple Line Icons](https://simplelineicons.github.io)

<img width="485" alt="image" src="https://user-images.githubusercontent.com/159500/65816952-0e587180-e202-11e9-93e2-c28b8eb8b6b0.png">

**Comment by Rijk** [comment]
![image](https://user-images.githubusercontent.com/159500/68087824-5f8aff00-fe59-11e9-8b37-bd6454adf4bd.png)

Beautiful! 👌

**Comment by Rijk** [comment]
Really, great execution on this one. It looks so nice in my app 😍

![image](https://user-images.githubusercontent.com/159500/68088024-54d16980-fe5b-11e9-8deb-c4bc16aa948d.png)


![image](https://user-images.githubusercontent.com/159500/68088041-72063800-fe5b-11e9-88c1-9aad4554451d.png)

**Comment by xiaochunjimmy** [comment]
Your app looks beautiful
