### ISSUE TITLE
Icon Request: Sticky Note

### ISSUE THREAD

**Issue by Rijk** [Remix-Design/RemixIcon#92]
## Icon Request

* Icon name: Sticky Note (various)
* Tags of this icon: note, post-it, sticky-note
* Use case: Internal comments/replies, notes
* Screenshots of similar icons: It is basically the Remix file icon, but in square aspect ratio, and with the folded corner on the bottom right side. Check out the [Fontawesome](https://fontawesome.com/icons/sticky-note?style=regular) version which is great.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/159500/65834314-fc4a0200-e2d9-11e9-881e-2f09a3ea6c18.png">

Basically, this one but square:

<img width="94" alt="image" src="https://user-images.githubusercontent.com/159500/65834324-0ff56880-e2da-11e9-9d69-929de0ac0b38.png">

It would also be nice to have a variant with this corner style, but with nothing on it:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/159500/65834337-30252780-e2da-11e9-9840-f5d33e785045.png">

That would be useful in cases where you want to put something on it yourself (like a number);

<img width="39" alt="image" src="https://user-images.githubusercontent.com/159500/65834378-86926600-e2da-11e9-9540-6445fa93d360.png">

**Comment by xiaochunjimmy** [comment]
Thank you for your advice.

**Comment by xiaochunjimmy** [comment]
Now you can find them from [our website](https://remixicon.com/#document)

**Comment by Rijk** [comment]
Really cool! 👍
