### ISSUE TITLE
官网 arrow-down-box-line icon 错误应用成 arrow-left-down-box-line

### ISSUE THREAD

**Issue by yikZero** [Remix-Design/RemixIcon#921]
链接：https://remixicon.com/icon/arrow-down-box-line

![RoShot 2024-10-23 at 13 35 17@2x](https://github.com/user-attachments/assets/c9a582c8-6042-409d-9f13-6d23b4487a53)

**Comment by yikZero** [comment]
@xiaochunjimmy 你好，非常感谢提供了 remix icon 这么高质量的图标库。我在应用最新 v4.4.0 的时候发现arrow-down-box-line的图标错误应用成 arrow-left-down-box-line，具体可查看[链接](https://remixicon.com/icon/arrow-down-box-line)。

本来想提个pr，但好像不只是替换个图标名字这么简单。就还是提一个问题。再次表示感谢

**Comment by wendygaoyuan** [comment]
感谢反馈，问题已收到，会尽快修复
