### ISSUE TITLE
long tailed arrows

### ISSUE THREAD

**Issue by juliomariutti** [Remix-Design/RemixIcon#922]
## Icon Request

* Icon name: long-arrow- (left-up, up, left-right, right, right-down, down, left-down, left) -line
* Tags of this icon: Arrows
* Use case: back links, text and arrow links, signage directions, etc.
* Screenshots of similar icons:
<img width="312" alt="Screenshot 2024-10-24 at 11 09 59" src="https://github.com/user-attachments/assets/d29c6d56-465e-45b5-8eca-c7125146b308">
<img width="266" alt="Screenshot 2024-10-24 at 11 05 45" src="https://github.com/user-attachments/assets/aa36080b-d721-499c-9aeb-deb6874bf520">
<img width="737" alt="Screenshot 2024-10-24 at 11 06 36" src="https://github.com/user-attachments/assets/edde5eba-1560-4846-90d5-059d8aa6a790">
<img width="1179" alt="Screenshot 2024-10-24 at 11 08 35" src="https://github.com/user-attachments/assets/3ccbed6e-fc98-4690-ba46-bdc252e56a6f">
<img width="590" alt="Screenshot 2024-10-24 at 11 09 17" src="https://github.com/user-attachments/assets/5b44a397-7e36-481b-a052-1104753229cd">

**Comment by xiaochunjimmy** [comment]
Added in v4.6.0
