### ISSUE TITLE
Pix logo icon is missing

### ISSUE THREAD

**Issue by azhikodan** [Remix-Design/remixicon#925]
**Describe the bug**
The SVG icons for pix-fill and pix-line in the Logos collection either have incorrect files or are missing the appropriate files.

**To Reproduce**
1. Go to the Logos folder.
2. Check the files for pix-fill and pix-line.

**Expected behavior**
The SVG icons for pix-fill and pix-line in the Logos collection may have issues, as they either contain incorrect files or are missing the necessary files altogether. This discrepancy can impact the consistency and functionality of the icon set, potentially causing display or usability issues. It’s essential to review and verify these icons to ensure they meet the required specifications. If necessary, the icons should be replaced or updated to align with the standards of the collection, ensuring all icons in the Logos collection are accurate and readily usable.

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/f907fff6-bf4d-4052-b6fe-01975d1acd08)

**Device (please complete the following information):**
 - OS: Mac OS 14.7.1

**Additional context**

**Comment by xiaochunjimmy** [comment]
Thank you for the feedback, we will try to fix it in the next version.
