### ISSUE TITLE
New icon request - Alarm Add

### ISSUE THREAD

**Issue by NeedMoreCoffee** [Remix-Design/RemixIcon#926]
## Icon Request

* Icon name: alarm-add
* Tags of this icon: 

* Use case: Ability to add an alarm or alert to a specific time/date
* Screenshots of similar icons:
![Alarm-Add](https://github.com/user-attachments/assets/1cdc97c5-e0ba-4706-9876-58ad801fb021)
![alarm-add](https://github.com/user-attachments/assets/c8d3edec-dc44-45d6-bb78-67ac483b92f2)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/alarm-add-line
https://remixicon.com/icon/alarm-add-fill
