### ISSUE TITLE
Firefox brand logo used instead of Firefox browser

### ISSUE THREAD

**Issue by FormularSumo** [Remix-Design/RemixIcon#927]
The Firefox logo currently used by Remix Icons is the general Firefox brand, rather than the browser. I believe this is probably a mistake, as the browser tends to be better known and is probably what was intended. If not, then I think it would be helpful to also include the browser in the icon pack given that many other popular browser logos do feature.

Explainer
![FX_Design_Blog_Logos_Family](https://github.com/MicrosoftEdge/MSEdgeExplainers/assets/36278229/10d83e56-0f0e-4c5b-9d5b-70a8155cd90f)
From https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/

This is an example of what the monochrome Firefox browser logo looks like, adapted from https://mozilla.design/files/2019/10/Firefox-Browser-Logo-Assets.zip
![firefox](https://github.com/MicrosoftEdge/MSEdgeExplainers/assets/36278229/3920dee4-a582-43e0-baa3-15b6b58a0575)

Vs the currently included brand one
https://github.com/Remix-Design/RemixIcon/blob/c1c01303b97f81bce88374220e08c3d80c9f241a/icons/Logos/firefox-fill.svg?plain=1

**Comment by xiaochunjimmy** [comment]
Thank you for your feedback, it is very valuable.

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/firefox-browser-line
https://remixicon.com/icon/firefox-browser-fill
