### ISSUE TITLE
Service Icon

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#928]
## Icon Request

* Icon name: Service
* Tags of this icon: service, hotel service, helpdesk, bell
* Screenshots of similar icons:
<img width="310" alt="image" src="https://github.com/user-attachments/assets/39c166c7-d367-4386-9161-563884d15fb0">

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/service-bell-line
https://remixicon.com/icon/service-bell-fill
