### ISSUE TITLE
Icon Request: Hammer Icon / Build

### ISSUE THREAD

**Issue by bramaudi** [Remix-Design/RemixIcon#93]
## Icon Request

* Icon name: Hammer
* Tags of this icon: hammer,build
* Use case: -
* Screenshots of similar icons: -

**Comment by xiaochunjimmy** [comment]
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Design/hammer-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Design/hammer-line.svg
or
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Finance/auction-fill.svg
https://github.com/Remix-Design/RemixIcon/blob/master/icons/Finance/auction-line.svg
