### ISSUE TITLE
checkbox-circle-line stem gets too close to enclosing circle

### ISSUE THREAD

**Issue by lowfatcode** [Remix-Design/RemixIcon#930]
**Describe the bug**
The icon `checkbox-circle-line` feels like it comes to close to the enclosing circle making it inconsistent with other circle icons such as `indeterminate-circle-line` and `close-circle-line`.

**Expected behavior**
I appreciate this is subjective but it feels off to me!

**Screenshots**

**Device (please complete the following information):**
 - macOS 14.4 (23E214)
 - Safari Version 17.4 (19618.1.15.11.12)

**Comment by xiaochunjimmy** [comment]
The icon optimization has been completed, thank you for the feedback and suggestions.

https://remixicon.com/icon/checkbox-circle-line
https://remixicon.com/icon/checkbox-circle-fill
