### ISSUE TITLE
New icon request, figma icon

### ISSUE THREAD

**Issue by anjiattri** [Remix-Design/RemixIcon#932]
## Icon Request

* Icon name: Figma
* Tags of this icon: figma
* Use case: need to use figma icon in my website
* Screenshots of similar icons:
![Vector (1)](https://github.com/user-attachments/assets/7f117443-1f08-4cc4-84c8-eae7912c8d0a)
![Vector (1)](https://github.com/user-attachments/assets/daca3bee-15d5-4d7d-bba6-41dcab564c3c)

**Comment by xiaochunjimmy** [comment]
https://remixicon.com/icon/figma-line
https://remixicon.com/icon/figma-fill
