### ISSUE TITLE
Medium has updated its logo.

### ISSUE THREAD

**Issue by minpeter** [Remix-Design/RemixIcon#937]
## Icon Request

* Icon name: RiMediumFill
* Tags of this icon: RiMediumFill
* Use case: For medium social display
* Screenshots of similar icons: 

ref: https://medium.design/logos-and-brand-guidelines-f1a01a733592?gi=196348293a26

![image](https://github.com/user-attachments/assets/69a08abe-c289-43ad-a35e-06bd6706b8d6)

rel issue: https://github.com/Remix-Design/RemixIcon/issues/701

**Comment by xiaochunjimmy** [comment]
Thank you for your feedback, they really change the icons too frequently.

**Comment by xiaochunjimmy** [comment]
Update completed
