### ISSUE TITLE
Icon naming problem(`book-mark` and `bookmark`)

### ISSUE THREAD

**Issue by chenyueban** [Remix-Design/RemixIcon#94]
**Describe the bug**

When using the `book-mark` and `bookmark` icons, They always make me misunderstand as another icon.

---

每当我使用 `book-mark` and `bookmark` 这两个图标时，我总是会误用到另外一个图标。

**Expected behavior**

I think it is more appropriate to change `book-mark` to `dictionary-mark`.

---

我认为把 `book-mark` 改为 `dictionary-mark` 更符合图标意义且不容易让人混淆

Just personal advice
只是个人建议

**Comment by xiaochunjimmy** [comment]
非常感谢你的建议，这个确实是一开始在命名的时候我考虑得不太周全。

之前之所以用book-mark而不是dictionary-mark或者其他，主要是因为前面的相似图标叫book，这个是在其基础上增加了一点变形...

但是改名有一定的风险，如果用户已经在使用这个图标，并且更新了最新的图标字体库版本，如果没能及时同步更新他的项目，将可能导致图标无法展示。
