### ISSUE TITLE
Coupon Icon

### ISSUE THREAD

**Issue by hyedyhyedy** [Remix-Design/RemixIcon#95]
<img width="564" alt="Screen Shot 2019-10-02 at 16 21 18" src="https://user-images.githubusercontent.com/36624358/66052575-1d586000-e531-11e9-82ec-1ff808b09316.png">

Hi, thanks for the icons. It's so useful :) 
But I found one error in one of the coupon icons.
Please refer to the image I attached. 

Best wishes,
Hyejin

**Comment by xiaochunjimmy** [comment]
I am very grateful that pointing out the problem to help us improve our products.
We will fix it in the next version.
Thank you.

**Comment by xiaochunjimmy** [comment]
We've fixed this bug in v2.1.0.
Sorry for waiting for a month-long time.
