### ISSUE TITLE
Icon Request: pin / pushpin

### ISSUE THREAD

**Issue by alvaromartmart** [Remix-Design/RemixIcon#97]
## Icon Request

* Icon name: pin
* Tags of this icon: pin, pushpin
* Use case: i.e. pin a specific block of the UI to the top of the page, etc
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/18287793/66487990-8d289680-eaad-11e9-94e0-8946b3918f8c.png)

**Comment by xiaochunjimmy** [comment]
We've added 2 styles of the pushpin icons.
You can search `push` from our website to find them.

**Comment by alvaromartmart** [comment]
Great, thanks!!
