### ISSUE TITLE
Icon request: box

### ISSUE THREAD

**Issue by mtancoigne** [Remix-Design/RemixIcon#98]
## Icon Request

Hi!

I forked and created the icon before reading that you prefer issues over PRs. The icon is the "inbox" icon without the arrow, making it a generic "box".

* Icon name: box
* Tags of this icon: box
* Use case: represent a box or container
* Screenshots of similar icons: 
	- https://github.com/el-cms/RemixIcon/blob/box/icons/Life/box-fill.svg
	- https://github.com/el-cms/RemixIcon/blob/box/icons/Life/box-line.svg

If you're interested and the icon fits your design requirements, you can pick [the commit](https://github.com/el-cms/RemixIcon/commit/6e54fa1a5cdb9f4edb68e14a8dda9dd65cdcba8c) directly :)

**Comment by xiaochunjimmy** [comment]
Thank you for your suggestion and icons. We will include them in the next version.

**Comment by mtancoigne** [comment]
Thanks for your great job on these icons !
