### ISSUE TITLE
Gender Icon

### ISSUE THREAD

**Issue by Achanchill** [Remix-Design/RemixIcon#99]
## Icon Request

* Icon name: Gender Icon
* Tags of this icon: Gender
* Use case: for sex icon like male or female
* Screenshots of similar icons:

**Comment by itsezc** [comment]
They already exist:

**Comment by xiaochunjimmy** [comment]
@itsezc Thank you for your explanation.

@Achanchill Are these icons what you want?

**Comment by xiaochunjimmy** [comment]
I added `male` and `female` keywords to these icons.

**Comment by itsezc** [comment]
@xiaochunjimmy you may close this issue, it has been resolved (:
